-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Recreate the Oracle EBS Inventory Organization configuration table
-- for the final Adhesives Research Inventory Item Creation application.
--
-- This table defines the Inventory Organizations that can participate
-- in an Item Request.
--
-- Organizations can be configured as:
--   - MASTER
--   - TARGET
--
-- The application will use this table instead of hardcoding Oracle EBS
-- organization identifiers or organization codes in APEX or PL/SQL.
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Drop the existing table when it already exists.
--
-- CASCADE CONSTRAINTS removes foreign key references from previously
-- created application objects when rebuilding the schema.
--
-- ORA-00942 is ignored because it means the table does not exist.
-- Any other Oracle error is raised normally.
-- =====================================================================

BEGIN
    EXECUTE IMMEDIATE
        'DROP TABLE ops.adre_inv_item_org CASCADE CONSTRAINTS PURGE';

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Create the Oracle EBS Inventory Organization configuration table.
-- =====================================================================

CREATE TABLE ops.adre_inv_item_org
(
    item_org_id
        NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        NOT NULL,

    organization_id
        NUMBER
        NOT NULL,

    organization_code
        VARCHAR2(30)
        NOT NULL,

    organization_name
        VARCHAR2(240)
        NOT NULL,

    default_role
        VARCHAR2(30)
        NOT NULL,

    active_flag
        VARCHAR2(1)
        DEFAULT 'Y'
        NOT NULL,

    display_sequence
        NUMBER
        DEFAULT 10
        NOT NULL,

    created_by
        VARCHAR2(100)
        NOT NULL,

    creation_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_updated_by
        VARCHAR2(100)
        NOT NULL,

    last_update_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_update_login
        VARCHAR2(100),

    record_version_number
        NUMBER
        DEFAULT 1
        NOT NULL,

    CONSTRAINT adre_inv_item_org_pk
        PRIMARY KEY
        (
            item_org_id
        ),

    CONSTRAINT adre_inv_item_org_u1
        UNIQUE
        (
            organization_id
        ),

    CONSTRAINT adre_inv_item_org_u2
        UNIQUE
        (
            organization_code
        ),

    CONSTRAINT adre_inv_item_org_ck1
        CHECK
        (
            default_role IN
            (
                'MASTER',
                'TARGET'
            )
        ),

    CONSTRAINT adre_inv_item_org_ck2
        CHECK
        (
            active_flag IN
            (
                'Y',
                'N'
            )
        ),

    CONSTRAINT adre_inv_item_org_ck3
        CHECK
        (
            organization_id > 0
        ),

    CONSTRAINT adre_inv_item_org_ck4
        CHECK
        (
            display_sequence > 0
        ),

    CONSTRAINT adre_inv_item_org_ck5
        CHECK
        (
            record_version_number > 0
        )
);


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support Oracle APEX LOVs and configuration screens that display
-- active organizations in the configured sequence.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_org_n1
    ON ops.adre_inv_item_org
    (
        active_flag,
        display_sequence
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support filtering organizations by their default MASTER or TARGET
-- role.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_org_n2
    ON ops.adre_inv_item_org
    (
        default_role,
        active_flag
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add table documentation.
-- =====================================================================

COMMENT ON TABLE ops.adre_inv_item_org IS
'Configuration table containing Oracle EBS Inventory Organizations available to the Adhesives Research Inventory Item Creation application.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add column documentation.
-- =====================================================================

COMMENT ON COLUMN ops.adre_inv_item_org.item_org_id IS
'Surrogate primary key generated by Oracle for the application organization configuration.';

COMMENT ON COLUMN ops.adre_inv_item_org.organization_id IS
'Oracle EBS Inventory Organization identifier.';

COMMENT ON COLUMN ops.adre_inv_item_org.organization_code IS
'Oracle EBS Inventory Organization code such as MAS or GRI.';

COMMENT ON COLUMN ops.adre_inv_item_org.organization_name IS
'User-facing name of the Oracle EBS Inventory Organization.';

COMMENT ON COLUMN ops.adre_inv_item_org.default_role IS
'Default role of the organization in an Item Request. Valid values are MASTER and TARGET.';

COMMENT ON COLUMN ops.adre_inv_item_org.active_flag IS
'Indicates whether the organization is available for use in the application. Valid values are Y and N.';

COMMENT ON COLUMN ops.adre_inv_item_org.display_sequence IS
'Controls the display order of organizations in Oracle APEX.';

COMMENT ON COLUMN ops.adre_inv_item_org.created_by IS
'Application or database user that created the row.';

COMMENT ON COLUMN ops.adre_inv_item_org.creation_date IS
'Date and time when the row was created.';

COMMENT ON COLUMN ops.adre_inv_item_org.last_updated_by IS
'Application or database user that last updated the row.';

COMMENT ON COLUMN ops.adre_inv_item_org.last_update_date IS
'Date and time when the row was last updated.';

COMMENT ON COLUMN ops.adre_inv_item_org.last_update_login IS
'Oracle APEX session identifier or database login associated with the last update.';

COMMENT ON COLUMN ops.adre_inv_item_org.record_version_number IS
'Row version number used for change tracking and optimistic locking.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Automatically maintain audit information and normalize organization
-- configuration values for ADRE_INV_ITEM_ORG.
-- =====================================================================

CREATE OR REPLACE TRIGGER ops.adre_inv_item_org_biu
BEFORE INSERT OR UPDATE
ON ops.adre_inv_item_org
FOR EACH ROW

DECLARE

    l_user
        VARCHAR2(100);

    l_login
        VARCHAR2(100);

BEGIN

    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX user when available.
    --
    -- Use the current Oracle database user when the operation is
    -- executed outside Oracle APEX.
    -- =================================================================

    l_user :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_USER'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX session identifier when available.
    -- =================================================================

    l_login :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_SESSION'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the Oracle EBS Organization Code.
    --
    -- Example:
    -- gri
    --
    -- becomes:
    -- GRI
    -- =================================================================

    :NEW.organization_code :=
        UPPER
        (
            TRIM
            (
                :NEW.organization_code
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the configured default organization role.
    -- =================================================================

    :NEW.default_role :=
        UPPER
        (
            TRIM
            (
                :NEW.default_role
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the active indicator.
    -- =================================================================

    :NEW.active_flag :=
        UPPER
        (
            TRIM
            (
                :NEW.active_flag
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Remove unnecessary leading and trailing spaces from the
    -- organization display name.
    -- =================================================================

    :NEW.organization_name :=
        TRIM
        (
            :NEW.organization_name
        );


    IF INSERTING THEN

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize creation audit information for a new organization.
        -- =============================================================

        :NEW.created_by :=
            NVL
            (
                :NEW.created_by,
                l_user
            );


        :NEW.creation_date :=
            NVL
            (
                :NEW.creation_date,
                SYSDATE
            );


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize the first row version.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :NEW.record_version_number,
                1
            );

    ELSE

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Preserve the original creation audit information.
        -- =============================================================

        :NEW.created_by :=
            :OLD.created_by;

        :NEW.creation_date :=
            :OLD.creation_date;


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Increment the row version number on every update.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :OLD.record_version_number,
                0
            ) + 1;

    END IF;


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Refresh last-update audit information for inserts and updates.
    -- =================================================================

    :NEW.last_updated_by :=
        l_user;

    :NEW.last_update_date :=
        SYSDATE;

    :NEW.last_update_login :=
        l_login;

END;
/

-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the table exists and is VALID.
--
-- ALL_OBJECTS uses OBJECT_NAME for the object identifier.
-- =====================================================================

SELECT
    owner,
    object_name AS table_name,
    status
FROM all_objects
WHERE owner = 'OPS'
  AND object_name = 'ADRE_INV_ITEM_ORG'
  AND object_type = 'TABLE';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the audit trigger exists and is enabled.
-- =====================================================================

SELECT
    owner,
    trigger_name,
    table_name,
    status
FROM all_triggers
WHERE owner = 'OPS'
  AND trigger_name = 'ADRE_INV_ITEM_ORG_BIU';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Check for trigger compilation errors.
--
-- A successful trigger compilation must return zero rows.
-- =====================================================================

SELECT
    line,
    position,
    text
FROM all_errors
WHERE owner = 'OPS'
  AND name = 'ADRE_INV_ITEM_ORG_BIU'
  AND type = 'TRIGGER'
ORDER BY sequence;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the table comment.
-- =====================================================================

SELECT
    table_name,
    comments
FROM all_tab_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_ORG';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate all column comments.
-- =====================================================================

SELECT
    column_name,
    comments
FROM all_col_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_ORG'
ORDER BY column_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================