-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Recreate the centralized Oracle EBS integration logging table for the
-- final Adhesives Research Inventory Item Creation application.
--
-- This table records the execution history generated when an Item
-- Request is processed and sent to Oracle EBS.
--
-- One Send to EBS execution can generate multiple log entries.
--
-- EXECUTION_ID groups all log entries generated by the same execution.
--
-- ITEM_REQUEST_ID identifies the Item Request being processed.
--
-- REQUEST_ORG_ID is optional because some integration operations apply
-- to the complete Item Request instead of a specific organization.
--
-- ENTITY_TYPE and ENTITY_ID identify the transaction object associated
-- with the log entry without requiring separate foreign key columns for
-- every transaction table.
--
-- Example ENTITY_TYPE values:
--   ITEM
--   ORGANIZATION
--   CATEGORY
--   ATTRIBUTE
--   DOCUMENT
--   BOM
--   BOM_COMPONENT
--
-- LOG_LEVEL identifies the severity of the log entry.
--
-- PROCESS_STATUS identifies the application processing result.
--
-- API_RETURN_STATUS preserves the native Oracle EBS API return status
-- when one is available.
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Drop the existing table when it already exists.
--
-- CASCADE CONSTRAINTS removes foreign key references from previously
-- created dependent application objects during the schema rebuild.
--
-- ORA-00942 is ignored because it means the table does not exist.
-- Any other Oracle error is raised normally.
-- =====================================================================

BEGIN
    EXECUTE IMMEDIATE
        'DROP TABLE ops.adre_inv_item_api_log CASCADE CONSTRAINTS PURGE';

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Create the centralized Oracle EBS integration logging table.
-- =====================================================================

CREATE TABLE ops.adre_inv_item_api_log
(
    item_api_log_id
        NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        NOT NULL,

    execution_id
        VARCHAR2(100)
        NOT NULL,

    item_request_id
        NUMBER
        NOT NULL,

    request_org_id
        NUMBER,

    process_name
        VARCHAR2(100)
        NOT NULL,

    api_name
        VARCHAR2(240),

    entity_type
        VARCHAR2(50),

    entity_id
        NUMBER,

    log_level
        VARCHAR2(20)
        DEFAULT 'INFO'
        NOT NULL,

    process_status
        VARCHAR2(30),

    api_return_status
        VARCHAR2(10),

    api_message_count
        NUMBER,

    message_text
        CLOB,

    execution_start_date
        DATE,

    execution_end_date
        DATE,

    elapsed_milliseconds
        NUMBER,

    created_by
        VARCHAR2(100)
        NOT NULL,

    creation_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_updated_by
        VARCHAR2(100)
        NOT NULL,

    last_update_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_update_login
        VARCHAR2(100),

    record_version_number
        NUMBER
        DEFAULT 1
        NOT NULL,

    CONSTRAINT adre_inv_item_api_log_pk
        PRIMARY KEY
        (
            item_api_log_id
        ),

    CONSTRAINT adre_inv_item_api_log_fk1
        FOREIGN KEY
        (
            item_request_id
        )
        REFERENCES ops.adre_inv_item_request
        (
            item_request_id
        ),

    CONSTRAINT adre_inv_item_api_log_fk2
        FOREIGN KEY
        (
            request_org_id
        )
        REFERENCES ops.adre_inv_item_request_org
        (
            request_org_id
        ),

    CONSTRAINT adre_inv_item_api_log_ck1
        CHECK
        (
            log_level IN
            (
                'DEBUG',
                'INFO',
                'WARNING',
                'ERROR'
            )
        ),

    CONSTRAINT adre_inv_item_api_log_ck2
        CHECK
        (
            process_status IS NULL
            OR process_status IN
            (
                'STARTED',
                'SUCCESS',
                'ERROR',
                'WARNING',
                'SKIPPED'
            )
        ),

    CONSTRAINT adre_inv_item_api_log_ck3
        CHECK
        (
            api_message_count IS NULL
            OR api_message_count >= 0
        ),

    CONSTRAINT adre_inv_item_api_log_ck4
        CHECK
        (
            elapsed_milliseconds IS NULL
            OR elapsed_milliseconds >= 0
        ),

    CONSTRAINT adre_inv_item_api_log_ck5
        CHECK
        (
            execution_end_date IS NULL
            OR execution_start_date IS NULL
            OR execution_end_date >= execution_start_date
        ),

    CONSTRAINT adre_inv_item_api_log_ck6
        CHECK
        (
            entity_id IS NULL
            OR entity_id > 0
        ),

    CONSTRAINT adre_inv_item_api_log_ck7
        CHECK
        (
            record_version_number > 0
        )
);


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support retrieval of the complete chronological history generated by
-- one Send to EBS execution.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_api_log_n1
    ON ops.adre_inv_item_api_log
    (
        execution_id,
        item_api_log_id
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support retrieval of all integration activity associated with one
-- Item Request.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_api_log_n2
    ON ops.adre_inv_item_api_log
    (
        item_request_id,
        creation_date
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support retrieval of integration activity associated with one Item
-- Request organization.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_api_log_n3
    ON ops.adre_inv_item_api_log
    (
        request_org_id,
        creation_date
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support monitoring and troubleshooting of integration errors and
-- warnings.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_api_log_n4
    ON ops.adre_inv_item_api_log
    (
        process_status,
        log_level,
        creation_date
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support retrieval of log entries associated with a specific
-- transaction entity.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_api_log_n5
    ON ops.adre_inv_item_api_log
    (
        entity_type,
        entity_id
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support reporting and troubleshooting by integration process.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_api_log_n6
    ON ops.adre_inv_item_api_log
    (
        process_name,
        creation_date
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add table documentation.
-- =====================================================================

COMMENT ON TABLE ops.adre_inv_item_api_log IS
'Centralized integration logging table containing Oracle EBS processing history for Adhesives Research Inventory Item Requests.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add column documentation.
-- =====================================================================

COMMENT ON COLUMN ops.adre_inv_item_api_log.item_api_log_id IS
'Surrogate primary key generated by Oracle for each integration log entry.';

COMMENT ON COLUMN ops.adre_inv_item_api_log.execution_id IS
'Identifier used to group all log entries generated by the same Send to EBS execution.';

COMMENT ON COLUMN ops.adre_inv_item_api_log.item_request_id IS
'Foreign key identifying the Item Request associated with the integration log entry.';

COMMENT ON COLUMN ops.adre_inv_item_api_log.request_org_id IS
'Optional foreign key identifying the Item Request organization associated with the integration operation.';

COMMENT ON COLUMN ops.adre_inv_item_api_log.process_name IS
'Application process name associated with the integration log entry.';

COMMENT ON COLUMN ops.adre_inv_item_api_log.api_name IS
'Oracle EBS or integration API name associated with the operation.';

COMMENT ON COLUMN ops.adre_inv_item_api_log.entity_type IS
'Logical transaction entity type associated with the log entry, such as ITEM, ORGANIZATION, CATEGORY, ATTRIBUTE, DOCUMENT, BOM or BOM_COMPONENT.';

COMMENT ON COLUMN ops.adre_inv_item_api_log.entity_id IS
'Identifier of the logical transaction entity associated with the log entry.';

COMMENT ON COLUMN ops.adre_inv_item_api_log.log_level IS
'Severity level of the log entry. Valid values are DEBUG, INFO, WARNING and ERROR.';

COMMENT ON COLUMN ops.adre_inv_item_api_log.process_status IS
'Application processing result. Valid values are STARTED, SUCCESS, ERROR, WARNING, SKIPPED or NULL when not applicable.';

COMMENT ON COLUMN ops.adre_inv_item_api_log.api_return_status IS
'Native Oracle EBS or integration API return status when one is available.';

COMMENT ON COLUMN ops.adre_inv_item_api_log.api_message_count IS
'Number of messages returned by the Oracle EBS or integration API.';

COMMENT ON COLUMN ops.adre_inv_item_api_log.message_text IS
'Detailed application, processing or Oracle EBS API message associated with the log entry.';

COMMENT ON COLUMN ops.adre_inv_item_api_log.execution_start_date IS
'Date and time when the logged integration operation started.';

COMMENT ON COLUMN ops.adre_inv_item_api_log.execution_end_date IS
'Date and time when the logged integration operation ended.';

COMMENT ON COLUMN ops.adre_inv_item_api_log.elapsed_milliseconds IS
'Elapsed processing time for the logged operation expressed in milliseconds.';

COMMENT ON COLUMN ops.adre_inv_item_api_log.created_by IS
'Application or database user that created the log entry.';

COMMENT ON COLUMN ops.adre_inv_item_api_log.creation_date IS
'Date and time when the log entry was created.';

COMMENT ON COLUMN ops.adre_inv_item_api_log.last_updated_by IS
'Application or database user that last updated the log entry.';

COMMENT ON COLUMN ops.adre_inv_item_api_log.last_update_date IS
'Date and time when the log entry was last updated.';

COMMENT ON COLUMN ops.adre_inv_item_api_log.last_update_login IS
'Oracle APEX session identifier or database login associated with the last update.';

COMMENT ON COLUMN ops.adre_inv_item_api_log.record_version_number IS
'Row version number used for change tracking and optimistic locking.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Automatically maintain audit information and normalize integration
-- logging values for ADRE_INV_ITEM_API_LOG.
-- =====================================================================

CREATE OR REPLACE TRIGGER ops.adre_inv_item_api_log_biu
BEFORE INSERT OR UPDATE
ON ops.adre_inv_item_api_log
FOR EACH ROW

DECLARE

    l_user
        VARCHAR2(100);

    l_login
        VARCHAR2(100);

BEGIN

    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX user when available.
    --
    -- Use the current Oracle database user when the operation is
    -- executed outside Oracle APEX.
    -- =================================================================

    l_user :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_USER'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX session identifier when available.
    -- =================================================================

    l_login :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_SESSION'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Remove unnecessary leading and trailing spaces from the execution
    -- identifier.
    -- =================================================================

    :NEW.execution_id :=
        TRIM
        (
            :NEW.execution_id
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the application process name.
    -- =================================================================

    :NEW.process_name :=
        UPPER
        (
            TRIM
            (
                :NEW.process_name
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Preserve the Oracle EBS API name while removing unnecessary
    -- leading and trailing spaces.
    -- =================================================================

    :NEW.api_name :=
        TRIM
        (
            :NEW.api_name
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the logical entity type.
    -- =================================================================

    :NEW.entity_type :=
        UPPER
        (
            TRIM
            (
                :NEW.entity_type
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the log severity level.
    -- =================================================================

    :NEW.log_level :=
        UPPER
        (
            TRIM
            (
                :NEW.log_level
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the application process status.
    -- =================================================================

    :NEW.process_status :=
        UPPER
        (
            TRIM
            (
                :NEW.process_status
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the Oracle EBS API return status when populated.
    -- =================================================================

    :NEW.api_return_status :=
        UPPER
        (
            TRIM
            (
                :NEW.api_return_status
            )
        );


    IF INSERTING THEN

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize creation audit information for a new integration
        -- log entry.
        -- =============================================================

        :NEW.created_by :=
            NVL
            (
                :NEW.created_by,
                l_user
            );


        :NEW.creation_date :=
            NVL
            (
                :NEW.creation_date,
                SYSDATE
            );


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize the first row version.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :NEW.record_version_number,
                1
            );

    ELSE

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Preserve the original creation audit information.
        -- =============================================================

        :NEW.created_by :=
            :OLD.created_by;

        :NEW.creation_date :=
            :OLD.creation_date;


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Increment the row version number on every update.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :OLD.record_version_number,
                0
            ) + 1;

    END IF;


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Refresh last-update audit information for inserts and updates.
    -- =================================================================

    :NEW.last_updated_by :=
        l_user;

    :NEW.last_update_date :=
        SYSDATE;

    :NEW.last_update_login :=
        l_login;

END;
/

-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the table exists and is VALID.
--
-- ALL_OBJECTS uses OBJECT_NAME for the object identifier.
-- =====================================================================

SELECT
    owner,
    object_name AS table_name,
    status
FROM all_objects
WHERE owner = 'OPS'
  AND object_name = 'ADRE_INV_ITEM_API_LOG'
  AND object_type = 'TABLE';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the audit trigger exists and is enabled.
-- =====================================================================

SELECT
    owner,
    trigger_name,
    table_name,
    status
FROM all_triggers
WHERE owner = 'OPS'
  AND trigger_name = 'ADRE_INV_ITEM_API_LOG_BIU';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Check for trigger compilation errors.
--
-- A successful trigger compilation must return zero rows.
-- =====================================================================

SELECT
    line,
    position,
    text
FROM all_errors
WHERE owner = 'OPS'
  AND name = 'ADRE_INV_ITEM_API_LOG_BIU'
  AND type = 'TRIGGER'
ORDER BY sequence;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the table comment.
-- =====================================================================

SELECT
    table_name,
    comments
FROM all_tab_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_API_LOG';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate all column comments.
-- =====================================================================

SELECT
    column_name,
    comments
FROM all_col_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_API_LOG'
ORDER BY column_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the constraints created for the centralized integration
-- logging table.
-- =====================================================================

SELECT
    constraint_name,
    constraint_type,
    status,
    r_constraint_name
FROM all_constraints
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_API_LOG'
ORDER BY constraint_type,
         constraint_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate all indexes associated with the integration log table.
-- =====================================================================

SELECT
    index_name,
    uniqueness,
    status
FROM all_indexes
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_API_LOG'
ORDER BY index_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================