-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Recreate the Item Type configuration table for the final
-- Adhesives Research Inventory Item Creation application.
--
-- This table defines the valid Item Types available in Oracle APEX.
--
-- Item Type will be one of the main drivers used by the application
-- to determine:
--   - Which attributes are displayed.
--   - Which attributes are required.
--   - Which template rules apply.
--   - Which organization-specific information must be completed.
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Drop the existing table when it already exists.
--
-- ORA-00942 is ignored because it means the table does not exist.
-- Any other Oracle error is raised normally.
-- =====================================================================

BEGIN
    EXECUTE IMMEDIATE
        'DROP TABLE ops.adre_inv_item_type CASCADE CONSTRAINTS PURGE';

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Create the Item Type configuration table.
-- =====================================================================

CREATE TABLE ops.adre_inv_item_type
(
    item_type_id
        NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        NOT NULL,

    item_type_code
        VARCHAR2(50)
        NOT NULL,

    item_type_name
        VARCHAR2(240)
        NOT NULL,

    description
        VARCHAR2(1000),

    active_flag
        VARCHAR2(1)
        DEFAULT 'Y'
        NOT NULL,

    display_sequence
        NUMBER
        DEFAULT 10
        NOT NULL,

    created_by
        VARCHAR2(100)
        NOT NULL,

    creation_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_updated_by
        VARCHAR2(100)
        NOT NULL,

    last_update_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_update_login
        VARCHAR2(100),

    record_version_number
        NUMBER
        DEFAULT 1
        NOT NULL,

    CONSTRAINT adre_inv_item_type_pk
        PRIMARY KEY
        (
            item_type_id
        ),

    CONSTRAINT adre_inv_item_type_u1
        UNIQUE
        (
            item_type_code
        ),

    CONSTRAINT adre_inv_item_type_ck1
        CHECK
        (
            active_flag IN ('Y', 'N')
        ),

    CONSTRAINT adre_inv_item_type_ck2
        CHECK
        (
            display_sequence > 0
        ),

    CONSTRAINT adre_inv_item_type_ck3
        CHECK
        (
            record_version_number > 0
        )
);


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Create an index to support Oracle APEX LOVs and configuration
-- screens that return active Item Types in display sequence.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_type_n1
    ON ops.adre_inv_item_type
    (
        active_flag,
        display_sequence
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add table documentation.
-- =====================================================================

COMMENT ON TABLE ops.adre_inv_item_type IS
'Configuration table containing the Item Types available in the Adhesives Research Inventory Item Creation application.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add column documentation.
-- =====================================================================

COMMENT ON COLUMN ops.adre_inv_item_type.item_type_id IS
'Surrogate primary key generated by Oracle for each Item Type.';

COMMENT ON COLUMN ops.adre_inv_item_type.item_type_code IS
'Unique application code used internally to identify the Item Type.';

COMMENT ON COLUMN ops.adre_inv_item_type.item_type_name IS
'User-facing Item Type name displayed in Oracle APEX.';

COMMENT ON COLUMN ops.adre_inv_item_type.description IS
'Functional description of the Item Type.';

COMMENT ON COLUMN ops.adre_inv_item_type.active_flag IS
'Indicates whether the Item Type is available for use. Valid values are Y and N.';

COMMENT ON COLUMN ops.adre_inv_item_type.display_sequence IS
'Controls the display order of Item Types in Oracle APEX.';

COMMENT ON COLUMN ops.adre_inv_item_type.created_by IS
'Application or database user that created the row.';

COMMENT ON COLUMN ops.adre_inv_item_type.creation_date IS
'Date and time when the row was created.';

COMMENT ON COLUMN ops.adre_inv_item_type.last_updated_by IS
'Application or database user that last updated the row.';

COMMENT ON COLUMN ops.adre_inv_item_type.last_update_date IS
'Date and time when the row was last updated.';

COMMENT ON COLUMN ops.adre_inv_item_type.last_update_login IS
'Oracle APEX session identifier or database login associated with the last update.';

COMMENT ON COLUMN ops.adre_inv_item_type.record_version_number IS
'Row version number used for change tracking and optimistic locking.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Automatically maintain audit information for ADRE_INV_ITEM_TYPE.
--
-- The trigger also normalizes ITEM_TYPE_CODE so the application stores
-- Item Type codes consistently in uppercase without leading or trailing
-- spaces.
--
-- ITEM_TYPE_NAME is trimmed before being stored.
-- =====================================================================

CREATE OR REPLACE TRIGGER ops.adre_inv_item_type_biu
BEFORE INSERT OR UPDATE
ON ops.adre_inv_item_type
FOR EACH ROW

DECLARE

    l_user
        VARCHAR2(100);

    l_login
        VARCHAR2(100);

BEGIN

    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX user when the DML originates from APEX.
    --
    -- When the operation is executed outside Oracle APEX, use the
    -- current Oracle database user.
    -- =================================================================

    l_user :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_USER'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX session identifier when available.
    --
    -- When no APEX session exists, use the current Oracle database
    -- user as the fallback value.
    -- =================================================================

    l_login :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_SESSION'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the Item Type code before storing the row.
    --
    -- Example:
    -- adhesive_coating
    --
    -- becomes:
    -- ADHESIVE_COATING
    -- =================================================================

    :NEW.item_type_code :=
        UPPER
        (
            TRIM
            (
                :NEW.item_type_code
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Remove unnecessary leading and trailing spaces from the Item Type
    -- display name.
    -- =================================================================

    :NEW.item_type_name :=
        TRIM
        (
            :NEW.item_type_name
        );


    IF INSERTING THEN

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize creation audit information for a new row.
        -- =============================================================

        :NEW.created_by :=
            NVL
            (
                :NEW.created_by,
                l_user
            );


        :NEW.creation_date :=
            NVL
            (
                :NEW.creation_date,
                SYSDATE
            );


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize the first row version.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :NEW.record_version_number,
                1
            );

    ELSE

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Preserve the original creation audit information when an
        -- existing Item Type is updated.
        -- =============================================================

        :NEW.created_by :=
            :OLD.created_by;

        :NEW.creation_date :=
            :OLD.creation_date;


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Increment the row version number after each update.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :OLD.record_version_number,
                0
            ) + 1;

    END IF;


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Refresh the last-update audit information for both inserts and
    -- updates.
    -- =================================================================

    :NEW.last_updated_by :=
        l_user;

    :NEW.last_update_date :=
        SYSDATE;

    :NEW.last_update_login :=
        l_login;

END;
/

-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the table was created successfully.
-- =====================================================================

SELECT
    owner,
    object_name AS table_name,
    status
  FROM all_objects
  WHERE owner = 'OPS'
  AND object_name = 'ADRE_INV_ITEM_TYPE'
  AND object_type = 'TABLE';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the audit trigger was compiled and enabled.
-- =====================================================================

SELECT
    owner,
    trigger_name,
    table_name,
    status
FROM all_triggers
WHERE owner = 'OPS'
  AND trigger_name = 'ADRE_INV_ITEM_TYPE_BIU';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the table comment.
-- =====================================================================

SELECT
    table_name,
    comments
FROM all_tab_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_TYPE';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate all column comments.
-- =====================================================================

SELECT
    column_name,
    comments
FROM all_col_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_TYPE'
ORDER BY column_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================