-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Recreate the Oracle EBS Category Set configuration table for the
-- final Adhesives Research Inventory Item Creation application.
--
-- This table defines the Oracle EBS Category Sets that are available
-- to the application.
--
-- CONTROL_LEVEL determines where the category is controlled:
--
--   1 = Item / Master Organization controlled
--   2 = Organization controlled
--
-- REQUIRED_FLAG determines whether a category value must be populated
-- before the Item Request can be sent to Oracle EBS.
--
-- The application uses this configuration instead of hardcoding
-- Category Set identifiers or names in Oracle APEX or PL/SQL.
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Drop the existing table when it already exists.
--
-- CASCADE CONSTRAINTS removes foreign key references from previously
-- created dependent application objects during the schema rebuild.
--
-- ORA-00942 is ignored because it means the table does not exist.
-- Any other Oracle error is raised normally.
-- =====================================================================

BEGIN
    EXECUTE IMMEDIATE
        'DROP TABLE ops.adre_inv_item_cat_set CASCADE CONSTRAINTS PURGE';

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Create the Oracle EBS Category Set configuration table.
-- =====================================================================

CREATE TABLE ops.adre_inv_item_cat_set
(
    item_cat_set_id
        NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        NOT NULL,

    ebs_category_set_id
        NUMBER
        NOT NULL,

    category_set_name
        VARCHAR2(240)
        NOT NULL,

    control_level
        NUMBER
        NOT NULL,

    required_flag
        VARCHAR2(1)
        DEFAULT 'N'
        NOT NULL,

    active_flag
        VARCHAR2(1)
        DEFAULT 'Y'
        NOT NULL,

    display_sequence
        NUMBER
        DEFAULT 10
        NOT NULL,

    created_by
        VARCHAR2(100)
        NOT NULL,

    creation_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_updated_by
        VARCHAR2(100)
        NOT NULL,

    last_update_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_update_login
        VARCHAR2(100),

    record_version_number
        NUMBER
        DEFAULT 1
        NOT NULL,

    CONSTRAINT adre_inv_item_cat_set_pk
        PRIMARY KEY
        (
            item_cat_set_id
        ),

    CONSTRAINT adre_inv_item_cat_set_u1
        UNIQUE
        (
            ebs_category_set_id
        ),

    CONSTRAINT adre_inv_item_cat_set_u2
        UNIQUE
        (
            category_set_name
        ),

    CONSTRAINT adre_inv_item_cat_set_ck1
        CHECK
        (
            control_level IN
            (
                1,
                2
            )
        ),

    CONSTRAINT adre_inv_item_cat_set_ck2
        CHECK
        (
            required_flag IN
            (
                'Y',
                'N'
            )
        ),

    CONSTRAINT adre_inv_item_cat_set_ck3
        CHECK
        (
            active_flag IN
            (
                'Y',
                'N'
            )
        ),

    CONSTRAINT adre_inv_item_cat_set_ck4
        CHECK
        (
            ebs_category_set_id > 0
        ),

    CONSTRAINT adre_inv_item_cat_set_ck5
        CHECK
        (
            display_sequence > 0
        ),

    CONSTRAINT adre_inv_item_cat_set_ck6
        CHECK
        (
            record_version_number > 0
        )
);


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support retrieval of active Category Sets by control level and
-- display sequence.
--
-- This index will be used when Oracle APEX determines which Category
-- Sets belong to the Master Organization or Target Organizations.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_cat_set_n1
    ON ops.adre_inv_item_cat_set
    (
        control_level,
        active_flag,
        display_sequence
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support general Oracle APEX LOV and configuration queries that return
-- active Category Sets by name.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_cat_set_n2
    ON ops.adre_inv_item_cat_set
    (
        active_flag,
        category_set_name
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add table documentation.
-- =====================================================================

COMMENT ON TABLE ops.adre_inv_item_cat_set IS
'Configuration table containing Oracle EBS Category Sets used by the Adhesives Research Inventory Item Creation application.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add column documentation.
-- =====================================================================

COMMENT ON COLUMN ops.adre_inv_item_cat_set.item_cat_set_id IS
'Surrogate primary key generated by Oracle for the application Category Set configuration.';

COMMENT ON COLUMN ops.adre_inv_item_cat_set.ebs_category_set_id IS
'Oracle EBS Category Set identifier.';

COMMENT ON COLUMN ops.adre_inv_item_cat_set.category_set_name IS
'Oracle EBS Category Set name displayed and used by the application.';

COMMENT ON COLUMN ops.adre_inv_item_cat_set.control_level IS
'Oracle EBS Category Set control level. Value 1 represents Item or Master Organization control and value 2 represents Organization control.';

COMMENT ON COLUMN ops.adre_inv_item_cat_set.required_flag IS
'Indicates whether a category value is required before Send to EBS. Valid values are Y and N.';

COMMENT ON COLUMN ops.adre_inv_item_cat_set.active_flag IS
'Indicates whether the Category Set is available for use in the application. Valid values are Y and N.';

COMMENT ON COLUMN ops.adre_inv_item_cat_set.display_sequence IS
'Controls the display order of Category Sets in Oracle APEX.';

COMMENT ON COLUMN ops.adre_inv_item_cat_set.created_by IS
'Application or database user that created the row.';

COMMENT ON COLUMN ops.adre_inv_item_cat_set.creation_date IS
'Date and time when the row was created.';

COMMENT ON COLUMN ops.adre_inv_item_cat_set.last_updated_by IS
'Application or database user that last updated the row.';

COMMENT ON COLUMN ops.adre_inv_item_cat_set.last_update_date IS
'Date and time when the row was last updated.';

COMMENT ON COLUMN ops.adre_inv_item_cat_set.last_update_login IS
'Oracle APEX session identifier or database login associated with the last update.';

COMMENT ON COLUMN ops.adre_inv_item_cat_set.record_version_number IS
'Row version number used for change tracking and optimistic locking.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Automatically maintain audit information and normalize Category Set
-- configuration values for ADRE_INV_ITEM_CAT_SET.
-- =====================================================================

CREATE OR REPLACE TRIGGER ops.adre_inv_item_cat_set_biu
BEFORE INSERT OR UPDATE
ON ops.adre_inv_item_cat_set
FOR EACH ROW

DECLARE

    l_user
        VARCHAR2(100);

    l_login
        VARCHAR2(100);

BEGIN

    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX user when available.
    --
    -- Use the current Oracle database user when the operation is
    -- executed outside Oracle APEX.
    -- =================================================================

    l_user :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_USER'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX session identifier when available.
    -- =================================================================

    l_login :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_SESSION'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Preserve the Oracle EBS Category Set name capitalization while
    -- removing unnecessary leading and trailing spaces.
    -- =================================================================

    :NEW.category_set_name :=
        TRIM
        (
            :NEW.category_set_name
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the required indicator.
    -- =================================================================

    :NEW.required_flag :=
        UPPER
        (
            TRIM
            (
                :NEW.required_flag
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the active indicator.
    -- =================================================================

    :NEW.active_flag :=
        UPPER
        (
            TRIM
            (
                :NEW.active_flag
            )
        );


    IF INSERTING THEN

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize creation audit information for a new Category Set.
        -- =============================================================

        :NEW.created_by :=
            NVL
            (
                :NEW.created_by,
                l_user
            );


        :NEW.creation_date :=
            NVL
            (
                :NEW.creation_date,
                SYSDATE
            );


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize the first row version.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :NEW.record_version_number,
                1
            );

    ELSE

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Preserve the original creation audit information.
        -- =============================================================

        :NEW.created_by :=
            :OLD.created_by;

        :NEW.creation_date :=
            :OLD.creation_date;


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Increment the row version number on every update.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :OLD.record_version_number,
                0
            ) + 1;

    END IF;


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Refresh last-update audit information for inserts and updates.
    -- =================================================================

    :NEW.last_updated_by :=
        l_user;

    :NEW.last_update_date :=
        SYSDATE;

    :NEW.last_update_login :=
        l_login;

END;
/

-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the table exists and is VALID.
--
-- ALL_OBJECTS uses OBJECT_NAME for the object identifier.
-- =====================================================================

SELECT
    owner,
    object_name AS table_name,
    status
FROM all_objects
WHERE owner = 'OPS'
  AND object_name = 'ADRE_INV_ITEM_CAT_SET'
  AND object_type = 'TABLE';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the audit trigger exists and is enabled.
-- =====================================================================

SELECT
    owner,
    trigger_name,
    table_name,
    status
FROM all_triggers
WHERE owner = 'OPS'
  AND trigger_name = 'ADRE_INV_ITEM_CAT_SET_BIU';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Check for trigger compilation errors.
--
-- A successful trigger compilation must return zero rows.
-- =====================================================================

SELECT
    line,
    position,
    text
FROM all_errors
WHERE owner = 'OPS'
  AND name = 'ADRE_INV_ITEM_CAT_SET_BIU'
  AND type = 'TRIGGER'
ORDER BY sequence;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the table comment.
-- =====================================================================

SELECT
    table_name,
    comments
FROM all_tab_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_CAT_SET';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate all column comments.
-- =====================================================================

SELECT
    column_name,
    comments
FROM all_col_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_CAT_SET'
ORDER BY column_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================