-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Recreate the Item Template Rule configuration table for the final
-- Adhesives Research Inventory Item Creation application.
--
-- Oracle EBS is the system of record for:
--
--   - Inventory Organizations
--   - Item Templates
--
-- The application does not maintain local copies of those entities.
--
-- EBS_ORGANIZATION_ID references the Oracle EBS Inventory Organization
-- identifier directly.
--
-- EBS_TEMPLATE_ID references an existing Oracle EBS Item Template
-- identifier directly.
--
-- No foreign key is created from these columns to APPS objects in order
-- to avoid coupling the application schema to Oracle EBS base tables.
--
-- Supported RULE_STATUS values:
--
--   READY
--   UNSUPPORTED
--   NEEDS_BUSINESS_DECISION
--   INVALID_COMBINATION
--   UNDER_INVESTIGATION
--
-- UNSUPPORTED replaces the previous NEEDS_NEW_TEMPLATE status because
-- creation of new Oracle EBS Item Templates is outside the scope of
-- this application.
--
-- A READY rule must always contain an EBS_TEMPLATE_ID.
--
-- NULL values in optional rule criteria represent wildcard or
-- not-applicable conditions.
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Drop the existing table when it already exists.
--
-- ORA-00942 is ignored because it means the table does not exist.
-- Any other Oracle error is raised normally.
-- =====================================================================

BEGIN
    EXECUTE IMMEDIATE
        'DROP TABLE ops.adre_inv_item_template_rule CASCADE CONSTRAINTS PURGE';

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Create the final Item Template Rule configuration table.
-- =====================================================================

CREATE TABLE ops.adre_inv_item_template_rule
(
    item_template_rule_id
        NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        NOT NULL,

    item_type_id
        NUMBER
        NOT NULL,

    ebs_organization_id
        NUMBER,

    division_value
        VARCHAR2(240),

    business_unit_value
        VARCHAR2(240),

    expense_item_flag
        VARCHAR2(1),

    ebs_template_id
        NUMBER,

    rule_status
        VARCHAR2(30)
        DEFAULT 'READY'
        NOT NULL,

    rule_notes
        VARCHAR2(2000),

    rule_priority
        NUMBER
        DEFAULT 100
        NOT NULL,

    active_flag
        VARCHAR2(1)
        DEFAULT 'Y'
        NOT NULL,

    effective_start_date
        DATE,

    effective_end_date
        DATE,

    created_by
        VARCHAR2(100)
        NOT NULL,

    creation_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_updated_by
        VARCHAR2(100)
        NOT NULL,

    last_update_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_update_login
        VARCHAR2(100),

    record_version_number
        NUMBER
        DEFAULT 1
        NOT NULL,


    CONSTRAINT adre_inv_item_template_rule_pk
        PRIMARY KEY
        (
            item_template_rule_id
        ),


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- ITEM_TYPE remains application-owned configuration and therefore
    -- retains its local foreign key.
    -- =================================================================

    CONSTRAINT adre_inv_item_template_rule_fk1
        FOREIGN KEY
        (
            item_type_id
        )
        REFERENCES ops.adre_inv_item_type
        (
            item_type_id
        ),


    CONSTRAINT adre_inv_item_template_rule_ck1
        CHECK
        (
            ebs_organization_id IS NULL
            OR ebs_organization_id > 0
        ),


    CONSTRAINT adre_inv_item_template_rule_ck2
        CHECK
        (
            expense_item_flag IS NULL
            OR expense_item_flag IN ('Y', 'N')
        ),


    CONSTRAINT adre_inv_item_template_rule_ck3
        CHECK
        (
            ebs_template_id IS NULL
            OR ebs_template_id > 0
        ),


    CONSTRAINT adre_inv_item_template_rule_ck4
        CHECK
        (
            rule_status IN
            (
                'READY',
                'UNSUPPORTED',
                'NEEDS_BUSINESS_DECISION',
                'INVALID_COMBINATION',
                'UNDER_INVESTIGATION'
            )
        ),


    CONSTRAINT adre_inv_item_template_rule_ck5
        CHECK
        (
            rule_status <> 'READY'
            OR ebs_template_id IS NOT NULL
        ),


    CONSTRAINT adre_inv_item_template_rule_ck6
        CHECK
        (
            rule_priority > 0
        ),


    CONSTRAINT adre_inv_item_template_rule_ck7
        CHECK
        (
            active_flag IN ('Y', 'N')
        ),


    CONSTRAINT adre_inv_item_template_rule_ck8
        CHECK
        (
            effective_end_date IS NULL
            OR effective_start_date IS NULL
            OR effective_end_date >= effective_start_date
        ),


    CONSTRAINT adre_inv_item_template_rule_ck9
        CHECK
        (
            record_version_number > 0
        )
);


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Prevent duplicate business rule definitions.
--
-- NULL values are normalized so wildcard criteria participate in the
-- uniqueness rule.
-- =====================================================================

CREATE UNIQUE INDEX ops.adre_inv_item_tmpl_rule_u1
    ON ops.adre_inv_item_template_rule
    (
        item_type_id,

        NVL
        (
            ebs_organization_id,
            -1
        ),

        NVL
        (
            UPPER
            (
                TRIM
                (
                    division_value
                )
            ),
            '~'
        ),

        NVL
        (
            UPPER
            (
                TRIM
                (
                    business_unit_value
                )
            ),
            '~'
        ),

        NVL
        (
            expense_item_flag,
            '~'
        )
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support rule resolution by Item Type and Oracle EBS Organization.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_tmpl_rule_n1
    ON ops.adre_inv_item_template_rule
    (
        item_type_id,
        ebs_organization_id,
        active_flag
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support rule evaluation by status and priority.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_tmpl_rule_n2
    ON ops.adre_inv_item_template_rule
    (
        active_flag,
        rule_status,
        rule_priority
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support retrieval of rules associated with an existing Oracle EBS
-- Item Template.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_tmpl_rule_n3
    ON ops.adre_inv_item_template_rule
    (
        ebs_template_id
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add table documentation.
-- =====================================================================

COMMENT ON TABLE ops.adre_inv_item_template_rule IS
'Application-owned business rules used to resolve an existing Oracle EBS Item Template based on Item Type, Oracle EBS Organization, Division, Business Unit and Expense Item criteria.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add column documentation.
-- =====================================================================

COMMENT ON COLUMN ops.adre_inv_item_template_rule.item_template_rule_id IS
'Surrogate primary key generated by Oracle for each Item Template resolution rule.';

COMMENT ON COLUMN ops.adre_inv_item_template_rule.item_type_id IS
'Foreign key identifying the application Item Type to which the rule applies.';

COMMENT ON COLUMN ops.adre_inv_item_template_rule.ebs_organization_id IS
'Oracle EBS Inventory Organization identifier used as an optional rule criterion. NULL means the rule is not restricted to one organization.';

COMMENT ON COLUMN ops.adre_inv_item_template_rule.division_value IS
'Optional Division criterion used to resolve the Oracle EBS Item Template. NULL means the criterion is not applicable.';

COMMENT ON COLUMN ops.adre_inv_item_template_rule.business_unit_value IS
'Optional Business Unit criterion used to resolve the Oracle EBS Item Template. NULL means the criterion is not applicable.';

COMMENT ON COLUMN ops.adre_inv_item_template_rule.expense_item_flag IS
'Optional Expense Item criterion. Valid values are Y, N or NULL when the criterion is not applicable.';

COMMENT ON COLUMN ops.adre_inv_item_template_rule.ebs_template_id IS
'Identifier of an existing Oracle EBS Item Template. READY rules must contain a valid Oracle EBS Template identifier.';

COMMENT ON COLUMN ops.adre_inv_item_template_rule.rule_status IS
'Business status of the rule. Valid values are READY, UNSUPPORTED, NEEDS_BUSINESS_DECISION, INVALID_COMBINATION and UNDER_INVESTIGATION.';

COMMENT ON COLUMN ops.adre_inv_item_template_rule.rule_notes IS
'Business or configuration notes associated with the Item Template resolution rule.';

COMMENT ON COLUMN ops.adre_inv_item_template_rule.rule_priority IS
'Rule evaluation priority. Lower numeric values are evaluated before higher values.';

COMMENT ON COLUMN ops.adre_inv_item_template_rule.active_flag IS
'Indicates whether the Item Template resolution rule is active. Valid values are Y and N.';

COMMENT ON COLUMN ops.adre_inv_item_template_rule.effective_start_date IS
'Optional date from which the Item Template resolution rule becomes effective.';

COMMENT ON COLUMN ops.adre_inv_item_template_rule.effective_end_date IS
'Optional date after which the Item Template resolution rule is no longer effective.';

COMMENT ON COLUMN ops.adre_inv_item_template_rule.created_by IS
'Application or database user that created the row.';

COMMENT ON COLUMN ops.adre_inv_item_template_rule.creation_date IS
'Date and time when the row was created.';

COMMENT ON COLUMN ops.adre_inv_item_template_rule.last_updated_by IS
'Application or database user that last updated the row.';

COMMENT ON COLUMN ops.adre_inv_item_template_rule.last_update_date IS
'Date and time when the row was last updated.';

COMMENT ON COLUMN ops.adre_inv_item_template_rule.last_update_login IS
'Oracle APEX session identifier or database login associated with the last update.';

COMMENT ON COLUMN ops.adre_inv_item_template_rule.record_version_number IS
'Row version number used for change tracking and optimistic locking.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Automatically maintain audit information and normalize Item Template
-- Rule configuration values.
-- =====================================================================

CREATE OR REPLACE TRIGGER ops.adre_inv_item_tmpl_rule_biu
BEFORE INSERT OR UPDATE
ON ops.adre_inv_item_template_rule
FOR EACH ROW

DECLARE

    l_user
        VARCHAR2(100);

    l_login
        VARCHAR2(100);

BEGIN

    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX user when available.

    l_user :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_USER'
            ),
            USER
        );


    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX session identifier when available.

    l_login :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_SESSION'
            ),
            USER
        );


    -- JCALZADILLA - 22.08.2026
    -- Normalize optional rule criteria.

    :NEW.division_value :=
        TRIM
        (
            :NEW.division_value
        );


    :NEW.business_unit_value :=
        TRIM
        (
            :NEW.business_unit_value
        );


    :NEW.expense_item_flag :=
        UPPER
        (
            TRIM
            (
                :NEW.expense_item_flag
            )
        );


    -- JCALZADILLA - 22.08.2026
    -- Normalize rule status and active indicator.

    :NEW.rule_status :=
        UPPER
        (
            TRIM
            (
                :NEW.rule_status
            )
        );


    :NEW.active_flag :=
        UPPER
        (
            TRIM
            (
                :NEW.active_flag
            )
        );


    -- JCALZADILLA - 22.08.2026
    -- Remove unnecessary surrounding spaces from rule notes.

    :NEW.rule_notes :=
        TRIM
        (
            :NEW.rule_notes
        );


    IF INSERTING THEN

        -- JCALZADILLA - 22.08.2026
        -- Initialize creation audit information.

        :NEW.created_by :=
            NVL
            (
                :NEW.created_by,
                l_user
            );


        :NEW.creation_date :=
            NVL
            (
                :NEW.creation_date,
                SYSDATE
            );


        :NEW.record_version_number :=
            NVL
            (
                :NEW.record_version_number,
                1
            );

    ELSE

        -- JCALZADILLA - 22.08.2026
        -- Preserve original creation audit information.

        :NEW.created_by :=
            :OLD.created_by;

        :NEW.creation_date :=
            :OLD.creation_date;


        -- JCALZADILLA - 22.08.2026
        -- Increment the row version number.

        :NEW.record_version_number :=
            NVL
            (
                :OLD.record_version_number,
                0
            ) + 1;

    END IF;


    -- JCALZADILLA - 22.08.2026
    -- Refresh last-update audit information.

    :NEW.last_updated_by :=
        l_user;

    :NEW.last_update_date :=
        SYSDATE;

    :NEW.last_update_login :=
        l_login;

END;
/

-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the recreated table exists.
--
-- Expected result:
-- 1 row / STATUS = VALID
-- =====================================================================

SELECT
    owner,
    object_name AS table_name,
    status
FROM all_objects
WHERE owner = 'OPS'
  AND object_name = 'ADRE_INV_ITEM_TEMPLATE_RULE'
  AND object_type = 'TABLE';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the new direct Oracle EBS reference columns.
--
-- Expected:
--
-- EBS_ORGANIZATION_ID = Y
-- EBS_TEMPLATE_ID     = Y
-- =====================================================================

SELECT
    column_name,
    data_type,
    nullable
FROM all_tab_columns
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_TEMPLATE_RULE'
  AND column_name IN
      (
          'EBS_ORGANIZATION_ID',
          'EBS_TEMPLATE_ID'
      )
ORDER BY column_id;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Confirm that obsolete local-reference columns no longer exist.
--
-- Expected result:
-- 0 rows
-- =====================================================================

SELECT
    column_name
FROM all_tab_columns
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_TEMPLATE_RULE'
  AND column_name IN
      (
          'ITEM_ORG_ID',
          'ITEM_TEMPLATE_ID'
      );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate foreign keys.
--
-- Expected result:
-- One foreign key only:
--
-- ADRE_INV_ITEM_TEMPLATE_RULE_FK1 -> ADRE_INV_ITEM_TYPE
--
-- There must be no foreign key to an Oracle EBS base table.
-- =====================================================================

SELECT
    c.constraint_name,
    cc.column_name,
    r.table_name AS referenced_table
FROM all_constraints c
JOIN all_cons_columns cc
  ON cc.owner = c.owner
 AND cc.constraint_name = c.constraint_name
JOIN all_constraints r
  ON r.owner = c.r_owner
 AND r.constraint_name = c.r_constraint_name
WHERE c.owner = 'OPS'
  AND c.table_name = 'ADRE_INV_ITEM_TEMPLATE_RULE'
  AND c.constraint_type = 'R'
ORDER BY
    c.constraint_name,
    cc.position;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the audit trigger exists and is enabled.
--
-- Expected result:
-- STATUS = ENABLED
-- =====================================================================

SELECT
    owner,
    trigger_name,
    table_name,
    status
FROM all_triggers
WHERE owner = 'OPS'
  AND trigger_name = 'ADRE_INV_ITEM_TMPL_RULE_BIU';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Check for trigger compilation errors.
--
-- Expected result:
-- 0 rows
-- =====================================================================

SELECT
    line,
    position,
    text
FROM all_errors
WHERE owner = 'OPS'
  AND name = 'ADRE_INV_ITEM_TMPL_RULE_BIU'
  AND type = 'TRIGGER'
ORDER BY sequence;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the table has documentation.
--
-- Expected result:
-- 1 row with a non-null COMMENTS value.
-- =====================================================================

SELECT
    table_name,
    comments
FROM all_tab_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_TEMPLATE_RULE';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that every column has documentation.
--
-- Expected result:
-- MISSING_COLUMN_COMMENTS = 0
-- =====================================================================

SELECT
    COUNT(*) AS missing_column_comments
FROM all_tab_columns c
LEFT JOIN all_col_comments cc
  ON cc.owner = c.owner
 AND cc.table_name = c.table_name
 AND cc.column_name = c.column_name
WHERE c.owner = 'OPS'
  AND c.table_name = 'ADRE_INV_ITEM_TEMPLATE_RULE'
  AND cc.comments IS NULL;


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================