-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Recreate the Oracle EBS Item Template configuration table for the
-- final Adhesives Research Inventory Item Creation application.
--
-- This table defines the Oracle EBS Item Templates available to the
-- application.
--
-- ITEM_TEMPLATE_ID is the internal application identifier.
--
-- EBS_TEMPLATE_ID stores the corresponding Oracle EBS template
-- identifier when it is available.
--
-- Application relationships will use ITEM_TEMPLATE_ID instead of
-- directly using the Oracle EBS template identifier.
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Drop the existing table when it already exists.
--
-- CASCADE CONSTRAINTS removes foreign key references from previously
-- created dependent application objects during the schema rebuild.
--
-- ORA-00942 is ignored because it means the table does not exist.
-- Any other Oracle error is raised normally.
-- =====================================================================

BEGIN
    EXECUTE IMMEDIATE
        'DROP TABLE ops.adre_inv_item_template CASCADE CONSTRAINTS PURGE';

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Create the Oracle EBS Item Template configuration table.
-- =====================================================================

CREATE TABLE ops.adre_inv_item_template
(
    item_template_id
        NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        NOT NULL,

    ebs_template_id
        NUMBER,

    template_name
        VARCHAR2(240)
        NOT NULL,

    description
        VARCHAR2(1000),

    active_flag
        VARCHAR2(1)
        DEFAULT 'Y'
        NOT NULL,

    display_sequence
        NUMBER
        DEFAULT 10
        NOT NULL,

    created_by
        VARCHAR2(100)
        NOT NULL,

    creation_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_updated_by
        VARCHAR2(100)
        NOT NULL,

    last_update_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_update_login
        VARCHAR2(100),

    record_version_number
        NUMBER
        DEFAULT 1
        NOT NULL,

    CONSTRAINT adre_inv_item_template_pk
        PRIMARY KEY
        (
            item_template_id
        ),

    CONSTRAINT adre_inv_item_template_u1
        UNIQUE
        (
            template_name
        ),

    CONSTRAINT adre_inv_item_template_u2
        UNIQUE
        (
            ebs_template_id
        ),

    CONSTRAINT adre_inv_item_template_ck1
        CHECK
        (
            active_flag IN
            (
                'Y',
                'N'
            )
        ),

    CONSTRAINT adre_inv_item_template_ck2
        CHECK
        (
            ebs_template_id IS NULL
            OR ebs_template_id > 0
        ),

    CONSTRAINT adre_inv_item_template_ck3
        CHECK
        (
            display_sequence > 0
        ),

    CONSTRAINT adre_inv_item_template_ck4
        CHECK
        (
            record_version_number > 0
        )
);


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support Oracle APEX LOVs and administration screens that return
-- active Item Templates in display sequence.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_template_n1
    ON ops.adre_inv_item_template
    (
        active_flag,
        display_sequence
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add table documentation.
-- =====================================================================

COMMENT ON TABLE ops.adre_inv_item_template IS
'Configuration table containing Oracle EBS Item Templates available to the Adhesives Research Inventory Item Creation application.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add column documentation.
-- =====================================================================

COMMENT ON COLUMN ops.adre_inv_item_template.item_template_id IS
'Surrogate primary key generated by Oracle for the application Item Template configuration.';

COMMENT ON COLUMN ops.adre_inv_item_template.ebs_template_id IS
'Oracle EBS Item Template identifier when available.';

COMMENT ON COLUMN ops.adre_inv_item_template.template_name IS
'Oracle EBS Item Template name used by the application for template selection and display.';

COMMENT ON COLUMN ops.adre_inv_item_template.description IS
'Functional description of the Oracle EBS Item Template.';

COMMENT ON COLUMN ops.adre_inv_item_template.active_flag IS
'Indicates whether the Item Template is available for use in the application. Valid values are Y and N.';

COMMENT ON COLUMN ops.adre_inv_item_template.display_sequence IS
'Controls the display order of Item Templates in Oracle APEX.';

COMMENT ON COLUMN ops.adre_inv_item_template.created_by IS
'Application or database user that created the row.';

COMMENT ON COLUMN ops.adre_inv_item_template.creation_date IS
'Date and time when the row was created.';

COMMENT ON COLUMN ops.adre_inv_item_template.last_updated_by IS
'Application or database user that last updated the row.';

COMMENT ON COLUMN ops.adre_inv_item_template.last_update_date IS
'Date and time when the row was last updated.';

COMMENT ON COLUMN ops.adre_inv_item_template.last_update_login IS
'Oracle APEX session identifier or database login associated with the last update.';

COMMENT ON COLUMN ops.adre_inv_item_template.record_version_number IS
'Row version number used for change tracking and optimistic locking.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Automatically maintain audit information and normalize configuration
-- values for ADRE_INV_ITEM_TEMPLATE.
-- =====================================================================

CREATE OR REPLACE TRIGGER ops.adre_inv_item_template_biu
BEFORE INSERT OR UPDATE
ON ops.adre_inv_item_template
FOR EACH ROW

DECLARE

    l_user
        VARCHAR2(100);

    l_login
        VARCHAR2(100);

BEGIN

    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX user when available.
    --
    -- Use the current Oracle database user when the operation is
    -- executed outside Oracle APEX.
    -- =================================================================

    l_user :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_USER'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX session identifier when available.
    --
    -- Use the current Oracle database user as the fallback value.
    -- =================================================================

    l_login :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_SESSION'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Preserve the original Oracle EBS Item Template name capitalization
    -- while removing unnecessary leading and trailing spaces.
    -- =================================================================

    :NEW.template_name :=
        TRIM
        (
            :NEW.template_name
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the active indicator.
    -- =================================================================

    :NEW.active_flag :=
        UPPER
        (
            TRIM
            (
                :NEW.active_flag
            )
        );


    IF INSERTING THEN

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize creation audit information for a new Item Template.
        -- =============================================================

        :NEW.created_by :=
            NVL
            (
                :NEW.created_by,
                l_user
            );


        :NEW.creation_date :=
            NVL
            (
                :NEW.creation_date,
                SYSDATE
            );


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize the first row version.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :NEW.record_version_number,
                1
            );

    ELSE

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Preserve the original creation audit information.
        -- =============================================================

        :NEW.created_by :=
            :OLD.created_by;

        :NEW.creation_date :=
            :OLD.creation_date;


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Increment the row version number on every update.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :OLD.record_version_number,
                0
            ) + 1;

    END IF;


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Refresh last-update audit information for inserts and updates.
    -- =================================================================

    :NEW.last_updated_by :=
        l_user;

    :NEW.last_update_date :=
        SYSDATE;

    :NEW.last_update_login :=
        l_login;

END;
/

-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the table exists and is VALID.
--
-- ALL_OBJECTS uses OBJECT_NAME for the object identifier.
-- =====================================================================

SELECT
    owner,
    object_name AS table_name,
    status
FROM all_objects
WHERE owner = 'OPS'
  AND object_name = 'ADRE_INV_ITEM_TEMPLATE'
  AND object_type = 'TABLE';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the audit trigger exists and is enabled.
-- =====================================================================

SELECT
    owner,
    trigger_name,
    table_name,
    status
FROM all_triggers
WHERE owner = 'OPS'
  AND trigger_name = 'ADRE_INV_ITEM_TEMPLATE_BIU';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Check for trigger compilation errors.
--
-- A successful trigger compilation must return zero rows.
-- =====================================================================

SELECT
    line,
    position,
    text
FROM all_errors
WHERE owner = 'OPS'
  AND name = 'ADRE_INV_ITEM_TEMPLATE_BIU'
  AND type = 'TRIGGER'
ORDER BY sequence;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the table comment.
-- =====================================================================

SELECT
    table_name,
    comments
FROM all_tab_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_TEMPLATE';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate all column comments.
-- =====================================================================

SELECT
    column_name,
    comments
FROM all_col_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_TEMPLATE'
ORDER BY column_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================