/* ============================================================
   XINV ITEM CREATION - DDL SCRIPT
   Purpose:
   - Create the item type configuration table.
   - Create one staging table for item creation requests captured in APEX.
   - Use identity columns with GENERATED BY DEFAULT ON NULL AS IDENTITY.
   - Add audit columns and audit triggers.
   - Add comments for tables and columns.

   Important:
   - This script does not call EGO_ITEM_PUB directly.
   - A future APPS wrapper package should read from XINV_ITEM_CREATION_STG
     and call EGO_ITEM_PUB.PROCESS_ITEM or EGO_ITEM_PUB.PROCESS_ITEMS.
   ============================================================ */

SET DEFINE OFF

PROMPT ============================================================
PROMPT Dropping previous objects if they exist
PROMPT ============================================================

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE xinv_item_creation_stg CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE xinv_item_types CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

PROMPT ============================================================
PROMPT Creating table XINV_ITEM_TYPES
PROMPT ============================================================

CREATE TABLE xinv_item_types (
    item_type_id                     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                                      (START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE)
                                      NOT NULL,
    item_type_code                   VARCHAR2(50)         NOT NULL,
    item_type_name                   VARCHAR2(150)        NOT NULL,
    item_type_description            VARCHAR2(1000),

    default_template_name            VARCHAR2(150),
    default_primary_uom_code         VARCHAR2(30),
    default_item_status_code         VARCHAR2(30),
    default_part_status              VARCHAR2(50),

    default_master_org_code          VARCHAR2(30),
    default_target_org_code          VARCHAR2(30),

    default_division                 VARCHAR2(100),
    default_business_unit            VARCHAR2(100),
    default_inventory_class          VARCHAR2(150),
    default_outside_processing_flag  VARCHAR2(1)          DEFAULT 'N' NOT NULL,

    requires_bom_flag                VARCHAR2(1)          DEFAULT 'N' NOT NULL,
    requires_routing_flag            VARCHAR2(1)          DEFAULT 'N' NOT NULL,
    requires_shelf_life_flag         VARCHAR2(1)          DEFAULT 'N' NOT NULL,
    requires_lot_control_flag        VARCHAR2(1)          DEFAULT 'N' NOT NULL,
    requires_serial_control_flag     VARCHAR2(1)          DEFAULT 'N' NOT NULL,
    requires_revision_control_flag   VARCHAR2(1)          DEFAULT 'N' NOT NULL,
    requires_cost_rollup_flag        VARCHAR2(1)          DEFAULT 'N' NOT NULL,
    requires_engineering_review_flag VARCHAR2(1)          DEFAULT 'N' NOT NULL,

    default_inventory_item_flag      VARCHAR2(1)          DEFAULT 'Y' NOT NULL,
    default_stockable_flag           VARCHAR2(1)          DEFAULT 'Y' NOT NULL,
    default_transactable_flag        VARCHAR2(1)          DEFAULT 'Y' NOT NULL,
    default_purchasing_enabled_flag  VARCHAR2(1)          DEFAULT 'N' NOT NULL,
    default_customer_order_flag      VARCHAR2(1)          DEFAULT 'N' NOT NULL,
    default_bom_enabled_flag         VARCHAR2(1)          DEFAULT 'N' NOT NULL,
    default_build_in_wip_flag        VARCHAR2(1)          DEFAULT 'N' NOT NULL,
    default_costing_enabled_flag     VARCHAR2(1)          DEFAULT 'Y' NOT NULL,
    default_inventory_asset_flag     VARCHAR2(1)          DEFAULT 'Y' NOT NULL,

    active_flag                      VARCHAR2(1)          DEFAULT 'Y' NOT NULL,

    created_by                       VARCHAR2(100)        NOT NULL,
    creation_date                    DATE                 NOT NULL,
    last_updated_by                  VARCHAR2(100)        NOT NULL,
    last_update_date                 DATE                 NOT NULL,
    last_update_login                VARCHAR2(100),
    record_version_number            NUMBER               DEFAULT 1 NOT NULL,

    CONSTRAINT xinv_item_types_pk
        PRIMARY KEY (item_type_id),

    CONSTRAINT xinv_item_types_u1
        UNIQUE (item_type_code),

    CONSTRAINT xinv_item_types_active_ck
        CHECK (active_flag IN ('Y', 'N')),

    CONSTRAINT xinv_item_types_flags_ck
        CHECK (
            default_outside_processing_flag IN ('Y', 'N')
            AND requires_bom_flag IN ('Y', 'N')
            AND requires_routing_flag IN ('Y', 'N')
            AND requires_shelf_life_flag IN ('Y', 'N')
            AND requires_lot_control_flag IN ('Y', 'N')
            AND requires_serial_control_flag IN ('Y', 'N')
            AND requires_revision_control_flag IN ('Y', 'N')
            AND requires_cost_rollup_flag IN ('Y', 'N')
            AND requires_engineering_review_flag IN ('Y', 'N')
            AND default_inventory_item_flag IN ('Y', 'N')
            AND default_stockable_flag IN ('Y', 'N')
            AND default_transactable_flag IN ('Y', 'N')
            AND default_purchasing_enabled_flag IN ('Y', 'N')
            AND default_customer_order_flag IN ('Y', 'N')
            AND default_bom_enabled_flag IN ('Y', 'N')
            AND default_build_in_wip_flag IN ('Y', 'N')
            AND default_costing_enabled_flag IN ('Y', 'N')
            AND default_inventory_asset_flag IN ('Y', 'N')
        )
);
/

COMMENT ON TABLE xinv_item_types IS 'Defines item type configuration used by the APEX item creation process. This table controls defaults, required sections, templates, and business rules before calling EBS item APIs.';
COMMENT ON COLUMN xinv_item_types.item_type_id IS 'Primary key generated by default on null as identity.';
COMMENT ON COLUMN xinv_item_types.item_type_code IS 'Unique technical code for the item type.';
COMMENT ON COLUMN xinv_item_types.item_type_name IS 'User-friendly item type name displayed in APEX.';
COMMENT ON COLUMN xinv_item_types.item_type_description IS 'Functional description of the item type and expected business use.';
COMMENT ON COLUMN xinv_item_types.default_template_name IS 'Default EBS item template expected for this item type.';
COMMENT ON COLUMN xinv_item_types.default_primary_uom_code IS 'Default primary unit of measure code.';
COMMENT ON COLUMN xinv_item_types.default_item_status_code IS 'Default EBS item status code.';
COMMENT ON COLUMN xinv_item_types.default_part_status IS 'Default business part status shown in the APEX item request.';
COMMENT ON COLUMN xinv_item_types.default_master_org_code IS 'Default item master organization code where the item must be created first.';
COMMENT ON COLUMN xinv_item_types.default_target_org_code IS 'Default target or child inventory organization code.';
COMMENT ON COLUMN xinv_item_types.default_division IS 'Default business division.';
COMMENT ON COLUMN xinv_item_types.default_business_unit IS 'Default business unit.';
COMMENT ON COLUMN xinv_item_types.default_inventory_class IS 'Default inventory class used by the business process.';
COMMENT ON COLUMN xinv_item_types.default_outside_processing_flag IS 'Default outside processing indicator. Valid values are Y and N.';
COMMENT ON COLUMN xinv_item_types.requires_bom_flag IS 'Indicates whether this item type normally requires BOM information.';
COMMENT ON COLUMN xinv_item_types.requires_routing_flag IS 'Indicates whether this item type normally requires routing information.';
COMMENT ON COLUMN xinv_item_types.requires_shelf_life_flag IS 'Indicates whether shelf life fields are required.';
COMMENT ON COLUMN xinv_item_types.requires_lot_control_flag IS 'Indicates whether lot control is normally required.';
COMMENT ON COLUMN xinv_item_types.requires_serial_control_flag IS 'Indicates whether serial control is normally required.';
COMMENT ON COLUMN xinv_item_types.requires_revision_control_flag IS 'Indicates whether revision control is normally required.';
COMMENT ON COLUMN xinv_item_types.requires_cost_rollup_flag IS 'Indicates whether cost rollup is normally required.';
COMMENT ON COLUMN xinv_item_types.requires_engineering_review_flag IS 'Indicates whether engineering review is normally required.';
COMMENT ON COLUMN xinv_item_types.default_inventory_item_flag IS 'Default EBS inventory item flag.';
COMMENT ON COLUMN xinv_item_types.default_stockable_flag IS 'Default EBS stockable flag.';
COMMENT ON COLUMN xinv_item_types.default_transactable_flag IS 'Default EBS transactable flag.';
COMMENT ON COLUMN xinv_item_types.default_purchasing_enabled_flag IS 'Default EBS purchasing enabled flag.';
COMMENT ON COLUMN xinv_item_types.default_customer_order_flag IS 'Default EBS customer order flag.';
COMMENT ON COLUMN xinv_item_types.default_bom_enabled_flag IS 'Default EBS BOM enabled flag.';
COMMENT ON COLUMN xinv_item_types.default_build_in_wip_flag IS 'Default EBS build in WIP flag.';
COMMENT ON COLUMN xinv_item_types.default_costing_enabled_flag IS 'Default EBS costing enabled flag.';
COMMENT ON COLUMN xinv_item_types.default_inventory_asset_flag IS 'Default EBS inventory asset flag.';
COMMENT ON COLUMN xinv_item_types.active_flag IS 'Controls whether this item type is available in APEX.';
COMMENT ON COLUMN xinv_item_types.created_by IS 'User that created the record.';
COMMENT ON COLUMN xinv_item_types.creation_date IS 'Date and time when the record was created.';
COMMENT ON COLUMN xinv_item_types.last_updated_by IS 'User that last updated the record.';
COMMENT ON COLUMN xinv_item_types.last_update_date IS 'Date and time when the record was last updated.';
COMMENT ON COLUMN xinv_item_types.last_update_login IS 'APEX session or database login that last updated the record.';
COMMENT ON COLUMN xinv_item_types.record_version_number IS 'Optimistic locking column for APEX forms.';

PROMPT ============================================================
PROMPT Creating table XINV_ITEM_CREATION_STG
PROMPT ============================================================

CREATE TABLE xinv_item_creation_stg (
    item_creation_stg_id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                                      (START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE)
                                      NOT NULL,
    request_number                   VARCHAR2(50)        NOT NULL,
    request_status                   VARCHAR2(30)        DEFAULT 'DRAFT' NOT NULL,

    item_type_id                     NUMBER              NOT NULL,

    api_transaction_type             VARCHAR2(30)        DEFAULT 'CREATE' NOT NULL,
    validate_only_flag               VARCHAR2(1)         DEFAULT 'Y' NOT NULL,

    base_part_number                 VARCHAR2(100),
    item_number                      VARCHAR2(100)       NOT NULL,
    part_status                      VARCHAR2(50),
    item_description                 VARCHAR2(240)       NOT NULL,
    long_description                 VARCHAR2(4000),

    primary_uom_code                 VARCHAR2(30)        NOT NULL,
    item_status_code                 VARCHAR2(30),
    template_name                    VARCHAR2(150),

    master_org_code                  VARCHAR2(30)        NOT NULL,
    target_org_code                  VARCHAR2(30),

    outside_processing_flag          VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    planner_code                     VARCHAR2(50),
    division                         VARCHAR2(100),
    business_unit                    VARCHAR2(100),
    cost_rollup_requested_flag       VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    engineering_status               VARCHAR2(100),
    pdr_number                       VARCHAR2(100),
    tsr_number                       VARCHAR2(100),
    ucm_content_id                   VARCHAR2(200),
    inventory_class                  VARCHAR2(150),

    inventory_item_flag              VARCHAR2(1)         DEFAULT 'Y' NOT NULL,
    revision_control_flag            VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    stockable_flag                   VARCHAR2(1)         DEFAULT 'Y' NOT NULL,
    reservable_flag                  VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    transactable_flag                VARCHAR2(1)         DEFAULT 'Y' NOT NULL,
    check_material_shortage_flag     VARCHAR2(1)         DEFAULT 'Y' NOT NULL,
    cycle_count_enabled_flag         VARCHAR2(1)         DEFAULT 'Y' NOT NULL,

    purchasing_enabled_flag          VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    customer_order_flag              VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    shippable_flag                   VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    invoiceable_flag                 VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    bom_enabled_flag                 VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    build_in_wip_flag                VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    costing_enabled_flag             VARCHAR2(1)         DEFAULT 'Y' NOT NULL,
    inventory_asset_flag             VARCHAR2(1)         DEFAULT 'Y' NOT NULL,

    lot_expiration_control           VARCHAR2(50),
    shelf_life_days                  NUMBER,
    retest_interval_days             NUMBER,
    expiration_action_interval       NUMBER,
    expiration_action_code           VARCHAR2(50),

    lot_control_code                 VARCHAR2(50),
    lot_starting_prefix              VARCHAR2(50),
    lot_starting_number              VARCHAR2(50),
    lot_maturity_days                NUMBER,
    lot_hold_days                    NUMBER,

    serial_generation_control        VARCHAR2(50),
    serial_tagging_enabled_flag      VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    serial_starting_prefix           VARCHAR2(50),
    serial_starting_number           VARCHAR2(50),

    grade_controlled_flag            VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    default_grade                    VARCHAR2(50),

    locator_control_code             VARCHAR2(50),
    restrict_subinventories_flag     VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    restrict_locators_flag           VARCHAR2(1)         DEFAULT 'N' NOT NULL,

    material_classification_type     VARCHAR2(100),
    material_classification_control  VARCHAR2(100),

    category_set_name                VARCHAR2(150),
    category_name                    VARCHAR2(250),

    bom_step1_item1_number           VARCHAR2(100),
    bom_step1_item1_qty              NUMBER,
    bom_step1_item1_uom_code         VARCHAR2(30),
    bom_step1_item1_theoretical_qty  NUMBER,

    bom_step1_item2_number           VARCHAR2(100),
    bom_step1_item2_qty              NUMBER,
    bom_step1_item2_uom_code         VARCHAR2(30),
    bom_step1_item2_theoretical_qty  NUMBER,

    bom_step1_item3_number           VARCHAR2(100),
    bom_step1_item3_qty              NUMBER,
    bom_step1_item3_uom_code         VARCHAR2(30),
    bom_step1_item3_theoretical_qty  NUMBER,

    bom_step1_copy_from              VARCHAR2(100),

    bom_step2_item1_number           VARCHAR2(100),
    bom_step2_item1_qty              NUMBER,
    bom_step2_item1_uom_code         VARCHAR2(30),
    bom_step2_item1_theoretical_qty  NUMBER,

    bom_step2_item2_number           VARCHAR2(100),
    bom_step2_item2_qty              NUMBER,
    bom_step2_item2_uom_code         VARCHAR2(30),
    bom_step2_item2_theoretical_qty  NUMBER,

    bom_step2_item3_number           VARCHAR2(100),
    bom_step2_item3_qty              NUMBER,
    bom_step2_item3_uom_code         VARCHAR2(30),
    bom_step2_item3_theoretical_qty  NUMBER,

    bom_step2_copy_from              VARCHAR2(100),

    bom_step3_item1_number           VARCHAR2(100),
    bom_step3_item1_qty              NUMBER,
    bom_step3_item1_uom_code         VARCHAR2(30),
    bom_step3_item1_theoretical_qty  NUMBER,

    bom_step3_item2_number           VARCHAR2(100),
    bom_step3_item2_qty              NUMBER,
    bom_step3_item2_uom_code         VARCHAR2(30),
    bom_step3_item2_theoretical_qty  NUMBER,

    bom_step3_item3_number           VARCHAR2(100),
    bom_step3_item3_qty              NUMBER,
    bom_step3_item3_uom_code         VARCHAR2(30),
    bom_step3_item3_theoretical_qty  NUMBER,

    bom_step3_copy_from              VARCHAR2(100),

    oracle_inventory_item_id         NUMBER,
    oracle_organization_id           NUMBER,
    api_return_status                VARCHAR2(10),
    api_message_count                NUMBER,
    api_message_text                 CLOB,
    api_processed_date               DATE,

    created_by                       VARCHAR2(100)       NOT NULL,
    creation_date                    DATE                NOT NULL,
    last_updated_by                  VARCHAR2(100)       NOT NULL,
    last_update_date                 DATE                NOT NULL,
    last_update_login                VARCHAR2(100),
    record_version_number            NUMBER              DEFAULT 1 NOT NULL,

    CONSTRAINT xinv_item_creation_stg_pk
        PRIMARY KEY (item_creation_stg_id),

    CONSTRAINT xinv_item_creation_stg_u1
        UNIQUE (request_number),

    CONSTRAINT xinv_item_creation_stg_fk1
        FOREIGN KEY (item_type_id)
        REFERENCES xinv_item_types (item_type_id),

    CONSTRAINT xinv_item_creation_status_ck
        CHECK (request_status IN (
            'DRAFT',
            'VALIDATED',
            'SUBMITTED',
            'PROCESSED',
            'ERROR',
            'CANCELLED'
        )),

    CONSTRAINT xinv_item_creation_api_tx_ck
        CHECK (api_transaction_type IN ('CREATE', 'UPDATE')),

    CONSTRAINT xinv_item_creation_validate_ck
        CHECK (validate_only_flag IN ('Y', 'N')),

    CONSTRAINT xinv_item_creation_flags_ck
        CHECK (
            outside_processing_flag IN ('Y', 'N')
            AND cost_rollup_requested_flag IN ('Y', 'N')
            AND inventory_item_flag IN ('Y', 'N')
            AND revision_control_flag IN ('Y', 'N')
            AND stockable_flag IN ('Y', 'N')
            AND reservable_flag IN ('Y', 'N')
            AND transactable_flag IN ('Y', 'N')
            AND check_material_shortage_flag IN ('Y', 'N')
            AND cycle_count_enabled_flag IN ('Y', 'N')
            AND purchasing_enabled_flag IN ('Y', 'N')
            AND customer_order_flag IN ('Y', 'N')
            AND shippable_flag IN ('Y', 'N')
            AND invoiceable_flag IN ('Y', 'N')
            AND bom_enabled_flag IN ('Y', 'N')
            AND build_in_wip_flag IN ('Y', 'N')
            AND costing_enabled_flag IN ('Y', 'N')
            AND inventory_asset_flag IN ('Y', 'N')
            AND serial_tagging_enabled_flag IN ('Y', 'N')
            AND grade_controlled_flag IN ('Y', 'N')
            AND restrict_subinventories_flag IN ('Y', 'N')
            AND restrict_locators_flag IN ('Y', 'N')
        )
);
/

COMMENT ON TABLE xinv_item_creation_stg IS 'Main staging table for item creation requests captured in APEX before calling EBS item APIs. This table stores header, inventory attributes, organization defaults, BOM input fields, and API execution results.';
COMMENT ON COLUMN xinv_item_creation_stg.item_creation_stg_id IS 'Primary key generated by default on null as identity.';
COMMENT ON COLUMN xinv_item_creation_stg.request_number IS 'Business request number displayed to the user in APEX.';
COMMENT ON COLUMN xinv_item_creation_stg.request_status IS 'Workflow status of the item creation request.';
COMMENT ON COLUMN xinv_item_creation_stg.item_type_id IS 'Foreign key to XINV_ITEM_TYPES.';
COMMENT ON COLUMN xinv_item_creation_stg.api_transaction_type IS 'Transaction type expected by the EBS API. Usually CREATE for new items.';
COMMENT ON COLUMN xinv_item_creation_stg.validate_only_flag IS 'Y means validation only. N means the API may commit the item creation.';
COMMENT ON COLUMN xinv_item_creation_stg.base_part_number IS 'Base part number entered by the business user.';
COMMENT ON COLUMN xinv_item_creation_stg.item_number IS 'Final EBS item number to be created.';
COMMENT ON COLUMN xinv_item_creation_stg.part_status IS 'Business part status captured from the APEX request.';
COMMENT ON COLUMN xinv_item_creation_stg.item_description IS 'Short item description.';
COMMENT ON COLUMN xinv_item_creation_stg.long_description IS 'Long item description.';
COMMENT ON COLUMN xinv_item_creation_stg.primary_uom_code IS 'Primary unit of measure for the item.';
COMMENT ON COLUMN xinv_item_creation_stg.item_status_code IS 'EBS item status code.';
COMMENT ON COLUMN xinv_item_creation_stg.template_name IS 'EBS item template name selected or defaulted for this request.';
COMMENT ON COLUMN xinv_item_creation_stg.master_org_code IS 'EBS item master organization code where the item must be created first.';
COMMENT ON COLUMN xinv_item_creation_stg.target_org_code IS 'Target inventory organization code where the item may be assigned after master creation.';
COMMENT ON COLUMN xinv_item_creation_stg.outside_processing_flag IS 'Indicates whether outside processing applies.';
COMMENT ON COLUMN xinv_item_creation_stg.planner_code IS 'Planner code selected for the item, if applicable.';
COMMENT ON COLUMN xinv_item_creation_stg.division IS 'Business division.';
COMMENT ON COLUMN xinv_item_creation_stg.business_unit IS 'Business unit.';
COMMENT ON COLUMN xinv_item_creation_stg.cost_rollup_requested_flag IS 'Indicates whether cost rollup is requested by the business.';
COMMENT ON COLUMN xinv_item_creation_stg.engineering_status IS 'Engineering status or engineering reference value.';
COMMENT ON COLUMN xinv_item_creation_stg.pdr_number IS 'PDR number captured from the request.';
COMMENT ON COLUMN xinv_item_creation_stg.tsr_number IS 'TSR number captured from the request.';
COMMENT ON COLUMN xinv_item_creation_stg.ucm_content_id IS 'UCM content identifier for supporting documents.';
COMMENT ON COLUMN xinv_item_creation_stg.inventory_class IS 'Inventory class captured from the business request.';
COMMENT ON COLUMN xinv_item_creation_stg.inventory_item_flag IS 'Inventory item flag to be mapped into the EBS item API.';
COMMENT ON COLUMN xinv_item_creation_stg.revision_control_flag IS 'Revision control flag from the EBS inventory attributes.';
COMMENT ON COLUMN xinv_item_creation_stg.stockable_flag IS 'Stockable flag from the EBS inventory attributes.';
COMMENT ON COLUMN xinv_item_creation_stg.reservable_flag IS 'Reservable flag from the EBS inventory attributes.';
COMMENT ON COLUMN xinv_item_creation_stg.transactable_flag IS 'Transactable flag from the EBS inventory attributes.';
COMMENT ON COLUMN xinv_item_creation_stg.check_material_shortage_flag IS 'Check material shortage flag from the EBS inventory attributes.';
COMMENT ON COLUMN xinv_item_creation_stg.cycle_count_enabled_flag IS 'Cycle count enabled flag from the EBS inventory attributes.';
COMMENT ON COLUMN xinv_item_creation_stg.purchasing_enabled_flag IS 'Purchasing enabled flag to be mapped into the EBS item API.';
COMMENT ON COLUMN xinv_item_creation_stg.customer_order_flag IS 'Customer order flag to be mapped into the EBS item API.';
COMMENT ON COLUMN xinv_item_creation_stg.shippable_flag IS 'Shippable flag to be mapped into the EBS item API.';
COMMENT ON COLUMN xinv_item_creation_stg.invoiceable_flag IS 'Invoiceable flag to be mapped into the EBS item API.';
COMMENT ON COLUMN xinv_item_creation_stg.bom_enabled_flag IS 'BOM enabled flag to be mapped into the EBS item API.';
COMMENT ON COLUMN xinv_item_creation_stg.build_in_wip_flag IS 'Build in WIP flag to be mapped into the EBS item API.';
COMMENT ON COLUMN xinv_item_creation_stg.costing_enabled_flag IS 'Costing enabled flag to be mapped into the EBS item API.';
COMMENT ON COLUMN xinv_item_creation_stg.inventory_asset_flag IS 'Inventory asset flag to be mapped into the EBS item API.';
COMMENT ON COLUMN xinv_item_creation_stg.lot_expiration_control IS 'Business value for lot expiration control, such as Shelf life days.';
COMMENT ON COLUMN xinv_item_creation_stg.shelf_life_days IS 'Shelf life days when lot expiration control requires it.';
COMMENT ON COLUMN xinv_item_creation_stg.retest_interval_days IS 'Retest interval days for lot expiration setup.';
COMMENT ON COLUMN xinv_item_creation_stg.expiration_action_interval IS 'Expiration action interval for lot expiration setup.';
COMMENT ON COLUMN xinv_item_creation_stg.expiration_action_code IS 'Expiration action code for lot expiration setup.';
COMMENT ON COLUMN xinv_item_creation_stg.lot_control_code IS 'Business value for lot control, such as Full Control or No Control.';
COMMENT ON COLUMN xinv_item_creation_stg.lot_starting_prefix IS 'Lot starting prefix.';
COMMENT ON COLUMN xinv_item_creation_stg.lot_starting_number IS 'Lot starting number.';
COMMENT ON COLUMN xinv_item_creation_stg.lot_maturity_days IS 'Lot maturity days.';
COMMENT ON COLUMN xinv_item_creation_stg.lot_hold_days IS 'Lot hold days.';
COMMENT ON COLUMN xinv_item_creation_stg.serial_generation_control IS 'Business value for serial generation control.';
COMMENT ON COLUMN xinv_item_creation_stg.serial_tagging_enabled_flag IS 'Serial tagging enabled flag.';
COMMENT ON COLUMN xinv_item_creation_stg.serial_starting_prefix IS 'Serial starting prefix.';
COMMENT ON COLUMN xinv_item_creation_stg.serial_starting_number IS 'Serial starting number.';
COMMENT ON COLUMN xinv_item_creation_stg.grade_controlled_flag IS 'Grade controlled flag.';
COMMENT ON COLUMN xinv_item_creation_stg.default_grade IS 'Default grade when grade control is enabled.';
COMMENT ON COLUMN xinv_item_creation_stg.locator_control_code IS 'Business value for locator control.';
COMMENT ON COLUMN xinv_item_creation_stg.restrict_subinventories_flag IS 'Restrict subinventories flag.';
COMMENT ON COLUMN xinv_item_creation_stg.restrict_locators_flag IS 'Restrict locators flag.';
COMMENT ON COLUMN xinv_item_creation_stg.material_classification_type IS 'Material classification type.';
COMMENT ON COLUMN xinv_item_creation_stg.material_classification_control IS 'Material classification control value.';
COMMENT ON COLUMN xinv_item_creation_stg.category_set_name IS 'Category set name to be used when category assignment is added to the process.';
COMMENT ON COLUMN xinv_item_creation_stg.category_name IS 'Category name to be used when category assignment is added to the process.';
COMMENT ON COLUMN xinv_item_creation_stg.bom_step1_item1_number IS 'BOM step 1 component item 1.';
COMMENT ON COLUMN xinv_item_creation_stg.bom_step1_item1_qty IS 'BOM step 1 component item 1 quantity.';
COMMENT ON COLUMN xinv_item_creation_stg.bom_step1_item1_uom_code IS 'BOM step 1 component item 1 UOM.';
COMMENT ON COLUMN xinv_item_creation_stg.bom_step1_item1_theoretical_qty IS 'BOM step 1 component item 1 theoretical quantity.';
COMMENT ON COLUMN xinv_item_creation_stg.bom_step1_item2_number IS 'BOM step 1 component item 2.';
COMMENT ON COLUMN xinv_item_creation_stg.bom_step1_item2_qty IS 'BOM step 1 component item 2 quantity.';
COMMENT ON COLUMN xinv_item_creation_stg.bom_step1_item2_uom_code IS 'BOM step 1 component item 2 UOM.';
COMMENT ON COLUMN xinv_item_creation_stg.bom_step1_item2_theoretical_qty IS 'BOM step 1 component item 2 theoretical quantity.';
COMMENT ON COLUMN xinv_item_creation_stg.bom_step1_item3_number IS 'BOM step 1 component item 3.';
COMMENT ON COLUMN xinv_item_creation_stg.bom_step1_item3_qty IS 'BOM step 1 component item 3 quantity.';
COMMENT ON COLUMN xinv_item_creation_stg.bom_step1_item3_uom_code IS 'BOM step 1 component item 3 UOM.';
COMMENT ON COLUMN xinv_item_creation_stg.bom_step1_item3_theoretical_qty IS 'BOM step 1 component item 3 theoretical quantity.';
COMMENT ON COLUMN xinv_item_creation_stg.bom_step1_copy_from IS 'BOM step 1 copy-from item number.';
COMMENT ON COLUMN xinv_item_creation_stg.bom_step2_copy_from IS 'BOM step 2 copy-from item number.';
COMMENT ON COLUMN xinv_item_creation_stg.bom_step3_copy_from IS 'BOM step 3 copy-from item number.';
COMMENT ON COLUMN xinv_item_creation_stg.oracle_inventory_item_id IS 'Inventory item ID returned or confirmed after the EBS API process.';
COMMENT ON COLUMN xinv_item_creation_stg.oracle_organization_id IS 'Organization ID returned or confirmed after the EBS API process.';
COMMENT ON COLUMN xinv_item_creation_stg.api_return_status IS 'Return status received from EGO_ITEM_PUB.';
COMMENT ON COLUMN xinv_item_creation_stg.api_message_count IS 'Number of messages returned by EGO_ITEM_PUB.';
COMMENT ON COLUMN xinv_item_creation_stg.api_message_text IS 'Full API message text returned from EBS.';
COMMENT ON COLUMN xinv_item_creation_stg.api_processed_date IS 'Date and time when the API process was executed.';
COMMENT ON COLUMN xinv_item_creation_stg.created_by IS 'User that created the record.';
COMMENT ON COLUMN xinv_item_creation_stg.creation_date IS 'Date and time when the record was created.';
COMMENT ON COLUMN xinv_item_creation_stg.last_updated_by IS 'User that last updated the record.';
COMMENT ON COLUMN xinv_item_creation_stg.last_update_date IS 'Date and time when the record was last updated.';
COMMENT ON COLUMN xinv_item_creation_stg.last_update_login IS 'APEX session or database login that last updated the record.';
COMMENT ON COLUMN xinv_item_creation_stg.record_version_number IS 'Optimistic locking column for APEX forms.';

PROMPT ============================================================
PROMPT Creating audit triggers
PROMPT ============================================================

CREATE OR REPLACE TRIGGER xinv_item_types_biu
BEFORE INSERT OR UPDATE ON xinv_item_types
FOR EACH ROW
DECLARE
    l_user  VARCHAR2(100);
    l_login VARCHAR2(100);
BEGIN
    /*
       This trigger fills standard audit columns.
       When executed from APEX, it uses APP_USER and APP_SESSION.
       Otherwise, it uses the database session user and session id.
    */
    l_user  := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    l_login := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_SESSION'), SYS_CONTEXT('USERENV', 'SESSIONID'));

    IF INSERTING THEN
        :NEW.created_by            := NVL(:NEW.created_by, l_user);
        :NEW.creation_date         := NVL(:NEW.creation_date, SYSDATE);
        :NEW.record_version_number := NVL(:NEW.record_version_number, 1);
    ELSE
        :NEW.created_by            := :OLD.created_by;
        :NEW.creation_date         := :OLD.creation_date;
        :NEW.record_version_number := NVL(:OLD.record_version_number, 0) + 1;
    END IF;

    :NEW.last_updated_by   := l_user;
    :NEW.last_update_date  := SYSDATE;
    :NEW.last_update_login := l_login;
END;
/
SHOW ERRORS

CREATE OR REPLACE TRIGGER xinv_item_creation_stg_biu
BEFORE INSERT OR UPDATE ON xinv_item_creation_stg
FOR EACH ROW
DECLARE
    l_user  VARCHAR2(100);
    l_login VARCHAR2(100);
BEGIN
    /*
       This trigger fills standard audit columns.
       When executed from APEX, it uses APP_USER and APP_SESSION.
       Otherwise, it uses the database session user and session id.
    */
    l_user  := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    l_login := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_SESSION'), SYS_CONTEXT('USERENV', 'SESSIONID'));

    IF INSERTING THEN
        :NEW.created_by            := NVL(:NEW.created_by, l_user);
        :NEW.creation_date         := NVL(:NEW.creation_date, SYSDATE);
        :NEW.record_version_number := NVL(:NEW.record_version_number, 1);
    ELSE
        :NEW.created_by            := :OLD.created_by;
        :NEW.creation_date         := :OLD.creation_date;
        :NEW.record_version_number := NVL(:OLD.record_version_number, 0) + 1;
    END IF;

    :NEW.last_updated_by   := l_user;
    :NEW.last_update_date  := SYSDATE;
    :NEW.last_update_login := l_login;
END;
/
SHOW ERRORS

PROMPT ============================================================
PROMPT Creating indexes
PROMPT ============================================================

CREATE INDEX xinv_item_creation_stg_n1
    ON xinv_item_creation_stg (item_type_id);

CREATE INDEX xinv_item_creation_stg_n2
    ON xinv_item_creation_stg (request_status);

CREATE INDEX xinv_item_creation_stg_n3
    ON xinv_item_creation_stg (item_number);

CREATE INDEX xinv_item_creation_stg_n4
    ON xinv_item_creation_stg (master_org_code, target_org_code);

PROMPT ============================================================
PROMPT DDL completed
PROMPT ============================================================
