/* ============================================================
   AR Global - XINV Item Creation Staging DDL V2
   Purpose:
   - Recreate XINV item staging V2 objects for one-row item submission.
   - Store one master organization/template and one target organization/template.
   - Support the package flow:
       1) create or verify item in master org, e.g. MAS
       2) create or verify item in target org, e.g. GRI

   IMPORTANT:
   - Run this script as OPS, or change object ownership as needed.
   - This script DROPS and recreates the V2 custom tables only.
   - Do not run in production without backing up existing staging data.
   ============================================================ */

SET DEFINE OFF

PROMPT ============================================================
PROMPT Dropping previous custom objects if they exist
PROMPT ============================================================

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER xinv_item_creation_stg_v2_biu';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4080 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER xinv_item_types_v2_biu';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4080 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE xinv_item_creation_stg_v2 CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE xinv_item_types_v2 CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

PROMPT ============================================================
PROMPT Creating table XINV_ITEM_TYPES_V2
PROMPT ============================================================

CREATE TABLE xinv_item_types_v2 (
    item_type_id                     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                                      (START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE)
                                      NOT NULL,
    item_type_code                   VARCHAR2(50)         NOT NULL,
    item_type_name                   VARCHAR2(150)        NOT NULL,
    item_type_description            VARCHAR2(1000),

    default_primary_uom_code         VARCHAR2(30),
    default_item_status_code         VARCHAR2(30),
    default_part_status              VARCHAR2(50),

    default_master_org_code          VARCHAR2(30),
    default_master_template_name     VARCHAR2(150),
    default_target_org_code          VARCHAR2(30),
    default_target_template_name     VARCHAR2(150),

    default_division                 VARCHAR2(100),
    default_business_unit            VARCHAR2(100),
    default_inventory_class          VARCHAR2(150),
    default_outside_processing_flag  VARCHAR2(1)          DEFAULT 'N' NOT NULL,

    requires_bom_flag                VARCHAR2(1)          DEFAULT 'N' NOT NULL,
    requires_routing_flag            VARCHAR2(1)          DEFAULT 'N' NOT NULL,
    requires_shelf_life_flag         VARCHAR2(1)          DEFAULT 'N' NOT NULL,
    requires_lot_control_flag        VARCHAR2(1)          DEFAULT 'N' NOT NULL,
    requires_serial_control_flag     VARCHAR2(1)          DEFAULT 'N' NOT NULL,
    requires_revision_control_flag   VARCHAR2(1)          DEFAULT 'N' NOT NULL,
    requires_cost_rollup_flag        VARCHAR2(1)          DEFAULT 'N' NOT NULL,
    requires_engineering_review_flag VARCHAR2(1)          DEFAULT 'N' NOT NULL,

    default_inventory_item_flag      VARCHAR2(1)          DEFAULT 'Y' NOT NULL,
    default_stockable_flag           VARCHAR2(1)          DEFAULT 'Y' NOT NULL,
    default_transactable_flag        VARCHAR2(1)          DEFAULT 'Y' NOT NULL,
    default_purchasing_enabled_flag  VARCHAR2(1)          DEFAULT 'N' NOT NULL,
    default_customer_order_flag      VARCHAR2(1)          DEFAULT 'N' NOT NULL,
    default_bom_enabled_flag         VARCHAR2(1)          DEFAULT 'N' NOT NULL,
    default_build_in_wip_flag        VARCHAR2(1)          DEFAULT 'N' NOT NULL,
    default_costing_enabled_flag     VARCHAR2(1)          DEFAULT 'Y' NOT NULL,
    default_inventory_asset_flag     VARCHAR2(1)          DEFAULT 'Y' NOT NULL,

    active_flag                      VARCHAR2(1)          DEFAULT 'Y' NOT NULL,

    created_by                       VARCHAR2(100)        NOT NULL,
    creation_date                    DATE                 NOT NULL,
    last_updated_by                  VARCHAR2(100)        NOT NULL,
    last_update_date                 DATE                 NOT NULL,
    last_update_login                VARCHAR2(100),
    record_version_number            NUMBER               DEFAULT 1 NOT NULL,

    CONSTRAINT xinv_itm_typ_v2_pk
        PRIMARY KEY (item_type_id),

    CONSTRAINT xinv_itm_typ_v2_u1
        UNIQUE (item_type_code),

    CONSTRAINT xinv_itm_typ_v2_act_ck
        CHECK (active_flag IN ('Y', 'N')),

    CONSTRAINT xinv_itm_typ_v2_flg_ck
        CHECK (
            default_outside_processing_flag IN ('Y', 'N')
            AND requires_bom_flag IN ('Y', 'N')
            AND requires_routing_flag IN ('Y', 'N')
            AND requires_shelf_life_flag IN ('Y', 'N')
            AND requires_lot_control_flag IN ('Y', 'N')
            AND requires_serial_control_flag IN ('Y', 'N')
            AND requires_revision_control_flag IN ('Y', 'N')
            AND requires_cost_rollup_flag IN ('Y', 'N')
            AND requires_engineering_review_flag IN ('Y', 'N')
            AND default_inventory_item_flag IN ('Y', 'N')
            AND default_stockable_flag IN ('Y', 'N')
            AND default_transactable_flag IN ('Y', 'N')
            AND default_purchasing_enabled_flag IN ('Y', 'N')
            AND default_customer_order_flag IN ('Y', 'N')
            AND default_bom_enabled_flag IN ('Y', 'N')
            AND default_build_in_wip_flag IN ('Y', 'N')
            AND default_costing_enabled_flag IN ('Y', 'N')
            AND default_inventory_asset_flag IN ('Y', 'N')
        )
);
/

COMMENT ON TABLE xinv_item_types_v2 IS 'Defines item type configuration used by the AR Global APEX item creation process.';
COMMENT ON COLUMN xinv_item_types_v2.default_master_template_name IS 'Default template used for item creation in the master organization.';
COMMENT ON COLUMN xinv_item_types_v2.default_target_template_name IS 'Default template used for item assignment or creation in the target organization.';

PROMPT ============================================================
PROMPT Creating table XINV_ITEM_CREATION_STG_V2
PROMPT ============================================================

CREATE TABLE xinv_item_creation_stg_v2 (
    item_creation_stg_id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                                      (START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE)
                                      NOT NULL,
    request_number                   VARCHAR2(50)        NOT NULL,
    request_status                   VARCHAR2(30)        DEFAULT 'DRAFT' NOT NULL,

    item_type_id                     NUMBER              NOT NULL,

    api_transaction_type             VARCHAR2(30)        DEFAULT 'CREATE' NOT NULL,
    validate_only_flag               VARCHAR2(1)         DEFAULT 'Y' NOT NULL,

    base_part_number                 VARCHAR2(100),
    item_number                      VARCHAR2(100)       NOT NULL,
    part_status                      VARCHAR2(50),
    item_description                 VARCHAR2(240)       NOT NULL,
    long_description                 VARCHAR2(4000),

    primary_uom_code                 VARCHAR2(30)        NOT NULL,
    item_status_code                 VARCHAR2(30),

    master_org_code                  VARCHAR2(30)        NOT NULL,
    master_template_name             VARCHAR2(150)       NOT NULL,
    target_org_code                  VARCHAR2(30),
    target_template_name             VARCHAR2(150),

    legacy_template_name             VARCHAR2(150),

    outside_processing_flag          VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    planner_code                     VARCHAR2(50),
    division                         VARCHAR2(100),
    business_unit                    VARCHAR2(100),
    cost_rollup_requested_flag       VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    engineering_status               VARCHAR2(100),
    pdr_number                       VARCHAR2(100),
    tsr_number                       VARCHAR2(100),
    ucm_content_id                   VARCHAR2(200),
    inventory_class                  VARCHAR2(150),

    inventory_item_flag              VARCHAR2(1)         DEFAULT 'Y' NOT NULL,
    revision_control_flag            VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    stockable_flag                   VARCHAR2(1)         DEFAULT 'Y' NOT NULL,
    reservable_flag                  VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    transactable_flag                VARCHAR2(1)         DEFAULT 'Y' NOT NULL,
    check_material_shortage_flag     VARCHAR2(1)         DEFAULT 'Y' NOT NULL,
    cycle_count_enabled_flag         VARCHAR2(1)         DEFAULT 'Y' NOT NULL,

    purchasing_enabled_flag          VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    customer_order_flag              VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    shippable_flag                   VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    invoiceable_flag                 VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    bom_enabled_flag                 VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    build_in_wip_flag                VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    costing_enabled_flag             VARCHAR2(1)         DEFAULT 'Y' NOT NULL,
    inventory_asset_flag             VARCHAR2(1)         DEFAULT 'Y' NOT NULL,

    lot_expiration_control           VARCHAR2(50),
    shelf_life_days                  NUMBER,
    retest_interval_days             NUMBER,
    expiration_action_interval       NUMBER,
    expiration_action_code           VARCHAR2(50),

    lot_control_code                 VARCHAR2(50),
    lot_starting_prefix              VARCHAR2(50),
    lot_starting_number              VARCHAR2(50),
    lot_maturity_days                NUMBER,
    lot_hold_days                    NUMBER,

    serial_generation_control        VARCHAR2(50),
    serial_tagging_enabled_flag      VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    serial_starting_prefix           VARCHAR2(50),
    serial_starting_number           VARCHAR2(50),

    grade_controlled_flag            VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    default_grade                    VARCHAR2(50),

    locator_control_code             VARCHAR2(50),
    restrict_subinventories_flag     VARCHAR2(1)         DEFAULT 'N' NOT NULL,
    restrict_locators_flag           VARCHAR2(1)         DEFAULT 'N' NOT NULL,

    material_classification_type     VARCHAR2(100),
    material_classification_control  VARCHAR2(100),

    category_set_name                VARCHAR2(150),
    category_name                    VARCHAR2(250),

    bom_step1_item1_number           VARCHAR2(100),
    bom_step1_item1_qty              NUMBER,
    bom_step1_item1_uom_code         VARCHAR2(30),
    bom_step1_item1_theoretical_qty  NUMBER,
    bom_step1_item2_number           VARCHAR2(100),
    bom_step1_item2_qty              NUMBER,
    bom_step1_item2_uom_code         VARCHAR2(30),
    bom_step1_item2_theoretical_qty  NUMBER,
    bom_step1_item3_number           VARCHAR2(100),
    bom_step1_item3_qty              NUMBER,
    bom_step1_item3_uom_code         VARCHAR2(30),
    bom_step1_item3_theoretical_qty  NUMBER,
    bom_step1_copy_from              VARCHAR2(100),

    bom_step2_item1_number           VARCHAR2(100),
    bom_step2_item1_qty              NUMBER,
    bom_step2_item1_uom_code         VARCHAR2(30),
    bom_step2_item1_theoretical_qty  NUMBER,
    bom_step2_item2_number           VARCHAR2(100),
    bom_step2_item2_qty              NUMBER,
    bom_step2_item2_uom_code         VARCHAR2(30),
    bom_step2_item2_theoretical_qty  NUMBER,
    bom_step2_item3_number           VARCHAR2(100),
    bom_step2_item3_qty              NUMBER,
    bom_step2_item3_uom_code         VARCHAR2(30),
    bom_step2_item3_theoretical_qty  NUMBER,
    bom_step2_copy_from              VARCHAR2(100),

    bom_step3_item1_number           VARCHAR2(100),
    bom_step3_item1_qty              NUMBER,
    bom_step3_item1_uom_code         VARCHAR2(30),
    bom_step3_item1_theoretical_qty  NUMBER,
    bom_step3_item2_number           VARCHAR2(100),
    bom_step3_item2_qty              NUMBER,
    bom_step3_item2_uom_code         VARCHAR2(30),
    bom_step3_item2_theoretical_qty  NUMBER,
    bom_step3_item3_number           VARCHAR2(100),
    bom_step3_item3_qty              NUMBER,
    bom_step3_item3_uom_code         VARCHAR2(30),
    bom_step3_item3_theoretical_qty  NUMBER,
    bom_step3_copy_from              VARCHAR2(100),

    master_inventory_item_id         NUMBER,
    master_organization_id           NUMBER,
    master_api_return_status         VARCHAR2(10),
    master_api_message_count         NUMBER,
    master_api_message_text          CLOB,
    master_api_processed_date        DATE,

    target_inventory_item_id         NUMBER,
    target_organization_id           NUMBER,
    target_api_return_status         VARCHAR2(10),
    target_api_message_count         NUMBER,
    target_api_message_text          CLOB,
    target_api_processed_date        DATE,

    oracle_inventory_item_id         NUMBER,
    oracle_organization_id           NUMBER,
    api_return_status                VARCHAR2(10),
    api_message_count                NUMBER,
    api_message_text                 CLOB,
    api_processed_date               DATE,

    created_by                       VARCHAR2(100)       NOT NULL,
    creation_date                    DATE                NOT NULL,
    last_updated_by                  VARCHAR2(100)       NOT NULL,
    last_update_date                 DATE                NOT NULL,
    last_update_login                VARCHAR2(100),
    record_version_number            NUMBER              DEFAULT 1 NOT NULL,

    CONSTRAINT xinv_itm_stg_v2_pk
        PRIMARY KEY (item_creation_stg_id),

    CONSTRAINT xinv_itm_stg_v2_u1
        UNIQUE (request_number),

    CONSTRAINT xinv_itm_stg_v2_fk1
        FOREIGN KEY (item_type_id)
        REFERENCES xinv_item_types_v2 (item_type_id),

    CONSTRAINT xinv_itm_stg_v2_status_ck
        CHECK (request_status IN (
            'DRAFT',
            'VALIDATED',
            'SUBMITTED',
            'PROCESSED',
            'ERROR',
            'CANCELLED'
        )),

    CONSTRAINT xinv_itm_stg_v2_api_tx_ck
        CHECK (api_transaction_type IN ('CREATE', 'UPDATE')),

    CONSTRAINT xinv_itm_stg_v2_val_ck
        CHECK (validate_only_flag IN ('Y', 'N')),

    CONSTRAINT xinv_itm_stg_v2_tgt_tpl_ck
        CHECK (target_org_code IS NULL OR target_template_name IS NOT NULL),

    CONSTRAINT xinv_itm_stg_v2_flg_ck
        CHECK (
            outside_processing_flag IN ('Y', 'N')
            AND cost_rollup_requested_flag IN ('Y', 'N')
            AND inventory_item_flag IN ('Y', 'N')
            AND revision_control_flag IN ('Y', 'N')
            AND stockable_flag IN ('Y', 'N')
            AND reservable_flag IN ('Y', 'N')
            AND transactable_flag IN ('Y', 'N')
            AND check_material_shortage_flag IN ('Y', 'N')
            AND cycle_count_enabled_flag IN ('Y', 'N')
            AND purchasing_enabled_flag IN ('Y', 'N')
            AND customer_order_flag IN ('Y', 'N')
            AND shippable_flag IN ('Y', 'N')
            AND invoiceable_flag IN ('Y', 'N')
            AND bom_enabled_flag IN ('Y', 'N')
            AND build_in_wip_flag IN ('Y', 'N')
            AND costing_enabled_flag IN ('Y', 'N')
            AND inventory_asset_flag IN ('Y', 'N')
            AND serial_tagging_enabled_flag IN ('Y', 'N')
            AND grade_controlled_flag IN ('Y', 'N')
            AND restrict_subinventories_flag IN ('Y', 'N')
            AND restrict_locators_flag IN ('Y', 'N')
        )
);
/

COMMENT ON TABLE xinv_item_creation_stg_v2 IS 'Main AR Global staging table for one item creation request captured in APEX. One row can create or verify the item in the master org and create or verify it in one target org.';
COMMENT ON COLUMN xinv_item_creation_stg_v2.master_org_code IS 'Master organization code where the item must exist first, for example MAS.';
COMMENT ON COLUMN xinv_item_creation_stg_v2.master_template_name IS 'Template used when creating the item in the master organization.';
COMMENT ON COLUMN xinv_item_creation_stg_v2.target_org_code IS 'Target inventory organization code where the item should be assigned or created, for example GRI.';
COMMENT ON COLUMN xinv_item_creation_stg_v2.target_template_name IS 'Template used when creating or assigning the item in the target organization.';
COMMENT ON COLUMN xinv_item_creation_stg_v2.legacy_template_name IS 'Legacy single-template column retained only for migration or fallback. New APEX logic should use MASTER_TEMPLATE_NAME and TARGET_TEMPLATE_NAME.';
COMMENT ON COLUMN xinv_item_creation_stg_v2.master_inventory_item_id IS 'Inventory item ID confirmed or returned for the master organization step.';
COMMENT ON COLUMN xinv_item_creation_stg_v2.master_organization_id IS 'Organization ID confirmed or returned for the master organization step.';
COMMENT ON COLUMN xinv_item_creation_stg_v2.target_inventory_item_id IS 'Inventory item ID confirmed or returned for the target organization step.';
COMMENT ON COLUMN xinv_item_creation_stg_v2.target_organization_id IS 'Organization ID confirmed or returned for the target organization step.';
COMMENT ON COLUMN xinv_item_creation_stg_v2.oracle_inventory_item_id IS 'Final inventory item ID returned or confirmed by the process. Target value is preferred when target org exists.';
COMMENT ON COLUMN xinv_item_creation_stg_v2.oracle_organization_id IS 'Final organization ID returned or confirmed by the process. Target value is preferred when target org exists.';
COMMENT ON COLUMN xinv_item_creation_stg_v2.api_return_status IS 'Overall package result: S, E, or U.';
COMMENT ON COLUMN xinv_item_creation_stg_v2.api_message_text IS 'Overall package message returned to APEX.';

PROMPT ============================================================
PROMPT Creating audit triggers
PROMPT ============================================================

CREATE OR REPLACE TRIGGER xinv_item_types_v2_biu
BEFORE INSERT OR UPDATE ON xinv_item_types_v2
FOR EACH ROW
DECLARE
    l_user  VARCHAR2(100);
    l_login VARCHAR2(100);
BEGIN
    l_user  := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    l_login := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_SESSION'), SYS_CONTEXT('USERENV', 'SESSIONID'));

    IF INSERTING THEN
        :NEW.created_by            := NVL(:NEW.created_by, l_user);
        :NEW.creation_date         := NVL(:NEW.creation_date, SYSDATE);
        :NEW.record_version_number := NVL(:NEW.record_version_number, 1);
    ELSE
        :NEW.created_by            := :OLD.created_by;
        :NEW.creation_date         := :OLD.creation_date;
        :NEW.record_version_number := NVL(:OLD.record_version_number, 0) + 1;
    END IF;

    :NEW.last_updated_by   := l_user;
    :NEW.last_update_date  := SYSDATE;
    :NEW.last_update_login := l_login;
END;
/
SHOW ERRORS

CREATE OR REPLACE TRIGGER xinv_item_creation_stg_v2_biu
BEFORE INSERT OR UPDATE ON xinv_item_creation_stg_v2
FOR EACH ROW
DECLARE
    l_user  VARCHAR2(100);
    l_login VARCHAR2(100);
BEGIN
    l_user  := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    l_login := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_SESSION'), SYS_CONTEXT('USERENV', 'SESSIONID'));

    IF INSERTING THEN
        :NEW.created_by            := NVL(:NEW.created_by, l_user);
        :NEW.creation_date         := NVL(:NEW.creation_date, SYSDATE);
        :NEW.record_version_number := NVL(:NEW.record_version_number, 1);
    ELSE
        :NEW.created_by            := :OLD.created_by;
        :NEW.creation_date         := :OLD.creation_date;
        :NEW.record_version_number := NVL(:OLD.record_version_number, 0) + 1;
    END IF;

    :NEW.last_updated_by   := l_user;
    :NEW.last_update_date  := SYSDATE;
    :NEW.last_update_login := l_login;
END;
/
SHOW ERRORS

PROMPT ============================================================
PROMPT Creating indexes
PROMPT ============================================================

CREATE INDEX xinv_itm_stg_v2_n1
    ON xinv_item_creation_stg_v2 (item_type_id);

CREATE INDEX xinv_itm_stg_v2_n2
    ON xinv_item_creation_stg_v2 (request_status);

CREATE INDEX xinv_itm_stg_v2_n3
    ON xinv_item_creation_stg_v2 (item_number);

CREATE INDEX xinv_itm_stg_v2_n4
    ON xinv_item_creation_stg_v2 (master_org_code, target_org_code);

CREATE INDEX xinv_itm_stg_v2_n5
    ON xinv_item_creation_stg_v2 (master_template_name, target_template_name);

PROMPT ============================================================
PROMPT DDL completed
PROMPT ============================================================
