-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Recreate the Item Request header transaction table for the final
-- Adhesives Research Inventory Item Creation application.
--
-- One row represents one inventory item creation request.
--
-- This table stores the general information entered on the main
-- Item Request page in Oracle APEX.
--
-- Organization-specific information, categories, configurable
-- attributes, documents and BOM data are stored in related tables.
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Drop the existing table when it already exists.
--
-- CASCADE CONSTRAINTS is used because other prototype or previously
-- created application tables may currently reference this table.
--
-- ORA-00942 is ignored because it means the table does not exist.
-- Any other Oracle error is raised normally.
-- =====================================================================

BEGIN
    EXECUTE IMMEDIATE
        'DROP TABLE ops.adre_inv_item_request CASCADE CONSTRAINTS PURGE';

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Create the Item Request header transaction table.
-- =====================================================================

CREATE TABLE ops.adre_inv_item_request
(
    item_request_id
        NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        NOT NULL,

    request_number
        VARCHAR2(100),

    request_status
        VARCHAR2(30)
        DEFAULT 'DRAFT'
        NOT NULL,

    item_type_id
        NUMBER
        NOT NULL,

    base_part_number
        VARCHAR2(100),

    item_number
        VARCHAR2(250),

    part_status
        VARCHAR2(30),

    item_description
        VARCHAR2(240),

    long_description
        CLOB,

    primary_uom_code
        VARCHAR2(30),

    item_status_code
        VARCHAR2(30),

    initiator
        VARCHAR2(100),

    requested_creation_date
        DATE,

    forecast_flag
        VARCHAR2(1),

    ebs_submit_date
        DATE,

    api_return_status
        VARCHAR2(10),

    api_message_count
        NUMBER,

    api_message_text
        CLOB,

    api_processed_date
        DATE,

    created_by
        VARCHAR2(100)
        NOT NULL,

    creation_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_updated_by
        VARCHAR2(100)
        NOT NULL,

    last_update_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_update_login
        VARCHAR2(100),

    record_version_number
        NUMBER
        DEFAULT 1
        NOT NULL,

    CONSTRAINT adre_inv_item_request_pk
        PRIMARY KEY
        (
            item_request_id
        ),

    CONSTRAINT adre_inv_item_request_u1
        UNIQUE
        (
            request_number
        ),

    CONSTRAINT adre_inv_item_request_fk1
        FOREIGN KEY
        (
            item_type_id
        )
        REFERENCES ops.adre_inv_item_type
        (
            item_type_id
        ),

    CONSTRAINT adre_inv_item_request_ck1
        CHECK
        (
            request_status IN
            (
                'DRAFT',
                'READY',
                'PROCESSING',
                'PROCESSED',
                'ERROR'
            )
        ),

    CONSTRAINT adre_inv_item_request_ck2
        CHECK
        (
            forecast_flag IS NULL
            OR forecast_flag IN ('Y', 'N')
        ),

    CONSTRAINT adre_inv_item_request_ck3
        CHECK
        (
            api_message_count IS NULL
            OR api_message_count >= 0
        ),

    CONSTRAINT adre_inv_item_request_ck4
        CHECK
        (
            record_version_number > 0
        )
);


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support item lookup and duplicate item validation.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_request_n1
    ON ops.adre_inv_item_request
    (
        item_number
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support the Oracle APEX Home page report where requests are commonly
-- filtered by status and ordered by creation date.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_request_n2
    ON ops.adre_inv_item_request
    (
        request_status,
        creation_date
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support retrieval and reporting of requests by Item Type.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_request_n3
    ON ops.adre_inv_item_request
    (
        item_type_id
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add table documentation.
-- =====================================================================

COMMENT ON TABLE ops.adre_inv_item_request IS
'Header transaction table containing one row for each inventory item creation request in the Adhesives Research application.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add column documentation.
-- =====================================================================

COMMENT ON COLUMN ops.adre_inv_item_request.item_request_id IS
'Surrogate primary key generated by Oracle for each Item Request.';

COMMENT ON COLUMN ops.adre_inv_item_request.request_number IS
'Unique business request number displayed to Oracle APEX users.';

COMMENT ON COLUMN ops.adre_inv_item_request.request_status IS
'Current processing status of the Item Request. Valid values are DRAFT, READY, PROCESSING, PROCESSED and ERROR.';

COMMENT ON COLUMN ops.adre_inv_item_request.item_type_id IS
'Foreign key identifying the Item Type selected for the request.';

COMMENT ON COLUMN ops.adre_inv_item_request.base_part_number IS
'Base part number associated with the requested inventory item.';

COMMENT ON COLUMN ops.adre_inv_item_request.item_number IS
'Oracle EBS inventory item number requested for creation.';

COMMENT ON COLUMN ops.adre_inv_item_request.part_status IS
'Business part status associated with the requested item.';

COMMENT ON COLUMN ops.adre_inv_item_request.item_description IS
'Short description of the requested inventory item.';

COMMENT ON COLUMN ops.adre_inv_item_request.long_description IS
'Extended description of the requested inventory item.';

COMMENT ON COLUMN ops.adre_inv_item_request.primary_uom_code IS
'Primary unit of measure code for the requested inventory item.';

COMMENT ON COLUMN ops.adre_inv_item_request.item_status_code IS
'Oracle EBS inventory item status code to be assigned to the item.';

COMMENT ON COLUMN ops.adre_inv_item_request.initiator IS
'User or business initiator responsible for the Item Request.';

COMMENT ON COLUMN ops.adre_inv_item_request.requested_creation_date IS
'Business requested creation date for the inventory item.';

COMMENT ON COLUMN ops.adre_inv_item_request.forecast_flag IS
'Indicates whether the requested inventory item is forecasted. Valid values are Y and N.';

COMMENT ON COLUMN ops.adre_inv_item_request.ebs_submit_date IS
'Date and time when the Item Request was submitted to Oracle EBS.';

COMMENT ON COLUMN ops.adre_inv_item_request.api_return_status IS
'Overall return status received from the Oracle EBS item creation API.';

COMMENT ON COLUMN ops.adre_inv_item_request.api_message_count IS
'Number of messages returned by the Oracle EBS item creation API.';

COMMENT ON COLUMN ops.adre_inv_item_request.api_message_text IS
'Overall message or error information returned by the Oracle EBS item creation API.';

COMMENT ON COLUMN ops.adre_inv_item_request.api_processed_date IS
'Date and time when Oracle EBS API processing completed for the Item Request.';

COMMENT ON COLUMN ops.adre_inv_item_request.created_by IS
'Application or database user that created the row.';

COMMENT ON COLUMN ops.adre_inv_item_request.creation_date IS
'Date and time when the row was created.';

COMMENT ON COLUMN ops.adre_inv_item_request.last_updated_by IS
'Application or database user that last updated the row.';

COMMENT ON COLUMN ops.adre_inv_item_request.last_update_date IS
'Date and time when the row was last updated.';

COMMENT ON COLUMN ops.adre_inv_item_request.last_update_login IS
'Oracle APEX session identifier or database login associated with the last update.';

COMMENT ON COLUMN ops.adre_inv_item_request.record_version_number IS
'Row version number used for change tracking and optimistic locking.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Automatically maintain audit information and normalize selected
-- values for ADRE_INV_ITEM_REQUEST.
-- =====================================================================

CREATE OR REPLACE TRIGGER ops.adre_inv_item_request_biu
BEFORE INSERT OR UPDATE
ON ops.adre_inv_item_request
FOR EACH ROW

DECLARE

    l_user
        VARCHAR2(100);

    l_login
        VARCHAR2(100);

BEGIN

    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX user when available.
    -- Use the Oracle database user outside an APEX session.
    -- =================================================================

    l_user :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_USER'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX session identifier when available.
    -- =================================================================

    l_login :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_SESSION'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize application status values.
    -- =================================================================

    :NEW.request_status :=
        UPPER
        (
            TRIM
            (
                :NEW.request_status
            )
        );


    :NEW.forecast_flag :=
        UPPER
        (
            TRIM
            (
                :NEW.forecast_flag
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize common Oracle EBS code values.
    -- =================================================================

    :NEW.primary_uom_code :=
        UPPER
        (
            TRIM
            (
                :NEW.primary_uom_code
            )
        );


    :NEW.item_status_code :=
        UPPER
        (
            TRIM
            (
                :NEW.item_status_code
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Remove unnecessary leading and trailing spaces from common
    -- business values.
    -- =================================================================

    :NEW.request_number :=
        TRIM
        (
            :NEW.request_number
        );


    :NEW.base_part_number :=
        TRIM
        (
            :NEW.base_part_number
        );


    :NEW.item_number :=
        TRIM
        (
            :NEW.item_number
        );


    :NEW.part_status :=
        TRIM
        (
            :NEW.part_status
        );


    :NEW.item_description :=
        TRIM
        (
            :NEW.item_description
        );


    :NEW.initiator :=
        TRIM
        (
            :NEW.initiator
        );


    IF INSERTING THEN

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize creation audit information for a new Item Request.
        -- =============================================================

        :NEW.created_by :=
            NVL
            (
                :NEW.created_by,
                l_user
            );


        :NEW.creation_date :=
            NVL
            (
                :NEW.creation_date,
                SYSDATE
            );


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize the first row version.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :NEW.record_version_number,
                1
            );

    ELSE

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Preserve the original creation audit information.
        -- =============================================================

        :NEW.created_by :=
            :OLD.created_by;

        :NEW.creation_date :=
            :OLD.creation_date;


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Increment the row version number on every update.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :OLD.record_version_number,
                0
            ) + 1;

    END IF;


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Refresh last-update audit information.
    -- =================================================================

    :NEW.last_updated_by :=
        l_user;

    :NEW.last_update_date :=
        SYSDATE;

    :NEW.last_update_login :=
        l_login;

END;
/

-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the table exists and is VALID.
--
-- ALL_OBJECTS uses OBJECT_NAME. It does not contain TABLE_NAME.
-- =====================================================================

SELECT
    owner,
    object_name AS table_name,
    status
FROM all_objects
WHERE owner = 'OPS'
  AND object_name = 'ADRE_INV_ITEM_REQUEST'
  AND object_type = 'TABLE';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the trigger exists and is enabled.
-- =====================================================================

SELECT
    owner,
    trigger_name,
    table_name,
    status
FROM all_triggers
WHERE owner = 'OPS'
  AND trigger_name = 'ADRE_INV_ITEM_REQUEST_BIU';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Check for trigger compilation errors.
--
-- A successful trigger compilation returns no rows.
-- =====================================================================

SELECT
    line,
    position,
    text
FROM all_errors
WHERE owner = 'OPS'
  AND name = 'ADRE_INV_ITEM_REQUEST_BIU'
  AND type = 'TRIGGER'
ORDER BY sequence;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the table comment.
-- =====================================================================

SELECT
    table_name,
    comments
FROM all_tab_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_REQUEST';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate all column comments.
-- =====================================================================

SELECT
    column_name,
    comments
FROM all_col_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_REQUEST'
ORDER BY column_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================