-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Recreate the Item Attribute Value transaction table for the final
-- Adhesives Research Inventory Item Creation application.
--
-- This table stores the actual values entered by the user for
-- configurable Item Attributes associated with an Item Request
-- organization.
--
-- One row represents:
--
--   One Item Request Organization
--   +
--   One configurable Item Attribute
--   +
--   One transactional value
--
-- Values are stored according to their configured data type:
--
--   CHAR / YES_NO -> ATTRIBUTE_CHAR_VALUE
--   NUMBER        -> ATTRIBUTE_NUMBER_VALUE
--   DATE          -> ATTRIBUTE_DATE_VALUE
--
-- VALUE_UOM_CODE allows the Unit of Measure to vary by organization.
--
-- Example:
--
--   GRI / WIDTH  = 29 / INCH
--   IRL / WIDTH  = 1  / METER
--
-- Empty values are allowed while the Item Request remains in DRAFT
-- status.
--
-- Required attribute validation will occur before Send to EBS.
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Drop the existing table when it already exists.
--
-- CASCADE CONSTRAINTS removes foreign key references from previously
-- created dependent application objects during the schema rebuild.
--
-- ORA-00942 is ignored because it means the table does not exist.
-- Any other Oracle error is raised normally.
-- =====================================================================

BEGIN
    EXECUTE IMMEDIATE
        'DROP TABLE ops.adre_inv_item_attr_value CASCADE CONSTRAINTS PURGE';

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Create the Item Attribute Value transaction table.
-- =====================================================================

CREATE TABLE ops.adre_inv_item_attr_value
(
    item_attr_value_id
        NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        NOT NULL,

    request_org_id
        NUMBER
        NOT NULL,

    item_attribute_id
        NUMBER
        NOT NULL,

    attribute_char_value
        VARCHAR2(4000),

    attribute_number_value
        NUMBER,

    attribute_date_value
        DATE,

    value_uom_code
        VARCHAR2(30),

    value_status
        VARCHAR2(30)
        DEFAULT 'DRAFT'
        NOT NULL,

    api_return_status
        VARCHAR2(10),

    api_message_count
        NUMBER,

    api_message_text
        CLOB,

    api_processed_date
        DATE,

    created_by
        VARCHAR2(100)
        NOT NULL,

    creation_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_updated_by
        VARCHAR2(100)
        NOT NULL,

    last_update_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_update_login
        VARCHAR2(100),

    record_version_number
        NUMBER
        DEFAULT 1
        NOT NULL,

    CONSTRAINT adre_inv_item_attr_value_pk
        PRIMARY KEY
        (
            item_attr_value_id
        ),

    CONSTRAINT adre_inv_item_attr_value_fk1
        FOREIGN KEY
        (
            request_org_id
        )
        REFERENCES ops.adre_inv_item_request_org
        (
            request_org_id
        ),

    CONSTRAINT adre_inv_item_attr_value_fk2
        FOREIGN KEY
        (
            item_attribute_id
        )
        REFERENCES ops.adre_inv_item_attribute
        (
            item_attribute_id
        ),

    CONSTRAINT adre_inv_item_attr_value_u1
        UNIQUE
        (
            request_org_id,
            item_attribute_id
        ),

    CONSTRAINT adre_inv_item_attr_value_ck1
        CHECK
        (
            value_status IN
            (
                'DRAFT',
                'READY',
                'PROCESSING',
                'PROCESSED',
                'ERROR',
                'SKIPPED'
            )
        ),

    CONSTRAINT adre_inv_item_attr_value_ck2
        CHECK
        (
              CASE
                  WHEN attribute_char_value IS NOT NULL
                  THEN 1
                  ELSE 0
              END

            + CASE
                  WHEN attribute_number_value IS NOT NULL
                  THEN 1
                  ELSE 0
              END

            + CASE
                  WHEN attribute_date_value IS NOT NULL
                  THEN 1
                  ELSE 0
              END

            <= 1
        ),

    CONSTRAINT adre_inv_item_attr_value_ck3
        CHECK
        (
            api_message_count IS NULL
            OR api_message_count >= 0
        ),

    CONSTRAINT adre_inv_item_attr_value_ck4
        CHECK
        (
            record_version_number > 0
        )
);


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support retrieval of all configurable attribute values associated
-- with one Item Request organization.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_attr_value_n1
    ON ops.adre_inv_item_attr_value
    (
        request_org_id,
        value_status
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support retrieval and validation of transactional values associated
-- with a specific configurable Item Attribute.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_attr_value_n2
    ON ops.adre_inv_item_attr_value
    (
        item_attribute_id,
        value_status
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support API processing and monitoring of attribute values by status.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_attr_value_n3
    ON ops.adre_inv_item_attr_value
    (
        value_status,
        request_org_id
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add table documentation.
-- =====================================================================

COMMENT ON TABLE ops.adre_inv_item_attr_value IS
'Transaction table containing actual configurable Item Attribute values entered for each Item Request organization in the Adhesives Research Inventory Item Creation application.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add column documentation.
-- =====================================================================

COMMENT ON COLUMN ops.adre_inv_item_attr_value.item_attr_value_id IS
'Surrogate primary key generated by Oracle for each transactional Item Attribute value.';

COMMENT ON COLUMN ops.adre_inv_item_attr_value.request_org_id IS
'Foreign key identifying the Item Request organization to which the attribute value applies.';

COMMENT ON COLUMN ops.adre_inv_item_attr_value.item_attribute_id IS
'Foreign key identifying the configurable Item Attribute whose transactional value is stored.';

COMMENT ON COLUMN ops.adre_inv_item_attr_value.attribute_char_value IS
'Character value entered for CHAR or YES_NO attributes.';

COMMENT ON COLUMN ops.adre_inv_item_attr_value.attribute_number_value IS
'Numeric value entered for NUMBER attributes.';

COMMENT ON COLUMN ops.adre_inv_item_attr_value.attribute_date_value IS
'Date value entered for DATE attributes.';

COMMENT ON COLUMN ops.adre_inv_item_attr_value.value_uom_code IS
'Optional Unit of Measure code associated with the transactional attribute value. This allows the Unit of Measure to vary by organization.';

COMMENT ON COLUMN ops.adre_inv_item_attr_value.value_status IS
'Current processing status of the attribute value. Valid values are DRAFT, READY, PROCESSING, PROCESSED, ERROR and SKIPPED.';

COMMENT ON COLUMN ops.adre_inv_item_attr_value.api_return_status IS
'Return status received from the Oracle EBS or integration API for this attribute value.';

COMMENT ON COLUMN ops.adre_inv_item_attr_value.api_message_count IS
'Number of messages returned by the Oracle EBS or integration API for this attribute value.';

COMMENT ON COLUMN ops.adre_inv_item_attr_value.api_message_text IS
'Message or error information returned by the Oracle EBS or integration API for this attribute value.';

COMMENT ON COLUMN ops.adre_inv_item_attr_value.api_processed_date IS
'Date and time when API processing completed for this attribute value.';

COMMENT ON COLUMN ops.adre_inv_item_attr_value.created_by IS
'Application or database user that created the row.';

COMMENT ON COLUMN ops.adre_inv_item_attr_value.creation_date IS
'Date and time when the row was created.';

COMMENT ON COLUMN ops.adre_inv_item_attr_value.last_updated_by IS
'Application or database user that last updated the row.';

COMMENT ON COLUMN ops.adre_inv_item_attr_value.last_update_date IS
'Date and time when the row was last updated.';

COMMENT ON COLUMN ops.adre_inv_item_attr_value.last_update_login IS
'Oracle APEX session identifier or database login associated with the last update.';

COMMENT ON COLUMN ops.adre_inv_item_attr_value.record_version_number IS
'Row version number used for change tracking and optimistic locking.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Automatically maintain audit information and normalize transactional
-- attribute values for ADRE_INV_ITEM_ATTR_VALUE.
-- =====================================================================

CREATE OR REPLACE TRIGGER ops.adre_inv_item_attr_value_biu
BEFORE INSERT OR UPDATE
ON ops.adre_inv_item_attr_value
FOR EACH ROW

DECLARE

    l_user
        VARCHAR2(100);

    l_login
        VARCHAR2(100);

BEGIN

    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX user when available.
    --
    -- Use the current Oracle database user when the operation is
    -- executed outside Oracle APEX.
    -- =================================================================

    l_user :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_USER'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX session identifier when available.
    -- =================================================================

    l_login :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_SESSION'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the processing status.
    -- =================================================================

    :NEW.value_status :=
        UPPER
        (
            TRIM
            (
                :NEW.value_status
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the Unit of Measure code when populated.
    --
    -- Example:
    -- inch
    --
    -- becomes:
    -- INCH
    -- =================================================================

    :NEW.value_uom_code :=
        UPPER
        (
            TRIM
            (
                :NEW.value_uom_code
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Remove unnecessary leading and trailing spaces from character
    -- attribute values.
    --
    -- Oracle automatically treats an empty VARCHAR2 string as NULL.
    -- =================================================================

    :NEW.attribute_char_value :=
        TRIM
        (
            :NEW.attribute_char_value
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the Oracle EBS API return status when populated.
    -- =================================================================

    :NEW.api_return_status :=
        UPPER
        (
            TRIM
            (
                :NEW.api_return_status
            )
        );


    IF INSERTING THEN

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize creation audit information for a new transactional
        -- attribute value.
        -- =============================================================

        :NEW.created_by :=
            NVL
            (
                :NEW.created_by,
                l_user
            );


        :NEW.creation_date :=
            NVL
            (
                :NEW.creation_date,
                SYSDATE
            );


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize the first row version.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :NEW.record_version_number,
                1
            );

    ELSE

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Preserve the original creation audit information.
        -- =============================================================

        :NEW.created_by :=
            :OLD.created_by;

        :NEW.creation_date :=
            :OLD.creation_date;


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Increment the row version number on every update.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :OLD.record_version_number,
                0
            ) + 1;

    END IF;


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Refresh last-update audit information for inserts and updates.
    -- =================================================================

    :NEW.last_updated_by :=
        l_user;

    :NEW.last_update_date :=
        SYSDATE;

    :NEW.last_update_login :=
        l_login;

END;
/

-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the table exists and is VALID.
--
-- ALL_OBJECTS uses OBJECT_NAME for the object identifier.
-- =====================================================================

SELECT
    owner,
    object_name AS table_name,
    status
FROM all_objects
WHERE owner = 'OPS'
  AND object_name = 'ADRE_INV_ITEM_ATTR_VALUE'
  AND object_type = 'TABLE';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the audit trigger exists and is enabled.
-- =====================================================================

SELECT
    owner,
    trigger_name,
    table_name,
    status
FROM all_triggers
WHERE owner = 'OPS'
  AND trigger_name = 'ADRE_INV_ITEM_ATTR_VALUE_BIU';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Check for trigger compilation errors.
--
-- A successful trigger compilation must return zero rows.
-- =====================================================================

SELECT
    line,
    position,
    text
FROM all_errors
WHERE owner = 'OPS'
  AND name = 'ADRE_INV_ITEM_ATTR_VALUE_BIU'
  AND type = 'TRIGGER'
ORDER BY sequence;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the table comment.
-- =====================================================================

SELECT
    table_name,
    comments
FROM all_tab_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_ATTR_VALUE';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate all column comments.
-- =====================================================================

SELECT
    column_name,
    comments
FROM all_col_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_ATTR_VALUE'
ORDER BY column_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the constraints created for the transactional Item Attribute
-- values.
-- =====================================================================

SELECT
    constraint_name,
    constraint_type,
    status,
    r_constraint_name
FROM all_constraints
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_ATTR_VALUE'
ORDER BY constraint_type,
         constraint_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================
