-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Recreate the Organization Details Section configuration table for the
-- final Adhesives Research Inventory Item Creation application.
--
-- This table defines the sections displayed inside the Organization
-- Details modal in Oracle APEX.
--
-- Example sections include:
--   - Engineering
--   - Document
--   - Inventory
--   - Costing
--   - Flexfield
--   - Categories
--   - BOM
--   - Physical Attributes
--   - Purchasing
--   - Lead Times
--
-- SECTION_TYPE determines how the application processes the section.
--
-- Valid SECTION_TYPE values:
--   ATTRIBUTE
--   CATEGORY
--   BOM
--   DOCUMENT
--
-- ORGANIZATION_SCOPE determines whether the section applies to:
--   MASTER
--   TARGET
--   BOTH
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Drop the existing table when it already exists.
--
-- CASCADE CONSTRAINTS removes foreign key references from previously
-- created dependent application objects during the schema rebuild.
--
-- ORA-00942 is ignored because it means the table does not exist.
-- Any other Oracle error is raised normally.
-- =====================================================================

BEGIN
    EXECUTE IMMEDIATE
        'DROP TABLE ops.adre_inv_item_section CASCADE CONSTRAINTS PURGE';

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Create the Organization Details Section configuration table.
-- =====================================================================

CREATE TABLE ops.adre_inv_item_section
(
    item_section_id
        NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        NOT NULL,

    section_code
        VARCHAR2(50)
        NOT NULL,

    section_name
        VARCHAR2(100)
        NOT NULL,

    section_type
        VARCHAR2(30)
        NOT NULL,

    organization_scope
        VARCHAR2(30)
        DEFAULT 'BOTH'
        NOT NULL,

    active_flag
        VARCHAR2(1)
        DEFAULT 'Y'
        NOT NULL,

    display_sequence
        NUMBER
        DEFAULT 10
        NOT NULL,

    created_by
        VARCHAR2(100)
        NOT NULL,

    creation_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_updated_by
        VARCHAR2(100)
        NOT NULL,

    last_update_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_update_login
        VARCHAR2(100),

    record_version_number
        NUMBER
        DEFAULT 1
        NOT NULL,

    CONSTRAINT adre_inv_item_section_pk
        PRIMARY KEY
        (
            item_section_id
        ),

    CONSTRAINT adre_inv_item_section_u1
        UNIQUE
        (
            section_code
        ),

    CONSTRAINT adre_inv_item_section_u2
        UNIQUE
        (
            section_name
        ),

    CONSTRAINT adre_inv_item_section_ck1
        CHECK
        (
            section_type IN
            (
                'ATTRIBUTE',
                'CATEGORY',
                'BOM',
                'DOCUMENT'
            )
        ),

    CONSTRAINT adre_inv_item_section_ck2
        CHECK
        (
            organization_scope IN
            (
                'MASTER',
                'TARGET',
                'BOTH'
            )
        ),

    CONSTRAINT adre_inv_item_section_ck3
        CHECK
        (
            active_flag IN
            (
                'Y',
                'N'
            )
        ),

    CONSTRAINT adre_inv_item_section_ck4
        CHECK
        (
            display_sequence > 0
        ),

    CONSTRAINT adre_inv_item_section_ck5
        CHECK
        (
            record_version_number > 0
        )
);


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support Oracle APEX rendering of active Organization Details sections
-- in the configured display sequence.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_section_n1
    ON ops.adre_inv_item_section
    (
        active_flag,
        display_sequence
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support retrieval of sections that apply to MASTER or TARGET
-- organizations.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_section_n2
    ON ops.adre_inv_item_section
    (
        organization_scope,
        active_flag
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support retrieval of sections by processing type.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_section_n3
    ON ops.adre_inv_item_section
    (
        section_type,
        active_flag
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add table documentation.
-- =====================================================================

COMMENT ON TABLE ops.adre_inv_item_section IS
'Configuration table containing the Organization Details sections displayed by the Adhesives Research Inventory Item Creation application.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add column documentation.
-- =====================================================================

COMMENT ON COLUMN ops.adre_inv_item_section.item_section_id IS
'Surrogate primary key generated by Oracle for each Organization Details section.';

COMMENT ON COLUMN ops.adre_inv_item_section.section_code IS
'Unique internal application code used to identify the Organization Details section.';

COMMENT ON COLUMN ops.adre_inv_item_section.section_name IS
'User-facing section name displayed in the Oracle APEX Organization Details modal.';

COMMENT ON COLUMN ops.adre_inv_item_section.section_type IS
'Processing type for the section. Valid values are ATTRIBUTE, CATEGORY, BOM and DOCUMENT.';

COMMENT ON COLUMN ops.adre_inv_item_section.organization_scope IS
'Defines whether the section applies to MASTER organizations, TARGET organizations or BOTH.';

COMMENT ON COLUMN ops.adre_inv_item_section.active_flag IS
'Indicates whether the section is available for use in the application. Valid values are Y and N.';

COMMENT ON COLUMN ops.adre_inv_item_section.display_sequence IS
'Controls the display order of sections in the Oracle APEX Organization Details modal.';

COMMENT ON COLUMN ops.adre_inv_item_section.created_by IS
'Application or database user that created the row.';

COMMENT ON COLUMN ops.adre_inv_item_section.creation_date IS
'Date and time when the row was created.';

COMMENT ON COLUMN ops.adre_inv_item_section.last_updated_by IS
'Application or database user that last updated the row.';

COMMENT ON COLUMN ops.adre_inv_item_section.last_update_date IS
'Date and time when the row was last updated.';

COMMENT ON COLUMN ops.adre_inv_item_section.last_update_login IS
'Oracle APEX session identifier or database login associated with the last update.';

COMMENT ON COLUMN ops.adre_inv_item_section.record_version_number IS
'Row version number used for change tracking and optimistic locking.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Automatically maintain audit information and normalize Organization
-- Details Section configuration values for ADRE_INV_ITEM_SECTION.
-- =====================================================================

CREATE OR REPLACE TRIGGER ops.adre_inv_item_section_biu
BEFORE INSERT OR UPDATE
ON ops.adre_inv_item_section
FOR EACH ROW

DECLARE

    l_user
        VARCHAR2(100);

    l_login
        VARCHAR2(100);

BEGIN

    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX user when available.
    --
    -- Use the current Oracle database user when the operation is
    -- executed outside Oracle APEX.
    -- =================================================================

    l_user :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_USER'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX session identifier when available.
    -- =================================================================

    l_login :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_SESSION'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the internal section code.
    --
    -- Example:
    -- physical_attributes
    --
    -- becomes:
    -- PHYSICAL_ATTRIBUTES
    -- =================================================================

    :NEW.section_code :=
        UPPER
        (
            TRIM
            (
                :NEW.section_code
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Preserve the user-facing section name while removing unnecessary
    -- leading and trailing spaces.
    -- =================================================================

    :NEW.section_name :=
        TRIM
        (
            :NEW.section_name
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the section processing type.
    -- =================================================================

    :NEW.section_type :=
        UPPER
        (
            TRIM
            (
                :NEW.section_type
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the organization scope.
    -- =================================================================

    :NEW.organization_scope :=
        UPPER
        (
            TRIM
            (
                :NEW.organization_scope
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the active indicator.
    -- =================================================================

    :NEW.active_flag :=
        UPPER
        (
            TRIM
            (
                :NEW.active_flag
            )
        );


    IF INSERTING THEN

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize creation audit information for a new section.
        -- =============================================================

        :NEW.created_by :=
            NVL
            (
                :NEW.created_by,
                l_user
            );


        :NEW.creation_date :=
            NVL
            (
                :NEW.creation_date,
                SYSDATE
            );


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize the first row version.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :NEW.record_version_number,
                1
            );

    ELSE

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Preserve the original creation audit information.
        -- =============================================================

        :NEW.created_by :=
            :OLD.created_by;

        :NEW.creation_date :=
            :OLD.creation_date;


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Increment the row version number on every update.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :OLD.record_version_number,
                0
            ) + 1;

    END IF;


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Refresh the last-update audit information for inserts and updates.
    -- =================================================================

    :NEW.last_updated_by :=
        l_user;

    :NEW.last_update_date :=
        SYSDATE;

    :NEW.last_update_login :=
        l_login;

END;
/

-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the table exists and is VALID.
--
-- ALL_OBJECTS uses OBJECT_NAME for the object identifier.
-- =====================================================================

SELECT
    owner,
    object_name AS table_name,
    status
FROM all_objects
WHERE owner = 'OPS'
  AND object_name = 'ADRE_INV_ITEM_SECTION'
  AND object_type = 'TABLE';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the audit trigger exists and is enabled.
-- =====================================================================

SELECT
    owner,
    trigger_name,
    table_name,
    status
FROM all_triggers
WHERE owner = 'OPS'
  AND trigger_name = 'ADRE_INV_ITEM_SECTION_BIU';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Check for trigger compilation errors.
--
-- A successful trigger compilation must return zero rows.
-- =====================================================================

SELECT
    line,
    position,
    text
FROM all_errors
WHERE owner = 'OPS'
  AND name = 'ADRE_INV_ITEM_SECTION_BIU'
  AND type = 'TRIGGER'
ORDER BY sequence;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the table comment.
-- =====================================================================

SELECT
    table_name,
    comments
FROM all_tab_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_SECTION';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate all column comments.
-- =====================================================================

SELECT
    column_name,
    comments
FROM all_col_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_SECTION'
ORDER BY column_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the constraints created for the section configuration.
-- =====================================================================

SELECT
    constraint_name,
    constraint_type,
    status
FROM all_constraints
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_SECTION'
ORDER BY constraint_type,
         constraint_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================