-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Create the final Request Organization table for the
-- Adhesives Research Inventory Item Creation application.
--
-- Oracle EBS is the system of record for:
--
--   - Inventory Organizations
--   - Item Templates
--
-- Therefore this table stores Oracle EBS identifiers directly:
--
--   EBS_ORGANIZATION_ID
--   EBS_TEMPLATE_ID
--
-- No local foreign keys are created for Oracle EBS Inventory
-- Organizations or Item Templates.
--
-- One Item Request can contain:
--
--   - One MASTER organization
--   - One or more TARGET organizations
--
-- REQUEST_ORG_ID is referenced by organization-specific transactional
-- tables such as Categories, Attribute Values, Documents, BOM and
-- API Log.
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Drop the existing table when it already exists.
--
-- ORA-00942 is ignored because it means the table does not exist.
-- Any other Oracle error is raised normally.
-- =====================================================================

BEGIN
    EXECUTE IMMEDIATE
        'DROP TABLE ops.adre_inv_item_request_org CASCADE CONSTRAINTS PURGE';

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Create the final Request Organization table.
-- =====================================================================

CREATE TABLE ops.adre_inv_item_request_org
(
    request_org_id
        NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        NOT NULL,

    item_request_id
        NUMBER
        NOT NULL,

    ebs_organization_id
        NUMBER
        NOT NULL,

    organization_role
        VARCHAR2(20)
        NOT NULL,

    ebs_template_id
        NUMBER,

    assignment_status
        VARCHAR2(30)
        DEFAULT 'DRAFT'
        NOT NULL,

    ebs_inventory_item_id
        NUMBER,

    api_return_status
        VARCHAR2(30),

    api_message_count
        NUMBER,

    api_message_text
        CLOB,

    api_processed_date
        DATE,

    created_by
        VARCHAR2(100)
        NOT NULL,

    creation_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_updated_by
        VARCHAR2(100)
        NOT NULL,

    last_update_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_update_login
        VARCHAR2(100),

    record_version_number
        NUMBER
        DEFAULT 1
        NOT NULL,


    CONSTRAINT adre_inv_item_request_org_pk
        PRIMARY KEY
        (
            request_org_id
        ),


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- ITEM_REQUEST is application-owned and therefore retains its
    -- local foreign key.
    -- =================================================================

    CONSTRAINT adre_inv_item_request_org_fk1
        FOREIGN KEY
        (
            item_request_id
        )
        REFERENCES ops.adre_inv_item_request
        (
            item_request_id
        ),


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Prevent the same Oracle EBS Inventory Organization from being
    -- assigned more than once to the same Item Request.
    -- =================================================================

    CONSTRAINT adre_inv_item_req_org_u1
        UNIQUE
        (
            item_request_id,
            ebs_organization_id
        ),


    CONSTRAINT adre_inv_item_req_org_ck1
        CHECK
        (
            organization_role IN
            (
                'MASTER',
                'TARGET'
            )
        ),


    CONSTRAINT adre_inv_item_req_org_ck2
        CHECK
        (
            assignment_status IN
            (
                'DRAFT',
                'READY',
                'PROCESSING',
                'PROCESSED',
                'ERROR',
                'SKIPPED'
            )
        ),


    CONSTRAINT adre_inv_item_req_org_ck3
        CHECK
        (
            ebs_inventory_item_id IS NULL
            OR ebs_inventory_item_id > 0
        ),


    CONSTRAINT adre_inv_item_req_org_ck4
        CHECK
        (
            api_message_count IS NULL
            OR api_message_count >= 0
        ),


    CONSTRAINT adre_inv_item_req_org_ck5
        CHECK
        (
            record_version_number > 0
        ),


    CONSTRAINT adre_inv_item_req_org_ck6
        CHECK
        (
            ebs_organization_id > 0
        ),


    CONSTRAINT adre_inv_item_req_org_ck7
        CHECK
        (
            ebs_template_id IS NULL
            OR ebs_template_id > 0
        )
);


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Enforce a maximum of one MASTER organization per Item Request.
--
-- TARGET organizations are not restricted by this index.
-- =====================================================================

CREATE UNIQUE INDEX ops.adre_inv_item_req_org_u2
    ON ops.adre_inv_item_request_org
    (
        CASE
            WHEN organization_role = 'MASTER'
            THEN item_request_id
        END
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support retrieval of organizations assigned to an Item Request by
-- organization role.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_req_org_n1
    ON ops.adre_inv_item_request_org
    (
        item_request_id,
        organization_role
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support processing queues by Assignment Status and Item Request.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_req_org_n2
    ON ops.adre_inv_item_request_org
    (
        assignment_status,
        item_request_id
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support searches by Oracle EBS Inventory Organization and Assignment
-- Status.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_req_org_n3
    ON ops.adre_inv_item_request_org
    (
        ebs_organization_id,
        assignment_status
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support retrieval by the Oracle EBS Inventory Item identifier
-- returned after processing.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_req_org_n4
    ON ops.adre_inv_item_request_org
    (
        ebs_inventory_item_id
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support searches and processing by the resolved Oracle EBS Item
-- Template identifier.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_req_org_n5
    ON ops.adre_inv_item_request_org
    (
        ebs_template_id
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add table documentation.
-- =====================================================================

COMMENT ON TABLE ops.adre_inv_item_request_org IS
'Associates an Item Request with an Oracle EBS Inventory Organization. Stores MASTER or TARGET role, resolved Oracle EBS Item Template, Oracle EBS Inventory Item identifier and organization-level processing status.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add column documentation.
-- =====================================================================

COMMENT ON COLUMN ops.adre_inv_item_request_org.request_org_id IS
'Surrogate primary key generated by Oracle for each Item Request and Inventory Organization assignment.';

COMMENT ON COLUMN ops.adre_inv_item_request_org.item_request_id IS
'Foreign key identifying the Item Request to which the Oracle EBS Inventory Organization is assigned.';

COMMENT ON COLUMN ops.adre_inv_item_request_org.ebs_organization_id IS
'Oracle EBS Inventory Organization identifier assigned to the Item Request. Oracle EBS is the system of record for Inventory Organizations.';

COMMENT ON COLUMN ops.adre_inv_item_request_org.organization_role IS
'Role of the Oracle EBS Inventory Organization within the Item Request. Valid values are MASTER and TARGET.';

COMMENT ON COLUMN ops.adre_inv_item_request_org.ebs_template_id IS
'Identifier of the existing Oracle EBS Item Template resolved for this Request Organization. NULL is allowed until template resolution is complete.';

COMMENT ON COLUMN ops.adre_inv_item_request_org.assignment_status IS
'Current organization-level processing status. Valid values are DRAFT, READY, PROCESSING, PROCESSED, ERROR and SKIPPED.';

COMMENT ON COLUMN ops.adre_inv_item_request_org.ebs_inventory_item_id IS
'Oracle EBS Inventory Item identifier returned after the item has been created or assigned to the Inventory Organization.';

COMMENT ON COLUMN ops.adre_inv_item_request_org.api_return_status IS
'Return status received from the Oracle EBS API for the most recent organization-level processing attempt.';

COMMENT ON COLUMN ops.adre_inv_item_request_org.api_message_count IS
'Number of messages returned by the Oracle EBS API for the most recent organization-level processing attempt.';

COMMENT ON COLUMN ops.adre_inv_item_request_org.api_message_text IS
'Messages returned by the Oracle EBS API for the most recent organization-level processing attempt.';

COMMENT ON COLUMN ops.adre_inv_item_request_org.api_processed_date IS
'Date and time when the most recent Oracle EBS organization-level API processing completed.';

COMMENT ON COLUMN ops.adre_inv_item_request_org.created_by IS
'Application or database user that created the row.';

COMMENT ON COLUMN ops.adre_inv_item_request_org.creation_date IS
'Date and time when the row was created.';

COMMENT ON COLUMN ops.adre_inv_item_request_org.last_updated_by IS
'Application or database user that last updated the row.';

COMMENT ON COLUMN ops.adre_inv_item_request_org.last_update_date IS
'Date and time when the row was last updated.';

COMMENT ON COLUMN ops.adre_inv_item_request_org.last_update_login IS
'Oracle APEX session identifier or database login associated with the last update.';

COMMENT ON COLUMN ops.adre_inv_item_request_org.record_version_number IS
'Row version number used for change tracking and optimistic locking.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Automatically maintain audit information and normalize Request
-- Organization processing values.
-- =====================================================================

CREATE OR REPLACE TRIGGER ops.adre_inv_item_req_org_biu
BEFORE INSERT OR UPDATE
ON ops.adre_inv_item_request_org
FOR EACH ROW

DECLARE

    l_user
        VARCHAR2(100);

    l_login
        VARCHAR2(100);

BEGIN

    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX user when available.

    l_user :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_USER'
            ),
            USER
        );


    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX session identifier when available.

    l_login :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_SESSION'
            ),
            USER
        );


    -- JCALZADILLA - 22.08.2026
    -- Normalize Organization Role.

    :NEW.organization_role :=
        UPPER
        (
            TRIM
            (
                :NEW.organization_role
            )
        );


    -- JCALZADILLA - 22.08.2026
    -- Normalize Assignment Status.

    :NEW.assignment_status :=
        UPPER
        (
            TRIM
            (
                :NEW.assignment_status
            )
        );


    -- JCALZADILLA - 22.08.2026
    -- Normalize API Return Status.

    :NEW.api_return_status :=
        UPPER
        (
            TRIM
            (
                :NEW.api_return_status
            )
        );


    IF INSERTING THEN

        -- JCALZADILLA - 22.08.2026
        -- Initialize creation audit information.

        :NEW.created_by :=
            NVL
            (
                :NEW.created_by,
                l_user
            );


        :NEW.creation_date :=
            NVL
            (
                :NEW.creation_date,
                SYSDATE
            );


        :NEW.record_version_number :=
            NVL
            (
                :NEW.record_version_number,
                1
            );

    ELSE

        -- JCALZADILLA - 22.08.2026
        -- Preserve original creation audit information.

        :NEW.created_by :=
            :OLD.created_by;

        :NEW.creation_date :=
            :OLD.creation_date;


        -- JCALZADILLA - 22.08.2026
        -- Increment the row version number.

        :NEW.record_version_number :=
            NVL
            (
                :OLD.record_version_number,
                0
            ) + 1;

    END IF;


    -- JCALZADILLA - 22.08.2026
    -- Refresh last-update audit information.

    :NEW.last_updated_by :=
        l_user;

    :NEW.last_update_date :=
        SYSDATE;

    :NEW.last_update_login :=
        l_login;

END;
/

-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the table exists.
--
-- Expected result:
-- STATUS = VALID
-- =====================================================================

SELECT
    owner,
    object_name AS table_name,
    status
FROM all_objects
WHERE owner = 'OPS'
  AND object_name = 'ADRE_INV_ITEM_REQUEST_ORG'
  AND object_type = 'TABLE';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the direct Oracle EBS reference columns.
--
-- Expected:
--
-- EBS_ORGANIZATION_ID   NUMBER   NULLABLE = N
-- EBS_TEMPLATE_ID       NUMBER   NULLABLE = Y
-- =====================================================================

SELECT
    column_name,
    data_type,
    nullable
FROM all_tab_columns
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_REQUEST_ORG'
  AND column_name IN
      (
          'EBS_ORGANIZATION_ID',
          'EBS_TEMPLATE_ID'
      )
ORDER BY column_id;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Confirm that obsolete local-reference columns do not exist.
--
-- Expected result:
-- 0 rows
-- =====================================================================

SELECT
    column_name
FROM all_tab_columns
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_REQUEST_ORG'
  AND column_name IN
      (
          'ITEM_ORG_ID',
          'ITEM_TEMPLATE_ID'
      );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate foreign keys.
--
-- Expected result:
--
-- ITEM_REQUEST_ID -> ADRE_INV_ITEM_REQUEST
--
-- There must be no foreign key to Oracle EBS base tables.
-- =====================================================================

SELECT
    c.constraint_name,
    cc.column_name,
    r.table_name AS referenced_table
FROM all_constraints c
JOIN all_cons_columns cc
  ON cc.owner = c.owner
 AND cc.constraint_name = c.constraint_name
JOIN all_constraints r
  ON r.owner = c.r_owner
 AND r.constraint_name = c.r_constraint_name
WHERE c.owner = 'OPS'
  AND c.table_name = 'ADRE_INV_ITEM_REQUEST_ORG'
  AND c.constraint_type = 'R'
ORDER BY
    c.constraint_name,
    cc.position;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate final indexes.
--
-- Expected:
--
-- ADRE_INV_ITEM_REQ_ORG_U2
-- ADRE_INV_ITEM_REQ_ORG_N1
-- ADRE_INV_ITEM_REQ_ORG_N2
-- ADRE_INV_ITEM_REQ_ORG_N3
-- ADRE_INV_ITEM_REQ_ORG_N4
-- ADRE_INV_ITEM_REQ_ORG_N5
--
-- All indexes must be VALID.
-- =====================================================================

SELECT
    index_name,
    uniqueness,
    status
FROM all_indexes
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_REQUEST_ORG'
ORDER BY index_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the audit trigger.
--
-- Expected:
-- ADRE_INV_ITEM_REQ_ORG_BIU = ENABLED
-- =====================================================================

SELECT
    owner,
    trigger_name,
    table_name,
    status
FROM all_triggers
WHERE owner = 'OPS'
  AND trigger_name = 'ADRE_INV_ITEM_REQ_ORG_BIU';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Check for trigger compilation errors.
--
-- Expected result:
-- 0 rows
-- =====================================================================

SELECT
    line,
    position,
    text
FROM all_errors
WHERE owner = 'OPS'
  AND name = 'ADRE_INV_ITEM_REQ_ORG_BIU'
  AND type = 'TRIGGER'
ORDER BY sequence;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that every column has documentation.
--
-- Expected result:
-- MISSING_COLUMN_COMMENTS = 0
-- =====================================================================

SELECT
    COUNT(*) AS missing_column_comments
FROM all_tab_columns c
LEFT JOIN all_col_comments cc
  ON cc.owner = c.owner
 AND cc.table_name = c.table_name
 AND cc.column_name = c.column_name
WHERE c.owner = 'OPS'
  AND c.table_name = 'ADRE_INV_ITEM_REQUEST_ORG'
  AND cc.comments IS NULL;


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================