-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Create the final Item Category table for the
-- Adhesives Research Inventory Item Creation application.
--
-- Oracle EBS is the system of record for:
--
--   - Category Sets
--   - Categories
--
-- Therefore this table stores Oracle EBS identifiers directly:
--
--   EBS_CATEGORY_SET_ID
--   EBS_CATEGORY_ID
--
-- No local foreign key is created for Oracle EBS Category Sets or
-- Categories.
--
-- Each Request Organization can contain one Category assignment per
-- Oracle EBS Category Set.
--
-- EBS_CATEGORY_ID may remain NULL while the Item Request is in Draft
-- status and before the final Category has been resolved.
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Drop the existing table when it already exists.
--
-- ORA-00942 is ignored because it means the table does not exist.
-- Any other Oracle error is raised normally.
-- =====================================================================

BEGIN
    EXECUTE IMMEDIATE
        'DROP TABLE ops.adre_inv_item_category CASCADE CONSTRAINTS PURGE';

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Create the final Item Category table.
-- =====================================================================

CREATE TABLE ops.adre_inv_item_category
(
    item_category_id
        NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        NOT NULL,

    request_org_id
        NUMBER
        NOT NULL,

    ebs_category_set_id
        NUMBER
        NOT NULL,

    ebs_category_id
        NUMBER,

    category_value
        VARCHAR2(500),

    assignment_status
        VARCHAR2(30)
        DEFAULT 'DRAFT'
        NOT NULL,

    api_return_status
        VARCHAR2(30),

    api_message_count
        NUMBER,

    api_message_text
        CLOB,

    api_processed_date
        DATE,

    created_by
        VARCHAR2(100)
        NOT NULL,

    creation_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_updated_by
        VARCHAR2(100)
        NOT NULL,

    last_update_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_update_login
        VARCHAR2(100),

    record_version_number
        NUMBER
        DEFAULT 1
        NOT NULL,


    CONSTRAINT adre_inv_item_category_pk
        PRIMARY KEY
        (
            item_category_id
        ),


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- REQUEST_ORG remains application-owned and therefore retains its
    -- local foreign key.
    -- =================================================================

    CONSTRAINT adre_inv_item_category_fk1
        FOREIGN KEY
        (
            request_org_id
        )
        REFERENCES ops.adre_inv_item_request_org
        (
            request_org_id
        ),


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Prevent the same Oracle EBS Category Set from being assigned
    -- more than once to the same Request Organization.
    -- =================================================================

    CONSTRAINT adre_inv_item_category_u1
        UNIQUE
        (
            request_org_id,
            ebs_category_set_id
        ),


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Require a valid positive Oracle EBS Category Set identifier.
    -- =================================================================

    CONSTRAINT adre_inv_item_category_ck1
        CHECK
        (
            ebs_category_set_id > 0
        ),


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- EBS_CATEGORY_ID may remain NULL while Draft, but must be
    -- positive when populated.
    -- =================================================================

    CONSTRAINT adre_inv_item_category_ck2
        CHECK
        (
            ebs_category_id IS NULL
            OR ebs_category_id > 0
        ),


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Restrict Category processing status to supported application
    -- values.
    -- =================================================================

    CONSTRAINT adre_inv_item_category_ck3
        CHECK
        (
            assignment_status IN
            (
                'DRAFT',
                'READY',
                'PROCESSING',
                'PROCESSED',
                'ERROR',
                'SKIPPED'
            )
        ),


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- API message count cannot be negative.
    -- =================================================================

    CONSTRAINT adre_inv_item_category_ck4
        CHECK
        (
            api_message_count IS NULL
            OR api_message_count >= 0
        ),


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Record version must always be positive.
    -- =================================================================

    CONSTRAINT adre_inv_item_category_ck5
        CHECK
        (
            record_version_number > 0
        )
);


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support retrieval of Category assignments by Request Organization
-- and processing status.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_category_n1
    ON ops.adre_inv_item_category
    (
        request_org_id,
        assignment_status
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support Category processing queues.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_category_n2
    ON ops.adre_inv_item_category
    (
        assignment_status,
        request_org_id
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support searches using the resolved Oracle EBS Category identifier.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_category_n3
    ON ops.adre_inv_item_category
    (
        ebs_category_id
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support retrieval of Category assignments by Oracle EBS Category
-- Set and Request Organization.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_category_n4
    ON ops.adre_inv_item_category
    (
        ebs_category_set_id,
        request_org_id
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add table documentation.
-- =====================================================================

COMMENT ON TABLE ops.adre_inv_item_category IS
'Stores Oracle EBS Category assignments for each Item Request Organization. Oracle EBS is the system of record for Category Sets and Categories.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add column documentation.
-- =====================================================================

COMMENT ON COLUMN ops.adre_inv_item_category.item_category_id IS
'Surrogate primary key generated by Oracle for each Item Category assignment.';

COMMENT ON COLUMN ops.adre_inv_item_category.request_org_id IS
'Foreign key identifying the Item Request Organization to which the Category assignment belongs.';

COMMENT ON COLUMN ops.adre_inv_item_category.ebs_category_set_id IS
'Oracle EBS Category Set identifier associated with the Category assignment. Oracle EBS is the system of record for Category Sets.';

COMMENT ON COLUMN ops.adre_inv_item_category.ebs_category_id IS
'Oracle EBS Category identifier selected for the Request Organization and Category Set. NULL is allowed while the Item Request remains in Draft status.';

COMMENT ON COLUMN ops.adre_inv_item_category.category_value IS
'Display value of the selected Oracle EBS Category used by the application for review and processing context.';

COMMENT ON COLUMN ops.adre_inv_item_category.assignment_status IS
'Current Category processing status. Valid values are DRAFT, READY, PROCESSING, PROCESSED, ERROR and SKIPPED.';

COMMENT ON COLUMN ops.adre_inv_item_category.api_return_status IS
'Return status received from the Oracle EBS Category API for the most recent processing attempt.';

COMMENT ON COLUMN ops.adre_inv_item_category.api_message_count IS
'Number of messages returned by the Oracle EBS Category API for the most recent processing attempt.';

COMMENT ON COLUMN ops.adre_inv_item_category.api_message_text IS
'Messages returned by the Oracle EBS Category API for the most recent processing attempt.';

COMMENT ON COLUMN ops.adre_inv_item_category.api_processed_date IS
'Date and time when the most recent Oracle EBS Category API processing completed.';

COMMENT ON COLUMN ops.adre_inv_item_category.created_by IS
'Application or database user that created the row.';

COMMENT ON COLUMN ops.adre_inv_item_category.creation_date IS
'Date and time when the row was created.';

COMMENT ON COLUMN ops.adre_inv_item_category.last_updated_by IS
'Application or database user that last updated the row.';

COMMENT ON COLUMN ops.adre_inv_item_category.last_update_date IS
'Date and time when the row was last updated.';

COMMENT ON COLUMN ops.adre_inv_item_category.last_update_login IS
'Oracle APEX session identifier or database login associated with the last update.';

COMMENT ON COLUMN ops.adre_inv_item_category.record_version_number IS
'Row version number used for change tracking and optimistic locking.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Automatically maintain audit information and normalize Item Category
-- processing values.
-- =====================================================================

CREATE OR REPLACE TRIGGER ops.adre_inv_item_category_biu
BEFORE INSERT OR UPDATE
ON ops.adre_inv_item_category
FOR EACH ROW

DECLARE

    l_user
        VARCHAR2(100);

    l_login
        VARCHAR2(100);

BEGIN

    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX user when available.

    l_user :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_USER'
            ),
            USER
        );


    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX session identifier when available.

    l_login :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_SESSION'
            ),
            USER
        );


    -- JCALZADILLA - 22.08.2026
    -- Normalize Category display value.

    :NEW.category_value :=
        TRIM
        (
            :NEW.category_value
        );


    -- JCALZADILLA - 22.08.2026
    -- Normalize Assignment Status.

    :NEW.assignment_status :=
        UPPER
        (
            TRIM
            (
                :NEW.assignment_status
            )
        );


    -- JCALZADILLA - 22.08.2026
    -- Normalize API Return Status.

    :NEW.api_return_status :=
        UPPER
        (
            TRIM
            (
                :NEW.api_return_status
            )
        );


    IF INSERTING THEN

        -- JCALZADILLA - 22.08.2026
        -- Initialize creation audit information.

        :NEW.created_by :=
            NVL
            (
                :NEW.created_by,
                l_user
            );


        :NEW.creation_date :=
            NVL
            (
                :NEW.creation_date,
                SYSDATE
            );


        :NEW.record_version_number :=
            NVL
            (
                :NEW.record_version_number,
                1
            );

    ELSE

        -- JCALZADILLA - 22.08.2026
        -- Preserve original creation audit information.

        :NEW.created_by :=
            :OLD.created_by;

        :NEW.creation_date :=
            :OLD.creation_date;


        -- JCALZADILLA - 22.08.2026
        -- Increment the row version number.

        :NEW.record_version_number :=
            NVL
            (
                :OLD.record_version_number,
                0
            ) + 1;

    END IF;


    -- JCALZADILLA - 22.08.2026
    -- Refresh last-update audit information.

    :NEW.last_updated_by :=
        l_user;

    :NEW.last_update_date :=
        SYSDATE;

    :NEW.last_update_login :=
        l_login;

END;
/

-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the table exists.
--
-- Expected:
-- STATUS = VALID
-- =====================================================================

SELECT
    owner,
    object_name AS table_name,
    status
FROM all_objects
WHERE owner = 'OPS'
  AND object_name = 'ADRE_INV_ITEM_CATEGORY'
  AND object_type = 'TABLE';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the direct Oracle EBS Category references.
--
-- Expected:
--
-- EBS_CATEGORY_SET_ID    NUMBER   NULLABLE = N
-- EBS_CATEGORY_ID        NUMBER   NULLABLE = Y
-- =====================================================================

SELECT
    column_name,
    data_type,
    nullable
FROM all_tab_columns
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_CATEGORY'
  AND column_name IN
      (
          'EBS_CATEGORY_SET_ID',
          'EBS_CATEGORY_ID'
      )
ORDER BY column_id;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Confirm that the obsolete local Category Set reference does not
-- exist.
--
-- Expected result:
-- 0 rows
-- =====================================================================

SELECT
    column_name
FROM all_tab_columns
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_CATEGORY'
  AND column_name = 'ITEM_CAT_SET_ID';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate foreign keys.
--
-- Expected:
--
-- REQUEST_ORG_ID -> ADRE_INV_ITEM_REQUEST_ORG
--
-- There must be no foreign key to Oracle EBS base tables.
-- =====================================================================

SELECT
    c.constraint_name,
    cc.column_name,
    r.table_name AS referenced_table
FROM all_constraints c
JOIN all_cons_columns cc
  ON cc.owner = c.owner
 AND cc.constraint_name = c.constraint_name
JOIN all_constraints r
  ON r.owner = c.r_owner
 AND r.constraint_name = c.r_constraint_name
WHERE c.owner = 'OPS'
  AND c.table_name = 'ADRE_INV_ITEM_CATEGORY'
  AND c.constraint_type = 'R'
ORDER BY
    c.constraint_name,
    cc.position;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate final indexes.
--
-- Expected:
--
-- ADRE_INV_ITEM_CATEGORY_N1
-- ADRE_INV_ITEM_CATEGORY_N2
-- ADRE_INV_ITEM_CATEGORY_N3
-- ADRE_INV_ITEM_CATEGORY_N4
--
-- All indexes must be VALID.
-- =====================================================================

SELECT
    index_name,
    uniqueness,
    status
FROM all_indexes
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_CATEGORY'
ORDER BY index_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the audit trigger.
--
-- Expected:
-- ADRE_INV_ITEM_CATEGORY_BIU = ENABLED
-- =====================================================================

SELECT
    owner,
    trigger_name,
    table_name,
    status
FROM all_triggers
WHERE owner = 'OPS'
  AND trigger_name = 'ADRE_INV_ITEM_CATEGORY_BIU';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Check for trigger compilation errors.
--
-- Expected result:
-- 0 rows
-- =====================================================================

SELECT
    line,
    position,
    text
FROM all_errors
WHERE owner = 'OPS'
  AND name = 'ADRE_INV_ITEM_CATEGORY_BIU'
  AND type = 'TRIGGER'
ORDER BY sequence;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that every column has documentation.
--
-- Expected:
-- MISSING_COLUMN_COMMENTS = 0
-- =====================================================================

SELECT
    COUNT(*) AS missing_column_comments
FROM all_tab_columns c
LEFT JOIN all_col_comments cc
  ON cc.owner = c.owner
 AND cc.table_name = c.table_name
 AND cc.column_name = c.column_name
WHERE c.owner = 'OPS'
  AND c.table_name = 'ADRE_INV_ITEM_CATEGORY'
  AND cc.comments IS NULL;


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================