-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Recreate the Item Type to Attribute configuration table for the final
-- Adhesives Research Inventory Item Creation application.
--
-- This table determines which configurable attributes apply to each
-- Item Type.
--
-- Oracle APEX will use this configuration to dynamically determine:
--   - Which attributes must be displayed.
--   - Whether the attribute applies to MASTER organizations.
--   - Whether the attribute applies to TARGET organizations.
--   - Whether the attribute applies to BOTH organization roles.
--   - Whether the attribute is required for the selected Item Type.
--   - Whether an Item Type specific default value applies.
--
-- ORGANIZATION_SCOPE valid values:
--   MASTER
--   TARGET
--   BOTH
--
-- REQUIRED_FLAG allows the general attribute requirement configured in
-- ADRE_INV_ITEM_ATTRIBUTE to be overridden for a specific Item Type.
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Drop the existing table when it already exists.
--
-- CASCADE CONSTRAINTS removes foreign key references from previously
-- created dependent application objects during the schema rebuild.
--
-- ORA-00942 is ignored because it means the table does not exist.
-- Any other Oracle error is raised normally.
-- =====================================================================

BEGIN
    EXECUTE IMMEDIATE
        'DROP TABLE ops.adre_inv_item_type_attr CASCADE CONSTRAINTS PURGE';

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Create the Item Type to Attribute configuration table.
-- =====================================================================

CREATE TABLE ops.adre_inv_item_type_attr
(
    item_type_attr_id
        NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        NOT NULL,

    item_type_id
        NUMBER
        NOT NULL,

    item_attribute_id
        NUMBER
        NOT NULL,

    organization_scope
        VARCHAR2(30)
        DEFAULT 'BOTH'
        NOT NULL,

    required_flag
        VARCHAR2(1)
        DEFAULT 'N'
        NOT NULL,

    default_value
        VARCHAR2(1000),

    active_flag
        VARCHAR2(1)
        DEFAULT 'Y'
        NOT NULL,

    display_sequence
        NUMBER
        DEFAULT 10
        NOT NULL,

    created_by
        VARCHAR2(100)
        NOT NULL,

    creation_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_updated_by
        VARCHAR2(100)
        NOT NULL,

    last_update_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_update_login
        VARCHAR2(100),

    record_version_number
        NUMBER
        DEFAULT 1
        NOT NULL,

    CONSTRAINT adre_inv_item_type_attr_pk
        PRIMARY KEY
        (
            item_type_attr_id
        ),

    CONSTRAINT adre_inv_item_type_attr_fk1
        FOREIGN KEY
        (
            item_type_id
        )
        REFERENCES ops.adre_inv_item_type
        (
            item_type_id
        ),

    CONSTRAINT adre_inv_item_type_attr_fk2
        FOREIGN KEY
        (
            item_attribute_id
        )
        REFERENCES ops.adre_inv_item_attribute
        (
            item_attribute_id
        ),

    CONSTRAINT adre_inv_item_type_attr_u1
        UNIQUE
        (
            item_type_id,
            item_attribute_id,
            organization_scope
        ),

    CONSTRAINT adre_inv_item_type_attr_ck1
        CHECK
        (
            organization_scope IN
            (
                'MASTER',
                'TARGET',
                'BOTH'
            )
        ),

    CONSTRAINT adre_inv_item_type_attr_ck2
        CHECK
        (
            required_flag IN
            (
                'Y',
                'N'
            )
        ),

    CONSTRAINT adre_inv_item_type_attr_ck3
        CHECK
        (
            active_flag IN
            (
                'Y',
                'N'
            )
        ),

    CONSTRAINT adre_inv_item_type_attr_ck4
        CHECK
        (
            display_sequence > 0
        ),

    CONSTRAINT adre_inv_item_type_attr_ck5
        CHECK
        (
            record_version_number > 0
        )
);


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support Oracle APEX retrieval of all active attributes associated
-- with an Item Type and organization role.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_type_attr_n1
    ON ops.adre_inv_item_type_attr
    (
        item_type_id,
        organization_scope,
        active_flag,
        display_sequence
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support retrieval of all Item Type configurations associated with a
-- specific configurable attribute.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_type_attr_n2
    ON ops.adre_inv_item_type_attr
    (
        item_attribute_id,
        active_flag
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add table documentation.
-- =====================================================================

COMMENT ON TABLE ops.adre_inv_item_type_attr IS
'Configuration table defining which configurable Item Attributes apply to each Item Type in the Adhesives Research Inventory Item Creation application.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add column documentation.
-- =====================================================================

COMMENT ON COLUMN ops.adre_inv_item_type_attr.item_type_attr_id IS
'Surrogate primary key generated by Oracle for each Item Type to Attribute configuration.';

COMMENT ON COLUMN ops.adre_inv_item_type_attr.item_type_id IS
'Foreign key identifying the Item Type to which the configurable attribute applies.';

COMMENT ON COLUMN ops.adre_inv_item_type_attr.item_attribute_id IS
'Foreign key identifying the configurable Item Attribute associated with the Item Type.';

COMMENT ON COLUMN ops.adre_inv_item_type_attr.organization_scope IS
'Defines whether the attribute applies to MASTER organizations, TARGET organizations or BOTH for the selected Item Type.';

COMMENT ON COLUMN ops.adre_inv_item_type_attr.required_flag IS
'Indicates whether the attribute is required for this Item Type configuration. Valid values are Y and N.';

COMMENT ON COLUMN ops.adre_inv_item_type_attr.default_value IS
'Optional Item Type specific default value. When populated, this value overrides the general default configured in ADRE_INV_ITEM_ATTRIBUTE.';

COMMENT ON COLUMN ops.adre_inv_item_type_attr.active_flag IS
'Indicates whether the Item Type to Attribute configuration is active. Valid values are Y and N.';

COMMENT ON COLUMN ops.adre_inv_item_type_attr.display_sequence IS
'Controls the display order of the attribute for the selected Item Type in Oracle APEX.';

COMMENT ON COLUMN ops.adre_inv_item_type_attr.created_by IS
'Application or database user that created the row.';

COMMENT ON COLUMN ops.adre_inv_item_type_attr.creation_date IS
'Date and time when the row was created.';

COMMENT ON COLUMN ops.adre_inv_item_type_attr.last_updated_by IS
'Application or database user that last updated the row.';

COMMENT ON COLUMN ops.adre_inv_item_type_attr.last_update_date IS
'Date and time when the row was last updated.';

COMMENT ON COLUMN ops.adre_inv_item_type_attr.last_update_login IS
'Oracle APEX session identifier or database login associated with the last update.';

COMMENT ON COLUMN ops.adre_inv_item_type_attr.record_version_number IS
'Row version number used for change tracking and optimistic locking.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Automatically maintain audit information and normalize configuration
-- values for ADRE_INV_ITEM_TYPE_ATTR.
-- =====================================================================

CREATE OR REPLACE TRIGGER ops.adre_inv_item_type_attr_biu
BEFORE INSERT OR UPDATE
ON ops.adre_inv_item_type_attr
FOR EACH ROW

DECLARE

    l_user
        VARCHAR2(100);

    l_login
        VARCHAR2(100);

BEGIN

    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX user when available.
    --
    -- Use the current Oracle database user when the operation is
    -- executed outside Oracle APEX.
    -- =================================================================

    l_user :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_USER'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX session identifier when available.
    -- =================================================================

    l_login :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_SESSION'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the organization scope.
    -- =================================================================

    :NEW.organization_scope :=
        UPPER
        (
            TRIM
            (
                :NEW.organization_scope
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the required indicator.
    -- =================================================================

    :NEW.required_flag :=
        UPPER
        (
            TRIM
            (
                :NEW.required_flag
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the active indicator.
    -- =================================================================

    :NEW.active_flag :=
        UPPER
        (
            TRIM
            (
                :NEW.active_flag
            )
        );


    IF INSERTING THEN

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize creation audit information for a new Item Type to
        -- Attribute configuration.
        -- =============================================================

        :NEW.created_by :=
            NVL
            (
                :NEW.created_by,
                l_user
            );


        :NEW.creation_date :=
            NVL
            (
                :NEW.creation_date,
                SYSDATE
            );


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize the first row version.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :NEW.record_version_number,
                1
            );

    ELSE

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Preserve the original creation audit information.
        -- =============================================================

        :NEW.created_by :=
            :OLD.created_by;

        :NEW.creation_date :=
            :OLD.creation_date;


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Increment the row version number on every update.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :OLD.record_version_number,
                0
            ) + 1;

    END IF;


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Refresh last-update audit information for inserts and updates.
    -- =================================================================

    :NEW.last_updated_by :=
        l_user;

    :NEW.last_update_date :=
        SYSDATE;

    :NEW.last_update_login :=
        l_login;

END;
/

-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the table exists and is VALID.
--
-- ALL_OBJECTS uses OBJECT_NAME for the object identifier.
-- =====================================================================

SELECT
    owner,
    object_name AS table_name,
    status
FROM all_objects
WHERE owner = 'OPS'
  AND object_name = 'ADRE_INV_ITEM_TYPE_ATTR'
  AND object_type = 'TABLE';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the audit trigger exists and is enabled.
-- =====================================================================

SELECT
    owner,
    trigger_name,
    table_name,
    status
FROM all_triggers
WHERE owner = 'OPS'
  AND trigger_name = 'ADRE_INV_ITEM_TYPE_ATTR_BIU';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Check for trigger compilation errors.
--
-- A successful trigger compilation must return zero rows.
-- =====================================================================

SELECT
    line,
    position,
    text
FROM all_errors
WHERE owner = 'OPS'
  AND name = 'ADRE_INV_ITEM_TYPE_ATTR_BIU'
  AND type = 'TRIGGER'
ORDER BY sequence;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the table comment.
-- =====================================================================

SELECT
    table_name,
    comments
FROM all_tab_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_TYPE_ATTR';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate all column comments.
-- =====================================================================

SELECT
    column_name,
    comments
FROM all_col_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_TYPE_ATTR'
ORDER BY column_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate constraints created for the Item Type to Attribute
-- configuration.
-- =====================================================================

SELECT
    constraint_name,
    constraint_type,
    status,
    r_constraint_name
FROM all_constraints
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_TYPE_ATTR'
ORDER BY constraint_type,
         constraint_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================