-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Recreate the Bill of Material component transaction table for the
-- final Adhesives Research Inventory Item Creation application.
--
-- One row represents one component associated with a BOM header.
--
-- ITEM_BOM_ID identifies the BOM header that owns the component.
--
-- COMPONENT_ITEM_NUMBER stores the Oracle EBS component item number.
--
-- EBS_COMPONENT_ITEM_ID stores the Oracle EBS Inventory Item identifier
-- after the component has been validated or resolved.
--
-- COMPONENT_QUANTITY represents the quantity required per assembly.
--
-- OPERATION_SEQUENCE and ITEM_SEQUENCE support Oracle EBS BOM
-- sequencing.
--
-- EFFECTIVITY_DATE and DISABLE_DATE control the active period of the
-- component within the BOM.
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Drop the existing table when it already exists.
--
-- CASCADE CONSTRAINTS removes foreign key references from previously
-- created dependent application objects during the schema rebuild.
--
-- ORA-00942 is ignored because it means the table does not exist.
-- Any other Oracle error is raised normally.
-- =====================================================================

BEGIN
    EXECUTE IMMEDIATE
        'DROP TABLE ops.adre_inv_item_bom_comp CASCADE CONSTRAINTS PURGE';

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Create the Bill of Material component transaction table.
-- =====================================================================

CREATE TABLE ops.adre_inv_item_bom_comp
(
    item_bom_comp_id
        NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        NOT NULL,

    item_bom_id
        NUMBER
        NOT NULL,

    component_item_number
        VARCHAR2(250)
        NOT NULL,

    ebs_component_item_id
        NUMBER,

    component_quantity
        NUMBER
        NOT NULL,

    component_uom_code
        VARCHAR2(30),

    operation_sequence
        NUMBER
        DEFAULT 1
        NOT NULL,

    item_sequence
        NUMBER,

    effectivity_date
        DATE,

    disable_date
        DATE,

    supply_type
        VARCHAR2(30),

    component_status
        VARCHAR2(30)
        DEFAULT 'DRAFT'
        NOT NULL,

    api_return_status
        VARCHAR2(10),

    api_message_count
        NUMBER,

    api_message_text
        CLOB,

    api_processed_date
        DATE,

    created_by
        VARCHAR2(100)
        NOT NULL,

    creation_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_updated_by
        VARCHAR2(100)
        NOT NULL,

    last_update_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_update_login
        VARCHAR2(100),

    record_version_number
        NUMBER
        DEFAULT 1
        NOT NULL,

    CONSTRAINT adre_inv_item_bom_comp_pk
        PRIMARY KEY
        (
            item_bom_comp_id
        ),

    CONSTRAINT adre_inv_item_bom_comp_fk1
        FOREIGN KEY
        (
            item_bom_id
        )
        REFERENCES ops.adre_inv_item_bom
        (
            item_bom_id
        ),

    CONSTRAINT adre_inv_item_bom_comp_ck1
        CHECK
        (
            component_quantity > 0
        ),

    CONSTRAINT adre_inv_item_bom_comp_ck2
        CHECK
        (
            operation_sequence > 0
        ),

    CONSTRAINT adre_inv_item_bom_comp_ck3
        CHECK
        (
            item_sequence IS NULL
            OR item_sequence > 0
        ),

    CONSTRAINT adre_inv_item_bom_comp_ck4
        CHECK
        (
            disable_date IS NULL
            OR effectivity_date IS NULL
            OR disable_date >= effectivity_date
        ),

    CONSTRAINT adre_inv_item_bom_comp_ck5
        CHECK
        (
            component_status IN
            (
                'DRAFT',
                'READY',
                'PROCESSING',
                'PROCESSED',
                'ERROR',
                'SKIPPED'
            )
        ),

    CONSTRAINT adre_inv_item_bom_comp_ck6
        CHECK
        (
            ebs_component_item_id IS NULL
            OR ebs_component_item_id > 0
        ),

    CONSTRAINT adre_inv_item_bom_comp_ck7
        CHECK
        (
            api_message_count IS NULL
            OR api_message_count >= 0
        ),

    CONSTRAINT adre_inv_item_bom_comp_ck8
        CHECK
        (
            record_version_number > 0
        )
);


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Prevent duplicate component definitions for the same BOM using the
-- component item number, operation sequence and item sequence.
--
-- A NULL ITEM_SEQUENCE is normalized to -1 only for uniqueness
-- evaluation.
-- =====================================================================

CREATE UNIQUE INDEX ops.adre_inv_item_bom_comp_u1
    ON ops.adre_inv_item_bom_comp
    (
        item_bom_id,

        UPPER
        (
            TRIM
            (
                component_item_number
            )
        ),

        operation_sequence,

        NVL
        (
            item_sequence,
            -1
        )
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support retrieval of all components associated with one BOM header.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_bom_comp_n1
    ON ops.adre_inv_item_bom_comp
    (
        item_bom_id,
        component_status
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support API processing and monitoring of BOM components by status.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_bom_comp_n2
    ON ops.adre_inv_item_bom_comp
    (
        component_status,
        item_bom_id
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support validation and reconciliation by Oracle EBS component item.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_bom_comp_n3
    ON ops.adre_inv_item_bom_comp
    (
        ebs_component_item_id
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add table documentation.
-- =====================================================================

COMMENT ON TABLE ops.adre_inv_item_bom_comp IS
'Transaction table containing Bill of Material components associated with BOM headers in the Adhesives Research Inventory Item Creation application.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add column documentation.
-- =====================================================================

COMMENT ON COLUMN ops.adre_inv_item_bom_comp.item_bom_comp_id IS
'Surrogate primary key generated by Oracle for each Bill of Material component.';

COMMENT ON COLUMN ops.adre_inv_item_bom_comp.item_bom_id IS
'Foreign key identifying the Bill of Material header that owns the component.';

COMMENT ON COLUMN ops.adre_inv_item_bom_comp.component_item_number IS
'Oracle EBS Inventory Item number of the BOM component.';

COMMENT ON COLUMN ops.adre_inv_item_bom_comp.ebs_component_item_id IS
'Oracle EBS Inventory Item identifier resolved for the BOM component.';

COMMENT ON COLUMN ops.adre_inv_item_bom_comp.component_quantity IS
'Quantity of the component required per assembly.';

COMMENT ON COLUMN ops.adre_inv_item_bom_comp.component_uom_code IS
'Unit of Measure code associated with the BOM component quantity.';

COMMENT ON COLUMN ops.adre_inv_item_bom_comp.operation_sequence IS
'Oracle EBS operation sequence number associated with the BOM component.';

COMMENT ON COLUMN ops.adre_inv_item_bom_comp.item_sequence IS
'Oracle EBS item sequence used to order BOM components within an operation.';

COMMENT ON COLUMN ops.adre_inv_item_bom_comp.effectivity_date IS
'Date from which the BOM component becomes effective.';

COMMENT ON COLUMN ops.adre_inv_item_bom_comp.disable_date IS
'Optional date from which the BOM component is no longer active.';

COMMENT ON COLUMN ops.adre_inv_item_bom_comp.supply_type IS
'Optional Oracle EBS supply type associated with the BOM component.';

COMMENT ON COLUMN ops.adre_inv_item_bom_comp.component_status IS
'Current processing status of the BOM component. Valid values are DRAFT, READY, PROCESSING, PROCESSED, ERROR and SKIPPED.';

COMMENT ON COLUMN ops.adre_inv_item_bom_comp.api_return_status IS
'Return status received from the Oracle EBS BOM component API.';

COMMENT ON COLUMN ops.adre_inv_item_bom_comp.api_message_count IS
'Number of messages returned by the Oracle EBS BOM component API.';

COMMENT ON COLUMN ops.adre_inv_item_bom_comp.api_message_text IS
'Message or error information returned by the Oracle EBS BOM component API.';

COMMENT ON COLUMN ops.adre_inv_item_bom_comp.api_processed_date IS
'Date and time when Oracle EBS API processing completed for the BOM component.';

COMMENT ON COLUMN ops.adre_inv_item_bom_comp.created_by IS
'Application or database user that created the row.';

COMMENT ON COLUMN ops.adre_inv_item_bom_comp.creation_date IS
'Date and time when the row was created.';

COMMENT ON COLUMN ops.adre_inv_item_bom_comp.last_updated_by IS
'Application or database user that last updated the row.';

COMMENT ON COLUMN ops.adre_inv_item_bom_comp.last_update_date IS
'Date and time when the row was last updated.';

COMMENT ON COLUMN ops.adre_inv_item_bom_comp.last_update_login IS
'Oracle APEX session identifier or database login associated with the last update.';

COMMENT ON COLUMN ops.adre_inv_item_bom_comp.record_version_number IS
'Row version number used for change tracking and optimistic locking.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Automatically maintain audit information and normalize Bill of
-- Material component values for ADRE_INV_ITEM_BOM_COMP.
-- =====================================================================

CREATE OR REPLACE TRIGGER ops.adre_inv_item_bom_comp_biu
BEFORE INSERT OR UPDATE
ON ops.adre_inv_item_bom_comp
FOR EACH ROW

DECLARE

    l_user
        VARCHAR2(100);

    l_login
        VARCHAR2(100);

BEGIN

    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX user when available.
    --
    -- Use the current Oracle database user when the operation is
    -- executed outside Oracle APEX.
    -- =================================================================

    l_user :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_USER'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX session identifier when available.
    -- =================================================================

    l_login :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_SESSION'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the BOM component Item Number.
    -- =================================================================

    :NEW.component_item_number :=
        UPPER
        (
            TRIM
            (
                :NEW.component_item_number
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the component Unit of Measure code.
    -- =================================================================

    :NEW.component_uom_code :=
        UPPER
        (
            TRIM
            (
                :NEW.component_uom_code
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the optional component supply type.
    -- =================================================================

    :NEW.supply_type :=
        UPPER
        (
            TRIM
            (
                :NEW.supply_type
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the component processing status.
    -- =================================================================

    :NEW.component_status :=
        UPPER
        (
            TRIM
            (
                :NEW.component_status
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the Oracle EBS API return status when populated.
    -- =================================================================

    :NEW.api_return_status :=
        UPPER
        (
            TRIM
            (
                :NEW.api_return_status
            )
        );


    IF INSERTING THEN

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize creation audit information for a new BOM component.
        -- =============================================================

        :NEW.created_by :=
            NVL
            (
                :NEW.created_by,
                l_user
            );


        :NEW.creation_date :=
            NVL
            (
                :NEW.creation_date,
                SYSDATE
            );


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize the first row version.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :NEW.record_version_number,
                1
            );

    ELSE

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Preserve the original creation audit information.
        -- =============================================================

        :NEW.created_by :=
            :OLD.created_by;

        :NEW.creation_date :=
            :OLD.creation_date;


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Increment the row version number on every update.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :OLD.record_version_number,
                0
            ) + 1;

    END IF;


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Refresh last-update audit information for inserts and updates.
    -- =================================================================

    :NEW.last_updated_by :=
        l_user;

    :NEW.last_update_date :=
        SYSDATE;

    :NEW.last_update_login :=
        l_login;

END;
/

-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the table exists and is VALID.
-- =====================================================================

SELECT
    owner,
    object_name AS table_name,
    status
FROM all_objects
WHERE owner = 'OPS'
  AND object_name = 'ADRE_INV_ITEM_BOM_COMP'
  AND object_type = 'TABLE';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the audit trigger exists and is enabled.
-- =====================================================================

SELECT
    owner,
    trigger_name,
    table_name,
    status
FROM all_triggers
WHERE owner = 'OPS'
  AND trigger_name = 'ADRE_INV_ITEM_BOM_COMP_BIU';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Check for trigger compilation errors.
--
-- A successful trigger compilation must return zero rows.
-- =====================================================================

SELECT
    line,
    position,
    text
FROM all_errors
WHERE owner = 'OPS'
  AND name = 'ADRE_INV_ITEM_BOM_COMP_BIU'
  AND type = 'TRIGGER'
ORDER BY sequence;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the table comment.
-- =====================================================================

SELECT
    table_name,
    comments
FROM all_tab_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_BOM_COMP';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate all column comments.
-- =====================================================================

SELECT
    column_name,
    comments
FROM all_col_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_BOM_COMP'
ORDER BY column_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate constraints created for the BOM component transaction table.
-- =====================================================================

SELECT
    constraint_name,
    constraint_type,
    status,
    r_constraint_name
FROM all_constraints
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_BOM_COMP'
ORDER BY constraint_type,
         constraint_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the unique BOM component index.
-- =====================================================================

SELECT
    owner,
    index_name,
    table_name,
    uniqueness,
    status
FROM all_indexes
WHERE owner = 'OPS'
  AND index_name = 'ADRE_INV_ITEM_BOM_COMP_U1';


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================