
  CREATE TABLE "ADRE_INV_ITEM_ATTR_VALUE" 
   (	"ITEM_ATTR_VALUE_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"REQUEST_ORG_ID" NUMBER NOT NULL ENABLE, 
	"ITEM_ATTRIBUTE_ID" NUMBER NOT NULL ENABLE, 
	"VALUE_UOM_CODE" VARCHAR2(30), 
	"VALUE_STATUS" VARCHAR2(30) DEFAULT 'DRAFT' NOT NULL ENABLE, 
	"API_RETURN_STATUS" VARCHAR2(10), 
	"API_MESSAGE_COUNT" NUMBER, 
	"API_MESSAGE_TEXT" CLOB, 
	"API_PROCESSED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(100) NOT NULL ENABLE, 
	"CREATION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" VARCHAR2(100) NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"LAST_UPDATE_LOGIN" VARCHAR2(100), 
	"RECORD_VERSION_NUMBER" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"ATTRIBUTE_VALUE" VARCHAR2(4000), 
	 CONSTRAINT "ADRE_INV_ITEM_ATTR_VALUE_CK1" CHECK ( 
            value_status IN 
            ( 
                'DRAFT', 
                'READY', 
                'PROCESSING', 
                'PROCESSED', 
                'ERROR', 
                'SKIPPED' 
            ) 
        ) ENABLE, 
	 CONSTRAINT "ADRE_INV_ITEM_ATTR_VALUE_CK3" CHECK ( 
            api_message_count IS NULL 
            OR api_message_count >= 0 
        ) ENABLE, 
	 CONSTRAINT "ADRE_INV_ITEM_ATTR_VALUE_CK4" CHECK ( 
            record_version_number > 0 
        ) ENABLE, 
	 CONSTRAINT "ADRE_INV_ITEM_ATTR_VALUE_PK" PRIMARY KEY ("ITEM_ATTR_VALUE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "ADRE_INV_ITEM_ATTR_VALUE_U1" UNIQUE ("REQUEST_ORG_ID", "ITEM_ATTRIBUTE_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "ADRE_INV_ITEM_ATTR_VALUE" ADD CONSTRAINT "ADRE_INV_ITEM_ATTR_VALUE_FK1" FOREIGN KEY ("REQUEST_ORG_ID")
	  REFERENCES "ADRE_INV_ITEM_REQUEST_ORG" ("REQUEST_ORG_ID") ENABLE;
  ALTER TABLE "ADRE_INV_ITEM_ATTR_VALUE" ADD CONSTRAINT "ADRE_INV_ITEM_ATTR_VALUE_FK2" FOREIGN KEY ("ITEM_ATTRIBUTE_ID")
	  REFERENCES "ADRE_INV_ITEM_ATTRIBUTE" ("ITEM_ATTRIBUTE_ID") ENABLE;

  CREATE INDEX "ADRE_INV_ITEM_ATTR_VALUE_N1" ON "ADRE_INV_ITEM_ATTR_VALUE" ("REQUEST_ORG_ID", "VALUE_STATUS") 
  ;

  CREATE INDEX "ADRE_INV_ITEM_ATTR_VALUE_N2" ON "ADRE_INV_ITEM_ATTR_VALUE" ("ITEM_ATTRIBUTE_ID", "VALUE_STATUS") 
  ;

  CREATE INDEX "ADRE_INV_ITEM_ATTR_VALUE_N3" ON "ADRE_INV_ITEM_ATTR_VALUE" ("VALUE_STATUS", "REQUEST_ORG_ID") 
  ;

   COMMENT ON COLUMN "ADRE_INV_ITEM_ATTR_VALUE"."ITEM_ATTR_VALUE_ID" IS 'Surrogate primary key generated by Oracle for each transactional Item Attribute value.';
   COMMENT ON COLUMN "ADRE_INV_ITEM_ATTR_VALUE"."REQUEST_ORG_ID" IS 'Foreign key identifying the Item Request organization to which the attribute value applies.';
   COMMENT ON COLUMN "ADRE_INV_ITEM_ATTR_VALUE"."ITEM_ATTRIBUTE_ID" IS 'Foreign key identifying the configurable Item Attribute whose transactional value is stored.';
   COMMENT ON COLUMN "ADRE_INV_ITEM_ATTR_VALUE"."VALUE_UOM_CODE" IS 'Optional Unit of Measure code associated with the transactional attribute value. This allows the Unit of Measure to vary by organization.';
   COMMENT ON COLUMN "ADRE_INV_ITEM_ATTR_VALUE"."VALUE_STATUS" IS 'Current processing status of the attribute value. Valid values are DRAFT, READY, PROCESSING, PROCESSED, ERROR and SKIPPED.';
   COMMENT ON COLUMN "ADRE_INV_ITEM_ATTR_VALUE"."API_RETURN_STATUS" IS 'Return status received from the Oracle EBS or integration API for this attribute value.';
   COMMENT ON COLUMN "ADRE_INV_ITEM_ATTR_VALUE"."API_MESSAGE_COUNT" IS 'Number of messages returned by the Oracle EBS or integration API for this attribute value.';
   COMMENT ON COLUMN "ADRE_INV_ITEM_ATTR_VALUE"."API_MESSAGE_TEXT" IS 'Message or error information returned by the Oracle EBS or integration API for this attribute value.';
   COMMENT ON COLUMN "ADRE_INV_ITEM_ATTR_VALUE"."API_PROCESSED_DATE" IS 'Date and time when API processing completed for this attribute value.';
   COMMENT ON COLUMN "ADRE_INV_ITEM_ATTR_VALUE"."CREATED_BY" IS 'Application or database user that created the row.';
   COMMENT ON COLUMN "ADRE_INV_ITEM_ATTR_VALUE"."CREATION_DATE" IS 'Date and time when the row was created.';
   COMMENT ON COLUMN "ADRE_INV_ITEM_ATTR_VALUE"."LAST_UPDATED_BY" IS 'Application or database user that last updated the row.';
   COMMENT ON COLUMN "ADRE_INV_ITEM_ATTR_VALUE"."LAST_UPDATE_DATE" IS 'Date and time when the row was last updated.';
   COMMENT ON COLUMN "ADRE_INV_ITEM_ATTR_VALUE"."LAST_UPDATE_LOGIN" IS 'Oracle APEX session identifier or database login associated with the last update.';
   COMMENT ON COLUMN "ADRE_INV_ITEM_ATTR_VALUE"."RECORD_VERSION_NUMBER" IS 'Row version number used for change tracking and optimistic locking.';
   COMMENT ON TABLE "ADRE_INV_ITEM_ATTR_VALUE"  IS 'Transaction table containing actual configurable Item Attribute values entered for each Item Request organization in the Adhesives Research Inventory Item Creation application.';

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADRE_INV_ITEM_ATTR_VALUE_BIU" 
BEFORE INSERT OR UPDATE
ON OPS.ADRE_INV_ITEM_ATTR_VALUE
FOR EACH ROW
DECLARE
    L_USER
        VARCHAR2(100);
    L_LOGIN
        VARCHAR2(100);
BEGIN
    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX user when available.
    --
    -- Use the current Oracle database user when the operation is
    -- executed outside Oracle APEX.
    -- =================================================================
    L_USER :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_USER'
            ),
            USER
        );
    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX session identifier when available.
    -- =================================================================
    L_LOGIN :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_SESSION'
            ),
            USER
        );
    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the processing status.
    -- =================================================================
    :NEW.VALUE_STATUS :=
        UPPER
        (
            TRIM
            (
                :NEW.VALUE_STATUS
            )
        );
    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the Unit of Measure code when populated.
    --
    -- Example:
    -- inch
    --
    -- becomes:
    -- INCH
    -- =================================================================
    :NEW.VALUE_UOM_CODE :=
        UPPER
        (
            TRIM
            (
                :NEW.VALUE_UOM_CODE
            )
        );
    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Remove unnecessary leading and trailing spaces from character
    -- attribute values.
    --
    -- Oracle automatically treats an empty VARCHAR2 string as NULL.
    -- =================================================================
    :NEW.ATTRIBUTE_CHAR_VALUE :=
        TRIM
        (
            :NEW.ATTRIBUTE_CHAR_VALUE
        );
    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the Oracle EBS API return status when populated.
    -- =================================================================
    :NEW.API_RETURN_STATUS :=
        UPPER
        (
            TRIM
            (
                :NEW.API_RETURN_STATUS
            )
        );
    IF INSERTING THEN
        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize creation audit information for a new transactional
        -- attribute value.
        -- =============================================================
        :NEW.CREATED_BY :=
            NVL
            (
                :NEW.CREATED_BY,
                L_USER
            );
        :NEW.CREATION_DATE :=
            NVL
            (
                :NEW.CREATION_DATE,
                SYSDATE
            );
        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize the first row version.
        -- =============================================================
        :NEW.RECORD_VERSION_NUMBER :=
            NVL
            (
                :NEW.RECORD_VERSION_NUMBER,
                1
            );
    ELSE
        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Preserve the original creation audit information.
        -- =============================================================
        :NEW.CREATED_BY :=
            :OLD.CREATED_BY;
        :NEW.CREATION_DATE :=
            :OLD.CREATION_DATE;
        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Increment the row version number on every update.
        -- =============================================================
        :NEW.RECORD_VERSION_NUMBER :=
            NVL
            (
                :OLD.RECORD_VERSION_NUMBER,
                0
            ) + 1;
    END IF;
    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Refresh last-update audit information for inserts and updates.
    -- =================================================================
    :NEW.LAST_UPDATED_BY :=
        L_USER;
    :NEW.LAST_UPDATE_DATE :=
        SYSDATE;
    :NEW.LAST_UPDATE_LOGIN :=
        L_LOGIN;
END;

/
ALTER TRIGGER "ADRE_INV_ITEM_ATTR_VALUE_BIU" ENABLE;