-- 2026-09-07 - JCALZADILLA - Create the configuration-driven Item Type to approved EBS UOM mapping.

CREATE TABLE ops.adre_inv_item_type_uom
(
    item_type_uom_id      NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    item_type_id          NUMBER                      NOT NULL,
    uom_code              VARCHAR2(30 BYTE)           NOT NULL,
    active_flag           VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL,
    display_sequence      NUMBER           DEFAULT 10  NOT NULL,
    created_by            VARCHAR2(100 BYTE),
    creation_date         DATE             DEFAULT SYSDATE NOT NULL,
    last_updated_by       VARCHAR2(100 BYTE),
    last_update_date      DATE             DEFAULT SYSDATE NOT NULL,
    last_update_login     VARCHAR2(100 BYTE),
    record_version_number NUMBER           DEFAULT 1 NOT NULL,

    CONSTRAINT adre_inv_item_type_uom_pk
        PRIMARY KEY (item_type_uom_id),

    CONSTRAINT adre_inv_item_type_uom_u1
        UNIQUE (item_type_id, uom_code),

    CONSTRAINT adre_inv_item_type_uom_f1
        FOREIGN KEY (item_type_id)
        REFERENCES ops.adre_inv_item_type (item_type_id),

    CONSTRAINT adre_inv_item_type_uom_c1
        CHECK (active_flag IN ('Y', 'N')),

    CONSTRAINT adre_inv_item_type_uom_c2
        CHECK (display_sequence >= 0),

    CONSTRAINT adre_inv_item_type_uom_c3
        CHECK (record_version_number >= 1)
);

COMMENT ON TABLE ops.adre_inv_item_type_uom IS
    'Configuration table defining the approved Oracle EBS Units of Measure available for each Adhesives Research Item Type.';

COMMENT ON COLUMN ops.adre_inv_item_type_uom.item_type_uom_id IS
    'Surrogate primary key generated for each Item Type to Unit of Measure mapping.';

COMMENT ON COLUMN ops.adre_inv_item_type_uom.item_type_id IS
    'Foreign key identifying the application Item Type for which the Unit of Measure is approved.';

COMMENT ON COLUMN ops.adre_inv_item_type_uom.uom_code IS
    'Oracle EBS Unit of Measure code returned to APEX and stored in request staging.';

COMMENT ON COLUMN ops.adre_inv_item_type_uom.active_flag IS
    'Indicates whether the Item Type to Unit of Measure mapping is available for selection. Valid values are Y and N.';

COMMENT ON COLUMN ops.adre_inv_item_type_uom.display_sequence IS
    'Controls the display order of approved Units of Measure for the Item Type.';

COMMENT ON COLUMN ops.adre_inv_item_type_uom.created_by IS
    'Application or database user that created the configuration row.';

COMMENT ON COLUMN ops.adre_inv_item_type_uom.creation_date IS
    'Date and time when the configuration row was created.';

COMMENT ON COLUMN ops.adre_inv_item_type_uom.last_updated_by IS
    'Application or database user that last updated the configuration row.';

COMMENT ON COLUMN ops.adre_inv_item_type_uom.last_update_date IS
    'Date and time when the configuration row was last updated.';

COMMENT ON COLUMN ops.adre_inv_item_type_uom.last_update_login IS
    'Oracle APEX session identifier or database login associated with the last update.';

COMMENT ON COLUMN ops.adre_inv_item_type_uom.record_version_number IS
    'Row version number used for change tracking and optimistic locking.';
