-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Recreate the Bill of Material header transaction table for the final
-- Adhesives Research Inventory Item Creation application.
--
-- One row represents one BOM header associated with one Item Request
-- organization.
--
-- REQUEST_ORG_ID identifies the organization where the BOM applies.
--
-- ALTERNATE_BOM_DESIGNATOR is optional.
-- A NULL value represents the Primary BOM.
--
-- EBS_BILL_SEQUENCE_ID stores the Oracle EBS Bill Sequence identifier
-- after the BOM has been created or resolved in Oracle EBS.
--
-- BOM components will be stored separately in
-- ADRE_INV_ITEM_BOM_COMP.
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Drop the existing table when it already exists.
--
-- CASCADE CONSTRAINTS removes foreign key references from previously
-- created dependent application objects during the schema rebuild.
--
-- ORA-00942 is ignored because it means the table does not exist.
-- Any other Oracle error is raised normally.
-- =====================================================================

BEGIN
    EXECUTE IMMEDIATE
        'DROP TABLE ops.adre_inv_item_bom CASCADE CONSTRAINTS PURGE';

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Create the Bill of Material header transaction table.
-- =====================================================================

CREATE TABLE ops.adre_inv_item_bom
(
    item_bom_id
        NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        NOT NULL,

    request_org_id
        NUMBER
        NOT NULL,

    alternate_bom_designator
        VARCHAR2(30),

    bom_description
        VARCHAR2(500),

    effectivity_date
        DATE,

    ebs_bill_sequence_id
        NUMBER,

    bom_status
        VARCHAR2(30)
        DEFAULT 'DRAFT'
        NOT NULL,

    api_return_status
        VARCHAR2(10),

    api_message_count
        NUMBER,

    api_message_text
        CLOB,

    api_processed_date
        DATE,

    created_by
        VARCHAR2(100)
        NOT NULL,

    creation_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_updated_by
        VARCHAR2(100)
        NOT NULL,

    last_update_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_update_login
        VARCHAR2(100),

    record_version_number
        NUMBER
        DEFAULT 1
        NOT NULL,

    CONSTRAINT adre_inv_item_bom_pk
        PRIMARY KEY
        (
            item_bom_id
        ),

    CONSTRAINT adre_inv_item_bom_fk1
        FOREIGN KEY
        (
            request_org_id
        )
        REFERENCES ops.adre_inv_item_request_org
        (
            request_org_id
        ),

    CONSTRAINT adre_inv_item_bom_ck1
        CHECK
        (
            bom_status IN
            (
                'DRAFT',
                'READY',
                'PROCESSING',
                'PROCESSED',
                'ERROR',
                'SKIPPED'
            )
        ),

    CONSTRAINT adre_inv_item_bom_ck2
        CHECK
        (
            ebs_bill_sequence_id IS NULL
            OR ebs_bill_sequence_id > 0
        ),

    CONSTRAINT adre_inv_item_bom_ck3
        CHECK
        (
            api_message_count IS NULL
            OR api_message_count >= 0
        ),

    CONSTRAINT adre_inv_item_bom_ck4
        CHECK
        (
            record_version_number > 0
        )
);


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Prevent duplicate BOM headers for the same Item Request organization.
--
-- A NULL ALTERNATE_BOM_DESIGNATOR represents the Primary BOM.
--
-- NVL is used so only one Primary BOM can exist for a REQUEST_ORG_ID.
--
-- Multiple alternate BOMs are allowed as long as each alternate
-- designator is unique for the Item Request organization.
-- =====================================================================

CREATE UNIQUE INDEX ops.adre_inv_item_bom_u1
    ON ops.adre_inv_item_bom
    (
        request_org_id,

        NVL
        (
            UPPER
            (
                TRIM
                (
                    alternate_bom_designator
                )
            ),
            '~PRIMARY~'
        )
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support retrieval of BOM headers associated with one Item Request
-- organization and filtering by processing status.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_bom_n1
    ON ops.adre_inv_item_bom
    (
        request_org_id,
        bom_status
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support API processing and monitoring of BOM headers by status.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_bom_n2
    ON ops.adre_inv_item_bom
    (
        bom_status,
        request_org_id
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support reconciliation and lookup of BOMs by the Oracle EBS Bill
-- Sequence identifier.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_bom_n3
    ON ops.adre_inv_item_bom
    (
        ebs_bill_sequence_id
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add table documentation.
-- =====================================================================

COMMENT ON TABLE ops.adre_inv_item_bom IS
'Transaction table containing Bill of Material headers associated with each Item Request organization in the Adhesives Research Inventory Item Creation application.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add column documentation.
-- =====================================================================

COMMENT ON COLUMN ops.adre_inv_item_bom.item_bom_id IS
'Surrogate primary key generated by Oracle for each Bill of Material header.';

COMMENT ON COLUMN ops.adre_inv_item_bom.request_org_id IS
'Foreign key identifying the Item Request organization to which the Bill of Material applies.';

COMMENT ON COLUMN ops.adre_inv_item_bom.alternate_bom_designator IS
'Optional Oracle EBS alternate BOM designator. NULL represents the Primary BOM.';

COMMENT ON COLUMN ops.adre_inv_item_bom.bom_description IS
'Business description of the Bill of Material.';

COMMENT ON COLUMN ops.adre_inv_item_bom.effectivity_date IS
'Date from which the Bill of Material becomes effective.';

COMMENT ON COLUMN ops.adre_inv_item_bom.ebs_bill_sequence_id IS
'Oracle EBS Bill Sequence identifier returned or resolved after BOM processing.';

COMMENT ON COLUMN ops.adre_inv_item_bom.bom_status IS
'Current processing status of the BOM header. Valid values are DRAFT, READY, PROCESSING, PROCESSED, ERROR and SKIPPED.';

COMMENT ON COLUMN ops.adre_inv_item_bom.api_return_status IS
'Return status received from the Oracle EBS BOM API.';

COMMENT ON COLUMN ops.adre_inv_item_bom.api_message_count IS
'Number of messages returned by the Oracle EBS BOM API.';

COMMENT ON COLUMN ops.adre_inv_item_bom.api_message_text IS
'Message or error information returned by the Oracle EBS BOM API.';

COMMENT ON COLUMN ops.adre_inv_item_bom.api_processed_date IS
'Date and time when Oracle EBS API processing completed for the BOM header.';

COMMENT ON COLUMN ops.adre_inv_item_bom.created_by IS
'Application or database user that created the row.';

COMMENT ON COLUMN ops.adre_inv_item_bom.creation_date IS
'Date and time when the row was created.';

COMMENT ON COLUMN ops.adre_inv_item_bom.last_updated_by IS
'Application or database user that last updated the row.';

COMMENT ON COLUMN ops.adre_inv_item_bom.last_update_date IS
'Date and time when the row was last updated.';

COMMENT ON COLUMN ops.adre_inv_item_bom.last_update_login IS
'Oracle APEX session identifier or database login associated with the last update.';

COMMENT ON COLUMN ops.adre_inv_item_bom.record_version_number IS
'Row version number used for change tracking and optimistic locking.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Automatically maintain audit information and normalize Bill of
-- Material header values for ADRE_INV_ITEM_BOM.
-- =====================================================================

CREATE OR REPLACE TRIGGER ops.adre_inv_item_bom_biu
BEFORE INSERT OR UPDATE
ON ops.adre_inv_item_bom
FOR EACH ROW

DECLARE

    l_user
        VARCHAR2(100);

    l_login
        VARCHAR2(100);

BEGIN

    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX user when available.
    --
    -- Use the current Oracle database user when the operation is
    -- executed outside Oracle APEX.
    -- =================================================================

    l_user :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_USER'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX session identifier when available.
    -- =================================================================

    l_login :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_SESSION'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the Alternate BOM Designator.
    --
    -- Example:
    -- test
    --
    -- becomes:
    -- TEST
    --
    -- A blank value is stored as NULL by Oracle and therefore
    -- represents the Primary BOM.
    -- =================================================================

    :NEW.alternate_bom_designator :=
        UPPER
        (
            TRIM
            (
                :NEW.alternate_bom_designator
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Remove unnecessary leading and trailing spaces from the BOM
    -- description.
    -- =================================================================

    :NEW.bom_description :=
        TRIM
        (
            :NEW.bom_description
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the BOM processing status.
    -- =================================================================

    :NEW.bom_status :=
        UPPER
        (
            TRIM
            (
                :NEW.bom_status
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the Oracle EBS API return status when populated.
    -- =================================================================

    :NEW.api_return_status :=
        UPPER
        (
            TRIM
            (
                :NEW.api_return_status
            )
        );


    IF INSERTING THEN

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize creation audit information for a new BOM header.
        -- =============================================================

        :NEW.created_by :=
            NVL
            (
                :NEW.created_by,
                l_user
            );


        :NEW.creation_date :=
            NVL
            (
                :NEW.creation_date,
                SYSDATE
            );


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize the first row version.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :NEW.record_version_number,
                1
            );

    ELSE

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Preserve the original creation audit information.
        -- =============================================================

        :NEW.created_by :=
            :OLD.created_by;

        :NEW.creation_date :=
            :OLD.creation_date;


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Increment the row version number on every update.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :OLD.record_version_number,
                0
            ) + 1;

    END IF;


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Refresh last-update audit information for inserts and updates.
    -- =================================================================

    :NEW.last_updated_by :=
        l_user;

    :NEW.last_update_date :=
        SYSDATE;

    :NEW.last_update_login :=
        l_login;

END;
/

-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the table exists and is VALID.
--
-- ALL_OBJECTS uses OBJECT_NAME for the object identifier.
-- =====================================================================

SELECT
    owner,
    object_name AS table_name,
    status
FROM all_objects
WHERE owner = 'OPS'
  AND object_name = 'ADRE_INV_ITEM_BOM'
  AND object_type = 'TABLE';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the audit trigger exists and is enabled.
-- =====================================================================

SELECT
    owner,
    trigger_name,
    table_name,
    status
FROM all_triggers
WHERE owner = 'OPS'
  AND trigger_name = 'ADRE_INV_ITEM_BOM_BIU';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Check for trigger compilation errors.
--
-- A successful trigger compilation must return zero rows.
-- =====================================================================

SELECT
    line,
    position,
    text
FROM all_errors
WHERE owner = 'OPS'
  AND name = 'ADRE_INV_ITEM_BOM_BIU'
  AND type = 'TRIGGER'
ORDER BY sequence;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the table comment.
-- =====================================================================

SELECT
    table_name,
    comments
FROM all_tab_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_BOM';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate all column comments.
-- =====================================================================

SELECT
    column_name,
    comments
FROM all_col_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_BOM'
ORDER BY column_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate constraints created for the Bill of Material header table.
-- =====================================================================

SELECT
    constraint_name,
    constraint_type,
    status,
    r_constraint_name
FROM all_constraints
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_BOM'
ORDER BY constraint_type,
         constraint_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the unique index used to prevent duplicate Primary or
-- Alternate BOM headers for the same Item Request organization.
-- =====================================================================

SELECT
    owner,
    index_name,
    table_name,
    uniqueness,
    status
FROM all_indexes
WHERE owner = 'OPS'
  AND index_name = 'ADRE_INV_ITEM_BOM_U1';


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================