-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Recreate the Item Document transaction table for the final
-- Adhesives Research Inventory Item Creation application.
--
-- This table stores documents and file attachments associated with an
-- Item Request organization.
--
-- One row represents one document attachment.
--
-- REQUEST_ORG_ID identifies the Item Request organization to which the
-- document belongs.
--
-- FILE_BLOB stores the actual binary file content.
--
-- FILE_NAME, MIME_TYPE and FILE_CHARSET store the file metadata used by
-- Oracle APEX for upload and download operations.
--
-- Documents can remain in DRAFT status while the Item Request is being
-- prepared.
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Drop the existing table when it already exists.
--
-- CASCADE CONSTRAINTS removes foreign key references from previously
-- created dependent application objects during the schema rebuild.
--
-- ORA-00942 is ignored because it means the table does not exist.
-- Any other Oracle error is raised normally.
-- =====================================================================

BEGIN
    EXECUTE IMMEDIATE
        'DROP TABLE ops.adre_inv_item_document CASCADE CONSTRAINTS PURGE';

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Create the Item Document transaction table.
-- =====================================================================

CREATE TABLE ops.adre_inv_item_document
(
    item_document_id
        NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        NOT NULL,

    request_org_id
        NUMBER
        NOT NULL,

    document_type
        VARCHAR2(100),

    document_title
        VARCHAR2(240)
        NOT NULL,

    document_description
        VARCHAR2(2000),

    file_name
        VARCHAR2(500),

    mime_type
        VARCHAR2(255),

    file_charset
        VARCHAR2(100),

    file_blob
        BLOB,

    document_status
        VARCHAR2(30)
        DEFAULT 'DRAFT'
        NOT NULL,

    api_return_status
        VARCHAR2(10),

    api_message_count
        NUMBER,

    api_message_text
        CLOB,

    api_processed_date
        DATE,

    created_by
        VARCHAR2(100)
        NOT NULL,

    creation_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_updated_by
        VARCHAR2(100)
        NOT NULL,

    last_update_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_update_login
        VARCHAR2(100),

    record_version_number
        NUMBER
        DEFAULT 1
        NOT NULL,

    CONSTRAINT adre_inv_item_document_pk
        PRIMARY KEY
        (
            item_document_id
        ),

    CONSTRAINT adre_inv_item_document_fk1
        FOREIGN KEY
        (
            request_org_id
        )
        REFERENCES ops.adre_inv_item_request_org
        (
            request_org_id
        ),

    CONSTRAINT adre_inv_item_document_ck1
        CHECK
        (
            document_status IN
            (
                'DRAFT',
                'READY',
                'PROCESSING',
                'PROCESSED',
                'ERROR',
                'SKIPPED'
            )
        ),

    CONSTRAINT adre_inv_item_document_ck2
        CHECK
        (
            api_message_count IS NULL
            OR api_message_count >= 0
        ),

    CONSTRAINT adre_inv_item_document_ck3
        CHECK
        (
            record_version_number > 0
        )
);


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support retrieval of all documents associated with an Item Request
-- organization and filtering by processing status.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_document_n1
    ON ops.adre_inv_item_document
    (
        request_org_id,
        document_status
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support filtering and reporting documents by document type.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_document_n2
    ON ops.adre_inv_item_document
    (
        document_type,
        request_org_id
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support API processing and monitoring of documents by status.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_document_n3
    ON ops.adre_inv_item_document
    (
        document_status,
        request_org_id
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add table documentation.
-- =====================================================================

COMMENT ON TABLE ops.adre_inv_item_document IS
'Transaction table containing documents and file attachments associated with each Item Request organization in the Adhesives Research Inventory Item Creation application.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add column documentation.
-- =====================================================================

COMMENT ON COLUMN ops.adre_inv_item_document.item_document_id IS
'Surrogate primary key generated by Oracle for each document transaction.';

COMMENT ON COLUMN ops.adre_inv_item_document.request_org_id IS
'Foreign key identifying the Item Request organization to which the document belongs.';

COMMENT ON COLUMN ops.adre_inv_item_document.document_type IS
'Business document type used to classify the attachment.';

COMMENT ON COLUMN ops.adre_inv_item_document.document_title IS
'User-facing title of the document displayed in Oracle APEX.';

COMMENT ON COLUMN ops.adre_inv_item_document.document_description IS
'Optional business description of the document.';

COMMENT ON COLUMN ops.adre_inv_item_document.file_name IS
'Original uploaded file name.';

COMMENT ON COLUMN ops.adre_inv_item_document.mime_type IS
'MIME type of the uploaded file.';

COMMENT ON COLUMN ops.adre_inv_item_document.file_charset IS
'Character set of the uploaded file when applicable.';

COMMENT ON COLUMN ops.adre_inv_item_document.file_blob IS
'Binary content of the uploaded document stored in Oracle.';

COMMENT ON COLUMN ops.adre_inv_item_document.document_status IS
'Current processing status of the document. Valid values are DRAFT, READY, PROCESSING, PROCESSED, ERROR and SKIPPED.';

COMMENT ON COLUMN ops.adre_inv_item_document.api_return_status IS
'Return status received from the Oracle EBS or document integration API.';

COMMENT ON COLUMN ops.adre_inv_item_document.api_message_count IS
'Number of messages returned by the Oracle EBS or document integration API.';

COMMENT ON COLUMN ops.adre_inv_item_document.api_message_text IS
'Message or error information returned by the Oracle EBS or document integration API.';

COMMENT ON COLUMN ops.adre_inv_item_document.api_processed_date IS
'Date and time when API processing completed for the document.';

COMMENT ON COLUMN ops.adre_inv_item_document.created_by IS
'Application or database user that created the row.';

COMMENT ON COLUMN ops.adre_inv_item_document.creation_date IS
'Date and time when the row was created.';

COMMENT ON COLUMN ops.adre_inv_item_document.last_updated_by IS
'Application or database user that last updated the row.';

COMMENT ON COLUMN ops.adre_inv_item_document.last_update_date IS
'Date and time when the row was last updated.';

COMMENT ON COLUMN ops.adre_inv_item_document.last_update_login IS
'Oracle APEX session identifier or database login associated with the last update.';

COMMENT ON COLUMN ops.adre_inv_item_document.record_version_number IS
'Row version number used for change tracking and optimistic locking.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Automatically maintain audit information and normalize document
-- transaction values for ADRE_INV_ITEM_DOCUMENT.
-- =====================================================================

CREATE OR REPLACE TRIGGER ops.adre_inv_item_document_biu
BEFORE INSERT OR UPDATE
ON ops.adre_inv_item_document
FOR EACH ROW

DECLARE

    l_user
        VARCHAR2(100);

    l_login
        VARCHAR2(100);

BEGIN

    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX user when available.
    --
    -- Use the current Oracle database user when the operation is
    -- executed outside Oracle APEX.
    -- =================================================================

    l_user :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_USER'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX session identifier when available.
    -- =================================================================

    l_login :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_SESSION'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the document processing status.
    -- =================================================================

    :NEW.document_status :=
        UPPER
        (
            TRIM
            (
                :NEW.document_status
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Remove unnecessary leading and trailing spaces from document
    -- metadata.
    -- =================================================================

    :NEW.document_type :=
        TRIM
        (
            :NEW.document_type
        );


    :NEW.document_title :=
        TRIM
        (
            :NEW.document_title
        );


    :NEW.file_name :=
        TRIM
        (
            :NEW.file_name
        );


    :NEW.mime_type :=
        TRIM
        (
            :NEW.mime_type
        );


    :NEW.file_charset :=
        TRIM
        (
            :NEW.file_charset
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the Oracle EBS or integration API return status when
    -- populated.
    -- =================================================================

    :NEW.api_return_status :=
        UPPER
        (
            TRIM
            (
                :NEW.api_return_status
            )
        );


    IF INSERTING THEN

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize creation audit information for a new document.
        -- =============================================================

        :NEW.created_by :=
            NVL
            (
                :NEW.created_by,
                l_user
            );


        :NEW.creation_date :=
            NVL
            (
                :NEW.creation_date,
                SYSDATE
            );


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize the first row version.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :NEW.record_version_number,
                1
            );

    ELSE

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Preserve the original creation audit information.
        -- =============================================================

        :NEW.created_by :=
            :OLD.created_by;

        :NEW.creation_date :=
            :OLD.creation_date;


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Increment the row version number on every update.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :OLD.record_version_number,
                0
            ) + 1;

    END IF;


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Refresh last-update audit information for inserts and updates.
    -- =================================================================

    :NEW.last_updated_by :=
        l_user;

    :NEW.last_update_date :=
        SYSDATE;

    :NEW.last_update_login :=
        l_login;

END;
/

-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the table exists and is VALID.
--
-- ALL_OBJECTS uses OBJECT_NAME for the object identifier.
-- =====================================================================

SELECT
    owner,
    object_name AS table_name,
    status
FROM all_objects
WHERE owner = 'OPS'
  AND object_name = 'ADRE_INV_ITEM_DOCUMENT'
  AND object_type = 'TABLE';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the audit trigger exists and is enabled.
-- =====================================================================

SELECT
    owner,
    trigger_name,
    table_name,
    status
FROM all_triggers
WHERE owner = 'OPS'
  AND trigger_name = 'ADRE_INV_ITEM_DOCUMENT_BIU';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Check for trigger compilation errors.
--
-- A successful trigger compilation must return zero rows.
-- =====================================================================

SELECT
    line,
    position,
    text
FROM all_errors
WHERE owner = 'OPS'
  AND name = 'ADRE_INV_ITEM_DOCUMENT_BIU'
  AND type = 'TRIGGER'
ORDER BY sequence;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the table comment.
-- =====================================================================

SELECT
    table_name,
    comments
FROM all_tab_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_DOCUMENT';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate all column comments.
-- =====================================================================

SELECT
    column_name,
    comments
FROM all_col_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_DOCUMENT'
ORDER BY column_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the constraints created for the Document transaction table.
-- =====================================================================

SELECT
    constraint_name,
    constraint_type,
    status,
    r_constraint_name
FROM all_constraints
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_DOCUMENT'
ORDER BY constraint_type,
         constraint_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================