-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Recreate the configurable Item Attribute definition table for the
-- final Adhesives Research Inventory Item Creation application.
--
-- This table defines the dynamic attributes that can appear inside the
-- Organization Details sections in Oracle APEX.
--
-- Examples include:
--   - Coater
--   - RLDH
--   - Coat Weight
--   - Width
--   - Length
--   - Lead Time Days
--   - Planning Method
--
-- ITEM_SECTION_ID identifies the Details section where the attribute
-- belongs.
--
-- ATTRIBUTE_DATA_TYPE determines how Oracle APEX renders and validates
-- the value.
--
-- Valid data types:
--   CHAR
--   NUMBER
--   DATE
--   YES_NO
--
-- EBS_ATTRIBUTE_NAME and EBS_ATTRIBUTE_GROUP provide configurable
-- mapping information for the Oracle EBS integration.
--
-- This table stores metadata only.
-- User-entered transactional values will be stored separately.
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Drop the existing table when it already exists.
--
-- CASCADE CONSTRAINTS removes foreign key references from previously
-- created dependent application objects during the schema rebuild.
--
-- ORA-00942 is ignored because it means the table does not exist.
-- Any other Oracle error is raised normally.
-- =====================================================================

BEGIN
    EXECUTE IMMEDIATE
        'DROP TABLE ops.adre_inv_item_attribute CASCADE CONSTRAINTS PURGE';

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Create the configurable Item Attribute definition table.
-- =====================================================================

CREATE TABLE ops.adre_inv_item_attribute
(
    item_attribute_id
        NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        NOT NULL,

    item_section_id
        NUMBER
        NOT NULL,

    attribute_code
        VARCHAR2(100)
        NOT NULL,

    attribute_name
        VARCHAR2(240)
        NOT NULL,

    attribute_data_type
        VARCHAR2(30)
        NOT NULL,

    description
        VARCHAR2(1000),

    default_value
        VARCHAR2(1000),

    unit_of_measure
        VARCHAR2(30),

    required_flag
        VARCHAR2(1)
        DEFAULT 'N'
        NOT NULL,

    active_flag
        VARCHAR2(1)
        DEFAULT 'Y'
        NOT NULL,

    display_sequence
        NUMBER
        DEFAULT 10
        NOT NULL,

    ebs_attribute_name
        VARCHAR2(240),

    ebs_attribute_group
        VARCHAR2(240),

    created_by
        VARCHAR2(100)
        NOT NULL,

    creation_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_updated_by
        VARCHAR2(100)
        NOT NULL,

    last_update_date
        DATE
        DEFAULT SYSDATE
        NOT NULL,

    last_update_login
        VARCHAR2(100),

    record_version_number
        NUMBER
        DEFAULT 1
        NOT NULL,

    CONSTRAINT adre_inv_item_attribute_pk
        PRIMARY KEY
        (
            item_attribute_id
        ),

    CONSTRAINT adre_inv_item_attribute_fk1
        FOREIGN KEY
        (
            item_section_id
        )
        REFERENCES ops.adre_inv_item_section
        (
            item_section_id
        ),

    CONSTRAINT adre_inv_item_attribute_u1
        UNIQUE
        (
            attribute_code
        ),

    CONSTRAINT adre_inv_item_attribute_ck1
        CHECK
        (
            attribute_data_type IN
            (
                'CHAR',
                'NUMBER',
                'DATE',
                'YES_NO'
            )
        ),

    CONSTRAINT adre_inv_item_attribute_ck2
        CHECK
        (
            required_flag IN
            (
                'Y',
                'N'
            )
        ),

    CONSTRAINT adre_inv_item_attribute_ck3
        CHECK
        (
            active_flag IN
            (
                'Y',
                'N'
            )
        ),

    CONSTRAINT adre_inv_item_attribute_ck4
        CHECK
        (
            display_sequence > 0
        ),

    CONSTRAINT adre_inv_item_attribute_ck5
        CHECK
        (
            record_version_number > 0
        )
);


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support Oracle APEX retrieval of active attributes for a Details
-- section in the configured display sequence.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_attribute_n1
    ON ops.adre_inv_item_attribute
    (
        item_section_id,
        active_flag,
        display_sequence
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support retrieval of configurable attributes by Oracle EBS logical
-- attribute group.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_attribute_n2
    ON ops.adre_inv_item_attribute
    (
        ebs_attribute_group,
        active_flag
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Support retrieval and validation by attribute data type.
-- =====================================================================

CREATE INDEX ops.adre_inv_item_attribute_n3
    ON ops.adre_inv_item_attribute
    (
        attribute_data_type,
        active_flag
    );


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add table documentation.
-- =====================================================================

COMMENT ON TABLE ops.adre_inv_item_attribute IS
'Configuration table defining dynamic Item Attributes displayed inside Organization Details sections in the Adhesives Research Inventory Item Creation application.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Add column documentation.
-- =====================================================================

COMMENT ON COLUMN ops.adre_inv_item_attribute.item_attribute_id IS
'Surrogate primary key generated by Oracle for each configurable Item Attribute.';

COMMENT ON COLUMN ops.adre_inv_item_attribute.item_section_id IS
'Foreign key identifying the Organization Details section where the attribute is displayed.';

COMMENT ON COLUMN ops.adre_inv_item_attribute.attribute_code IS
'Unique internal application code used to identify the configurable attribute.';

COMMENT ON COLUMN ops.adre_inv_item_attribute.attribute_name IS
'User-facing attribute label displayed in Oracle APEX.';

COMMENT ON COLUMN ops.adre_inv_item_attribute.attribute_data_type IS
'Data type used by Oracle APEX and PL/SQL to render and validate the attribute. Valid values are CHAR, NUMBER, DATE and YES_NO.';

COMMENT ON COLUMN ops.adre_inv_item_attribute.description IS
'Functional description of the configurable attribute.';

COMMENT ON COLUMN ops.adre_inv_item_attribute.default_value IS
'General default value for the attribute. An Item Type specific configuration can override this value.';

COMMENT ON COLUMN ops.adre_inv_item_attribute.unit_of_measure IS
'Optional default unit of measure associated with the attribute.';

COMMENT ON COLUMN ops.adre_inv_item_attribute.required_flag IS
'General required indicator for the attribute. Valid values are Y and N. Item Type configuration can override this requirement.';

COMMENT ON COLUMN ops.adre_inv_item_attribute.active_flag IS
'Indicates whether the configurable attribute is available for use. Valid values are Y and N.';

COMMENT ON COLUMN ops.adre_inv_item_attribute.display_sequence IS
'Controls the default display order of the attribute within its Organization Details section.';

COMMENT ON COLUMN ops.adre_inv_item_attribute.ebs_attribute_name IS
'Optional Oracle EBS attribute, field or API parameter name associated with the application attribute.';

COMMENT ON COLUMN ops.adre_inv_item_attribute.ebs_attribute_group IS
'Optional Oracle EBS logical attribute group used to organize integration mappings.';

COMMENT ON COLUMN ops.adre_inv_item_attribute.created_by IS
'Application or database user that created the row.';

COMMENT ON COLUMN ops.adre_inv_item_attribute.creation_date IS
'Date and time when the row was created.';

COMMENT ON COLUMN ops.adre_inv_item_attribute.last_updated_by IS
'Application or database user that last updated the row.';

COMMENT ON COLUMN ops.adre_inv_item_attribute.last_update_date IS
'Date and time when the row was last updated.';

COMMENT ON COLUMN ops.adre_inv_item_attribute.last_update_login IS
'Oracle APEX session identifier or database login associated with the last update.';

COMMENT ON COLUMN ops.adre_inv_item_attribute.record_version_number IS
'Row version number used for change tracking and optimistic locking.';


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - START CHANGE
-- Purpose:
-- Automatically maintain audit information and normalize configurable
-- Item Attribute values for ADRE_INV_ITEM_ATTRIBUTE.
-- =====================================================================

CREATE OR REPLACE TRIGGER ops.adre_inv_item_attribute_biu
BEFORE INSERT OR UPDATE
ON ops.adre_inv_item_attribute
FOR EACH ROW

DECLARE

    l_user
        VARCHAR2(100);

    l_login
        VARCHAR2(100);

BEGIN

    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX user when available.
    --
    -- Use the current Oracle database user when the operation is
    -- executed outside Oracle APEX.
    -- =================================================================

    l_user :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_USER'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Resolve the Oracle APEX session identifier when available.
    -- =================================================================

    l_login :=
        NVL
        (
            SYS_CONTEXT
            (
                'APEX$SESSION',
                'APP_SESSION'
            ),
            USER
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the internal attribute code.
    --
    -- Example:
    -- lead_time_days
    --
    -- becomes:
    -- LEAD_TIME_DAYS
    -- =================================================================

    :NEW.attribute_code :=
        UPPER
        (
            TRIM
            (
                :NEW.attribute_code
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Remove unnecessary leading and trailing spaces from the
    -- user-facing attribute name.
    -- =================================================================

    :NEW.attribute_name :=
        TRIM
        (
            :NEW.attribute_name
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the configured data type.
    -- =================================================================

    :NEW.attribute_data_type :=
        UPPER
        (
            TRIM
            (
                :NEW.attribute_data_type
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize the default Unit of Measure code when populated.
    -- =================================================================

    :NEW.unit_of_measure :=
        UPPER
        (
            TRIM
            (
                :NEW.unit_of_measure
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Normalize required and active indicators.
    -- =================================================================

    :NEW.required_flag :=
        UPPER
        (
            TRIM
            (
                :NEW.required_flag
            )
        );


    :NEW.active_flag :=
        UPPER
        (
            TRIM
            (
                :NEW.active_flag
            )
        );


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Remove unnecessary leading and trailing spaces from Oracle EBS
    -- mapping information.
    -- =================================================================

    :NEW.ebs_attribute_name :=
        TRIM
        (
            :NEW.ebs_attribute_name
        );


    :NEW.ebs_attribute_group :=
        TRIM
        (
            :NEW.ebs_attribute_group
        );


    IF INSERTING THEN

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize creation audit information for a new attribute.
        -- =============================================================

        :NEW.created_by :=
            NVL
            (
                :NEW.created_by,
                l_user
            );


        :NEW.creation_date :=
            NVL
            (
                :NEW.creation_date,
                SYSDATE
            );


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Initialize the first row version.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :NEW.record_version_number,
                1
            );

    ELSE

        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Preserve the original creation audit information.
        -- =============================================================

        :NEW.created_by :=
            :OLD.created_by;

        :NEW.creation_date :=
            :OLD.creation_date;


        -- =============================================================
        -- JCALZADILLA - 22.08.2026
        -- Increment the row version number on every update.
        -- =============================================================

        :NEW.record_version_number :=
            NVL
            (
                :OLD.record_version_number,
                0
            ) + 1;

    END IF;


    -- =================================================================
    -- JCALZADILLA - 22.08.2026
    -- Refresh last-update audit information for inserts and updates.
    -- =================================================================

    :NEW.last_updated_by :=
        l_user;

    :NEW.last_update_date :=
        SYSDATE;

    :NEW.last_update_login :=
        l_login;

END;
/

-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the table exists and is VALID.
--
-- ALL_OBJECTS uses OBJECT_NAME for the object identifier.
-- =====================================================================

SELECT
    owner,
    object_name AS table_name,
    status
FROM all_objects
WHERE owner = 'OPS'
  AND object_name = 'ADRE_INV_ITEM_ATTRIBUTE'
  AND object_type = 'TABLE';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate that the audit trigger exists and is enabled.
-- =====================================================================

SELECT
    owner,
    trigger_name,
    table_name,
    status
FROM all_triggers
WHERE owner = 'OPS'
  AND trigger_name = 'ADRE_INV_ITEM_ATTRIBUTE_BIU';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Check for trigger compilation errors.
--
-- A successful trigger compilation must return zero rows.
-- =====================================================================

SELECT
    line,
    position,
    text
FROM all_errors
WHERE owner = 'OPS'
  AND name = 'ADRE_INV_ITEM_ATTRIBUTE_BIU'
  AND type = 'TRIGGER'
ORDER BY sequence;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate the table comment.
-- =====================================================================

SELECT
    table_name,
    comments
FROM all_tab_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_ATTRIBUTE';


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate all column comments.
-- =====================================================================

SELECT
    column_name,
    comments
FROM all_col_comments
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_ATTRIBUTE'
ORDER BY column_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026
-- Validate constraints created for the Item Attribute configuration.
-- =====================================================================

SELECT
    constraint_name,
    constraint_type,
    status,
    r_constraint_name
FROM all_constraints
WHERE owner = 'OPS'
  AND table_name = 'ADRE_INV_ITEM_ATTRIBUTE'
ORDER BY constraint_type,
         constraint_name;


-- =====================================================================
-- JCALZADILLA - 22.08.2026 - END CHANGE
-- =====================================================================